### ISSUE TITLE
[BUG]: .Option("query", "SELECT 0 FROM DUAL")

### ISSUE THREAD

**Issue by DoctrSpock** [dotnet/spark#1006]
**Describe the bug**
While using connection to a Oracle DB if we use an option to "SELECT 0 FROM DUAL" (I know is a stupid usage of the tool, but to better understand the problem let's use this example) we got this error.

System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseDecimal(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Convert.ToDecimal(String value, IFormatProvider provider)
   at Razorvine.Pickle.Objects.DecimalConstructor.construct(Object[] args)
   at Razorvine.Pickle.UnpicklerImplementation`1.load_reduce()
   at Razorvine.Pickle.UnpicklerImplementation`1.Load()
   at Razorvine.Pickle.Unpickler.loads(Byte[] pickledata, Int32 stackCapacity)
   at Razorvine.Pickle.Unpickler.loads(ReadOnlyMemory`1 pickledata, Int32 stackCapacity)
   at Microsoft.Spark.Utils.PythonSerDe.GetUnpickledObjects(Stream stream, Int32 messageLength)
   at Microsoft.Spark.Sql.RowCollector.Collect(ISocketWrapper socket)+MoveNext()
   at Microsoft.Spark.Sql.DataFrame.GetRows(String funcName, Object[] args)+MoveNext()

If we return any 0(Zero) value from the query we got this error.

I don´t know if we are using wrongly or there is something we gotta do, any help is any help is much appreciated. 

**To Reproduce**

1. Connect to Oracle DB
2. Execute a simple query example: "SELECT 0 FROM DUAL"

**Expected behavior**
Return a DataFrame with value 0

**Comment by GoEddie** [comment]
Can you give more of an example, I’m a bit confused as you can read or write to oracle using the jdbc driver in spark but that won’t make its way over the wire to .NET unless you collect or have a UDF or something? 

If you cast the number to an int do you still get it? Trying to understand if it is all 0’s from oracle or just decimals.

if you wrote the data frame to parquet then read it back and collect it (or whatever you are doing) does it do it then?

 Just trying to understand a bit more about the behaviour.
