### ISSUE TITLE
V2.1.0 doesn't support spark 2.4.8

### ISSUE THREAD

**Issue by meywd** [dotnet/spark#1035]
Hi Spark Team, thanks for all the efforts, we use spark in GCP and are currently upgrading images due to log4j vulnerability, and currently facing an issue since we have the data we work with that doesn't support spark 3.x and the current Google images use Spark 2.4.8, and after upgrading to the latest package v2.1.0, I got the error `Exception in thread "main" java.lang.IllegalArgumentException: Unsupported spark version used: 2.4.8. Normalized spark version used: 2.4.8. Supported versions: 2.4.0, 2.4.4, 2.4.5, 2.4.1, 2.4.3` which I knew come from here, so after digging I found that it seem to be supported in https://github.com/dotnet/spark/blob/5f5215e6a4e011c4ece07a0f425ce01657ebcf6c/src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala but still I got that error when using microsoft-spark-2-4_2.11-2.1.0.jar.

Any idea why this happens?

**Comment by Niharikadutta** [comment]
Could you please provide the microsoft-spark.jar you are using to submit your application?

**Comment by meywd** [comment]
[microsoft-spark-2-4_2.11-2.1.0.zip](https://github.com/dotnet/spark/files/8101522/microsoft-spark-2-4_2.11-2.1.0.zip)

**Comment by Niharikadutta** [comment]
@meywd I'm not able to reproduce this with the jar you provided locally, can you run `spark-submit --version` in a new shell and share the output?

**Comment by meywd** [comment]
Sure, this is what I get:
```
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.4.8
      /_/

Using Scala version 2.11.12, OpenJDK 64-Bit Server VM, 1.8.0_312
Branch HEAD
Compiled by user  on 2022-01-21T20:32:53Z
Revision 067bed8d463d77448d3e16b0f623b2e35e0a3ce1
Url https://bigdataoss-internal.googlesource.com/third_party/apache/spark
Type --help for more information.

```

**Comment by suhsteve** [comment]
The list of versions in the supported versions list `Supported versions: 2.4.0, 2.4.4, 2.4.5, 2.4.1, 2.4.3` leads me to believe that an incorrect jar is being used.  More specifically a [v0.11.0](https://github.com/dotnet/spark/blob/v0.11.0/src/scala/microsoft-spark-2.4.x/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala) jar.  Spark 2.4.6 was added to v0.12.0 and I did not see it in the error message.

**Comment by meywd** [comment]
@suhsteve you are correct, turned out the wrong jar was being submitted, the above error is solved, however I am facing another issue:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/internal/Logging$class
	at org.apache.spark.deploy.dotnet.DotnetRunner$.<init>(DotnetRunner.scala:36)
	at org.apache.spark.deploy.dotnet.DotnetRunner$.<clinit>(DotnetRunner.scala)
	at org.apache.spark.deploy.dotnet.DotnetRunner.main(DotnetRunner.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:855)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:939)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:948)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.internal.Logging$class
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 15 more
```
the referenced jars are 
```
gs://fd-wolverine-prod/catalog/libs/gcs-connector-hadoop2-2.1.5.jar
gs://fd-wolverine-prod/catalog/libs/spark-sql-kafka-0-10_2.11-2.4.8.jar
gs://fd-wolverine-prod/catalog/libs/kafka-clients-2.1.1.jar
gs://fd-wolverine-prod/catalog/libs/spark-bigquery-latest_2.12.jar
gs://fd-wolverine-prod/catalog/libs/microsoft-spark-2-4_2.11-2.1.0.jar
```

**Comment by meywd** [comment]
@Niharikadutta After opening a support ticket with GCP regarding the error above they told me to try and use jars build with scala version "2.12.10" is that possible for dotnet spark?

**Comment by Niharikadutta** [comment]
@meywd Yes, Spark 2.4.8 uses Scala 2.12 as [documented here](https://spark.apache.org/docs/2.4.8/#downloading), please use 2.12 jars and try re-submitting your jobs

**Comment by meywd** [comment]
Isn't the DotNet Spark jar for spark 2.4 `microsoft-spark-2-4_2.11-2.1.0.jar` built for Scala 2.11?

**Comment by meywd** [comment]
Thanks, will do that
