### ISSUE TITLE
[BUG]: Spark Worker throwing System.IO.FileNotFoundException exception

### ISSUE THREAD

**Issue by DeepikaPrabha** [dotnet/spark#1043]
**Describe the bug**
I am reading a csv file and a adding a column using Udf.   This csv file has around 17M rows. I am using 8 executors (8 cores * 56GB)

```
using System;
Func<Column, Column> GetCanonUrlUdf = Udf<string, string>( url => { 
    if(!String.IsNullOrEmpty(url)) return "Dummy";
    return "";
});


var path = "<CSV file path>"

var df = spark.Read().Option("header", false).Option("inferShchema", true).Option("delimiter", "\t").Csv(path);
//Display(df);
df = df.WithColumn("newCol", UDFfunction(df["_c0"]));
Display(df);
```
When I do display, just after reading CSV, at line no (2), I don't get any error but if I  do display at line no 4, it throws me below error.

```
[2022-03-14T11:35:06.9462243Z] [vm-e3201287] [Error] [TaskRunner] [1] ProcessStream() failed with exception: System.IO.FileNotFoundException: Assembly 'ℛ*2c8e9aaa-736f-41af-87d1-d96f674af627#1-26, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' file not found ''
   at Microsoft.Spark.Utils.UdfSerDe.<>c.b__10_0(TypeData td) in /_/src/csharp/Microsoft.Spark/Utils/UdfSerDe.cs:line 270
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Spark.Utils.UdfSerDe.DeserializeType(TypeData typeData) in /_/src/csharp/Microsoft.Spark/Utils/UdfSerDe.cs:line 261
   at Microsoft.Spark.Utils.UdfSerDe.Deserialize(UdfData udfData) in /_/src/csharp/Microsoft.Spark/Utils/UdfSerDe.cs:line 160
   at Microsoft.Spark.Utils.CommandSerDe.DeserializeUdfs[T](UdfWrapperData data, Int32& nodeIndex, Int32& udfIndex) in /_/src/csharp/Microsoft.Spark/Utils/CommandSerDe.cs:line 333
   at Microsoft.Spark.Utils.CommandSerDe.Deserialize[T](Stream stream, SerializedMode& serializerMode, SerializedMode& deserializerMode, String& runMode) in /_/src/csharp/Microsoft.Spark/Utils/CommandSerDe.cs:line 306
   at Microsoft.Spark.Worker.Processor.CommandProcessor.ReadSqlCommands(PythonEvalType evalType, Stream stream) in D:\a\1\s\src\csharp\Microsoft.Spark.Worker\Processor\CommandProcessor.cs:line 187
   at Microsoft.Spark.Worker.Processor.CommandProcessor.ReadSqlCommands(PythonEvalType evalType, Stream stream, Version version) in D:\a\1\s\src\csharp\Microsoft.Spark.Worker\Processor\CommandProcessor.cs:line 101
   at Microsoft.Spark.Worker.Processor.CommandProcessor.Process(Stream stream) in D:\a\1\s\src\csharp\Microsoft.Spark.Worker\Processor\CommandProcessor.cs:line 43
   at Microsoft.Spark.Worker.Processor.PayloadProcessor.Process(Stream stream) in D:\a\1\s\src\csharp\Microsoft.Spark.Worker\Processor\PayloadProcessor.cs:line 83
   at Microsoft.Spark.Worker.TaskRunner.ProcessStream(Stream inputStream, Stream outputStream, Version version, Boolean& readComplete) in D:\a\1\s\src\csharp\Microsoft.Spark.Worker\TaskRunner.cs:line 144
[2022-03-14T11:35:06.9475863Z] [vm-e3201287] [Error] [TaskRunner] [2] ProcessStream() failed with exception: System.IO.FileNotFoundException: Assembly 'ℛ*2c8e9aaa-736f-41af-87d1-d96f674af627#1-26, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' file not found ''
   at Microsoft.Spark.Utils.UdfSerDe.<>c.b__10_0(TypeData td) in /_/src/csharp/Microsoft.Spark/Utils/UdfSerDe.cs:line 270
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
```

I have been getting this error intermittently. Can you please help me with what is the root cause for this problem? Is it a memory issue?

**Comment by Niharikadutta** [comment]
@DeepikaPrabha how are you submitting this application, is it batch or interactive?

**Comment by DeepikaPrabha** [comment]
@Niharikadutta I am not using UDF in the same cell where it is registered.  This is the flow.
Cell1(C#) -> UDF1
Cell2(C#) -> UDF2
Cell3(C#) -> UDF1 => working fine
Cell4(Python)-> Some operation
Cell5(C#) -> UDF1 -> Fails with above error

**Comment by Niharikadutta** [comment]
@DeepikaPrabha your failing notebook works if you remove the empty line after the magic command and before UDF definition. Can you please try on your end after removing the whiteline?
`%%csharp
using System;
Func<Column, Column> SecondUDF = Udf<string, string>( url => url + " second udf");`

**Comment by DeepikaPrabha** [comment]
yes, it worked for me after removing empty line after magic command. Is there any explanation on this behavior?
