### ISSUE TITLE
[BUG]: Can't deploy to databricks  anymore

### ISSUE THREAD

**Issue by fwaris** [dotnet/spark#1074]
**Describe the bug**

dotnet spark jobs do not run on the latest version of databricks clusters in Azure.
This worked before (about 3 or so months ago) but is no longer working.
With the db_init.sh (see attached) based on the one given in the repository there is no log output of any kind.
Without db_init.sh there is an error in the stderr log:

```scala
Caused by: java.lang.NullPointerException
	at com.databricks.backend.daemon.driver.WsfsDriverHttpClient.<init>(WSFSDriverHttpClient.scala:26)
	at com.databricks.backend.daemon.driver.WSFSCredentialForwardingHelper$.<init>(WorkspaceLocalFileSystem.scala:284)
	at com.databricks.backend.daemon.driver.WSFSCredentialForwardingHelper$.<clinit>(WorkspaceLocalFileSystem.scala)
	... 28 more
```

1. create a simple dotnet spark job that reads a csv file and shows the results
2. publish the job
3. deploy the job to databricks cluser 
4. run the job
5. note the job fails and there is no log output of any kind

**Expected behavior**
The job should not fail
[db_init.zip](https://github.com/dotnet/spark/files/8919459/db_init.zip)

**Comment by fwaris** [comment]
The only error I can see is this:
```
Failed: Unexpected failure while waiting for the cluster (0616-164143-ppdc6hs5) to be ready.Cause Unexpected state for cluster (0616-164143-ppdc6hs5): INIT_SCRIPT_FAILURE(CLIENT_ERROR): instance_id:bcca0478a4e04609932f04433af69bbb,databricks_error_message:Cluster scoped init script dbfs:/FileStore/faisal/db-init.sh failed: Timed out with exception after 5 attempts (debugStr = 'Reading remote file for init script'), Caused by: java.io.FileNotFoundException: /3903478365213635/FileStore/faisal/db-init.sh: No such file or directory.
```

I can see this message when I hover over the 'status' icon of the failed job in databricks UI.

It seems that the server cannot find the script (but the script is there at the path specified).

**Comment by davinder-veeam** [comment]
@fwaris , you can use stdout and stderr from init scripts, unfortunely, init script logs are only exported by databricks if you enable cluster logs then you should see folder likes

```bash
$ databricks fs ls dbfs:/cluster-logs/<cluster-id>/
driver
eventlog
executor
init_scripts.    <--- here stdout and stderr will provided to you of the init scripts
```
