### ISSUE TITLE
[BUG]: After upgrading spark to 3.3.0, unable to run spark-submit commands

### ISSUE THREAD

**Issue by hflexgrig** [dotnet/spark#1080]
Hi guys, I'm getting this exception, after upgrading spark version on my mac machine

Exception in thread "main" java.lang.IllegalArgumentException: Unsupported spark version used: '3.3.0'. Normalized spark version used: '3.3.0'. Supported spark major.minor version: '3.2'.

Any suggestions? Btw I tried downgrade back to 3.2 , but it won't work.

**Comment by Niharikadutta** [comment]
@hflexgrig Thank you for opening the issue, we are yet to add support for Spark 3.3.0. Can you share the exception stacktrace and Spark .NET version you are using when you face issue with Spark 3.2?

**Comment by hflexgrig** [comment]
Ah sorry, I've already downgraded my apache spark from 3.3 to 3.2.1, can copy stacktrace anymore.

**Comment by Niharikadutta** [comment]
Got it, please re-open the issue if you face this again. Cannot investigate further as stacktrace is not provided,

**Comment by zHaytam** [comment]
```
Exception in thread "main" java.lang.IllegalArgumentException: Unsupported spark version used: '3.3.0'. Normalized spark version used: '3.3.0'. Supported spark major.minor version: '3.2'.
        at org.apache.spark.util.dotnet.Utils$.validateSparkVersions(Utils.scala:217)
        at org.apache.spark.deploy.dotnet.DotnetRunner$.main(DotnetRunner.scala:61)
        at org.apache.spark.deploy.dotnet.DotnetRunner.main(DotnetRunner.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:958)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by zHaytam** [comment]
Even 3.2.2 is not supported...

**Comment by jorgemrDev** [comment]
i installed 3.2.0 ...same issue
![image](https://user-images.githubusercontent.com/9201028/211171709-6b4bd46f-a0d2-4524-845d-351b8baac8ec.png)
