### ISSUE TITLE
Worker trying to locate application file in %DotnetWorkerPath%, even though the application was launched from a separate folder 

### ISSUE THREAD

**Issue by shyamalshukla** [dotnet/spark#123]
**Describe the bug**
When using Udf, worker tries to locate the application file in %DotnetWorkerPath% folder, even though the application file's path specified in spark-submit command line, was from a different application folder

**To Reproduce**

Submission command: [Application folder - C:\app\shared\SparkNet]

spark-submit --class org.apache.spark.deploy.DotnetRunner --deploy-mode cluster --master spark://172.23.198.159:7077 C:\app\shared\SparkNet\microsoft-spark-2.4.x-0.2.0.jar C:\app\shared\SparkNet\NetForSparkDemo.exe

Application code:

            SparkSession spark = SparkSession.Builder()
                .AppName("SampleSparkApplication")
                .Master($"spark://{sparkServer}:7077")
                .GetOrCreate();

            DataFrame frame = spark
                    .ReadStream()
                    .Schema("name string, age int")
                    .Json("file:/C:/app/shared/SparkNet/test*.json");

            Func<Column, Column> AddSuffix = Udf<string, string>((i) => i + "_Suffix");
            Func<Column, Column> Add10 = Udf<int?, int>((i) => i.HasValue ? i.Value + 10 : 0);

            DataFrame frame1 = frame.Select(new Column[] { AddSuffix(frame["name"]), Add10(frame["age"]) });

            StreamingQuery query = frame1.WriteStream()
                .Format("Console")
                .Option("checkpointLocation", $"hdfs://{sparkServer}:9000/user/ContainerAdministrator/Checkpoint/")
                .Start();

            query.AwaitTermination();

**Expected behavior**
There shouldn't be a need to copy the application file in the %DotnetWorkerPath% folder

Exception call stack:

Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3, 172.23.198.159, executor 0): org.apache.spark.api.python.PythonException: System.IO.FileNotFoundException: Could not load file or assembly 'file:///C:\app\Microsoft.Spark.Worker.net461.win-x64-0.2.0\Microsoft.Spark.Worker-0.2.0\NetForSparkDemo.exe' or one of its dependencies. The system cannot find the file specified.
File name: 'file:///C:\app\Microsoft.Spark.Worker.net461.win-x64-0.2.0\Microsoft.Spark.Worker-0.2.0\NetForSparkDemo.exe'

   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Microsoft.Spark.Utils.UdfSerDe.LoadAssembly(String manifestModuleName)
   at Microsoft.Spark.Utils.UdfSerDe.<>c__DisplayClass10_0.<DeserializeType>b__0(TypeData td)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Spark.Utils.UdfSerDe.Deserialize(UdfData udfData)
   at Microsoft.Spark.Utils.CommandSerDe.DeserializeUdfs[T](UdfWrapperData data, Int32& nodeIndex, Int32& udfIndex)
   at Microsoft.Spark.Utils.CommandSerDe.Deserialize[T](Stream stream, SerializedMode& serializerMode, SerializedMode& deserializerMode, String& runMode)
   at Microsoft.Spark.Worker.Processor.CommandProcessor.ReadSqlCommands(PythonEvalType evalType, Stream stream)
   at Microsoft.Spark.Worker.Processor.CommandProcessor.Process(Stream stream)
   at Microsoft.Spark.Worker.Processor.PayloadProcessor.Process(Stream stream)
   at Microsoft.Spark.Worker.TaskRunner.ProcessStream(Stream inputStream, Stream outputStream, Version version, Boolean& readComplete)

**Comment by imback82** [comment]
Your UDF is embedded inside the NetForSparkDemo.exe, so the worker needs it to look up the UDF and execute it.

**Comment by shyamalshukla** [comment]
If I move the UDF code, out to another file, the worker would then need access to that file .. can the worker access the UDF from the application folder. For a shared environment, copying the application binaries to the worker folder will not be possible, since this can cause conflicts. 

Are there any alternatives to not have to copy the application code (or part of) to the worker folder

**Comment by imback82** [comment]
You can use `spark-submit`'s `--files` option to copy over assemblies that embed UDFs. They will be copied over to a unique directory for your job, so it will not cause any conflicts.

**Comment by rapoth** [comment]
@shyamalshukla : Did the suggestion work for you?

**Comment by imback82** [comment]
@shyamalshukla: Please reopen the issue if the suggestion didn't work out.
