### ISSUE TITLE
vscode debug "StructuredNetworkWordCount"，error：'JVM method execution failed: Nonstatic method awaitTermination failed for class 42 when called with no arguments'

### ISSUE THREAD

**Issue by wxzz** [dotnet/spark#160]
**vscode debug "StructuredNetworkWordCount"：**
1.cmd $：nc -lk 9999
2.cmd $：spark-submit --class org.apache.spark.deploy.DotnetRunner --master local microsoft-spark-2.4.x-0.3.0.jar debug
3.code：args=new string[]{"local","9999"};。    The rest of the code stays the same in the StructuredNetworkWordCount.cs。
---------------------------------------------------------------------------------------------------
**-pc0:~$ nc -lk 9999**
www.ineuos.net
www.ineuos.net
enter

**cmd $:spark-submit --class org.apache.spark.deploy.DotnetRunner --master local microsoft-spark-2.4.x-0.3.0.jar debug  enter**
19/06/29 10:44:32 ERROR MicroBatchExecution: Query [id = 91d03ac3-e6d6-4b98-8b5e-54cd4e74fcb9, runId = 83876997-9f46-468f-b1b9-d730ac67a892] terminated with error
java.net.UnknownHostException: local
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at org.apache.spark.sql.execution.streaming.sources.TextSocketMicroBatchReader.initialize(socket.scala:92)
	at org.apache.spark.sql.execution.streaming.sources.TextSocketMicroBatchReader.planInputPartitions(socket.scala:158)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2ScanExec.partitions$lzycompute(DataSourceV2ScanExec.scala:76)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2ScanExec.partitions(DataSourceV2ScanExec.scala:75)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2ScanExec.outputPartitioning(DataSourceV2ScanExec.scala:65)
	at org.apache.spark.sql.execution.exchange.EnsureRequirements$$anonfun$org$apache$spark$sql$execution$exchange$EnsureRequirements$$ensureDistributionAndOrdering$1.apply(EnsureRequirements.scala:150)
	at org.apache.spark.sql.execution.exchange.EnsureRequirements$$anonfun$org$apache$spark$sql$execution$exchange$EnsureRequirements$$ensureDistributionAndOrdering$1.apply(EnsureRequirements.scala:149)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:296)
	at org.apache.spark.sql.execution.exchange.EnsureRequirements.org$apache$spark$sql$execution$exchange$EnsureRequirements$$ensureDistributionAndOrdering(EnsureRequirements.scala:149)
	at org.apache.spark.sql.execution.exchange.EnsureRequirements$$anonfun$apply$1.applyOrElse(EnsureRequirements.scala:304)
	at org.apache.spark.sql.execution.exchange.EnsureRequirements$$anonfun$apply$1.applyOrElse(EnsureRequirements.scala:296)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:278)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:278)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:70)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:277)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:275)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:275)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:326)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:324)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:275)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:275)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:275)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:326)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:324)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:275)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:275)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:275)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:326)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:324)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:275)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:275)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:275)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:326)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:324)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:275)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:275)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:275)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:326)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:324)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:275)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:275)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:275)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:326)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:324)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:275)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:275)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:275)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:326)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:324)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:275)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:275)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:275)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:326)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:324)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:275)
	at org.apache.spark.sql.execution.exchange.EnsureRequirements.apply(EnsureRequirements.scala:296)
	at org.apache.spark.sql.execution.exchange.EnsureRequirements.apply(EnsureRequirements.scala:38)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$prepareForExecution$1.apply(QueryExecution.scala:87)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$prepareForExecution$1.apply(QueryExecution.scala:87)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at org.apache.spark.sql.execution.QueryExecution.prepareForExecution(QueryExecution.scala:87)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:77)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:77)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$4.apply(MicroBatchExecution.scala:528)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$4.apply(MicroBatchExecution.scala:519)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch(MicroBatchExecution.scala:519)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply$mcV$sp(MicroBatchExecution.scala:198)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1.apply$mcZ$sp(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:56)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:160)
	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:281)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:193)
19/06/29 10:44:32 ERROR DotnetBackendHandler: methods:
19/06/29 10:44:32 ERROR DotnetBackendHandler: public org.apache.spark.sql.SparkSession org.apache.spark.sql.execution.streaming.StreamingQueryWrapper.sparkSession()
19/06/29 10:44:32 ERROR DotnetBackendHandler: public void org.apache.spark.sql.execution.streaming.StreamingQueryWrapper.explain()
19/06/29 10:44:32 ERROR DotnetBackendHandler: public void org.apache.spark.sql.execution.streaming.StreamingQueryWrapper.explain(boolean)
19/06/29 10:44:32 ERROR DotnetBackendHandler: public org.apache.spark.sql.execution.streaming.StreamExecution org.apache.spark.sql.execution.streaming.StreamingQueryWrapper.streamingQuery()
19/06/29 10:44:32 ERROR DotnetBackendHandler: public java.util.UUID org.apache.spark.sql.execution.streaming.StreamingQueryWrapper.runId()
19/06/29 10:44:32 ERROR DotnetBackendHandler: public void org.apache.spark.sql.execution.streaming.StreamingQueryWrapper.processAllAvailable()
19/06/29 10:44:32 ERROR DotnetBackendHandler: public java.lang.String org.apache.spark.sql.execution.streaming.StreamingQueryWrapper.explainInternal(boolean)
19/06/29 10:44:32 ERROR DotnetBackendHandler: public org.apache.spark.sql.streaming.StreamingQueryProgress[] org.apache.spark.sql.execution.streaming.StreamingQueryWrapper.recentProgress()
19/06/29 10:44:32 ERROR DotnetBackendHandler: public org.apache.spark.sql.streaming.StreamingQueryProgress org.apache.spark.sql.execution.streaming.StreamingQueryWrapper.lastProgress()
19/06/29 10:44:32 ERROR DotnetBackendHandler: public scala.Option org.apache.spark.sql.execution.streaming.StreamingQueryWrapper.exception()
19/06/29 10:44:32 ERROR DotnetBackendHandler: public void org.apache.spark.sql.execution.streaming.StreamingQueryWrapper.awaitTermination()
19/06/29 10:44:32 ERROR DotnetBackendHandler: public boolean org.apache.spark.sql.execution.streaming.StreamingQueryWrapper.awaitTermination(long)
19/06/29 10:44:32 ERROR DotnetBackendHandler: public boolean org.apache.spark.sql.execution.streaming.StreamingQueryWrapper.isActive()
19/06/29 10:44:32 ERROR DotnetBackendHandler: public java.lang.String org.apache.spark.sql.execution.streaming.StreamingQueryWrapper.name()
19/06/29 10:44:32 ERROR DotnetBackendHandler: public void org.apache.spark.sql.execution.streaming.StreamingQueryWrapper.stop()
19/06/29 10:44:32 ERROR DotnetBackendHandler: public org.apache.spark.sql.streaming.StreamingQueryStatus org.apache.spark.sql.execution.streaming.StreamingQueryWrapper.status()
19/06/29 10:44:32 ERROR DotnetBackendHandler: public java.util.UUID org.apache.spark.sql.execution.streaming.StreamingQueryWrapper.id()
19/06/29 10:44:32 ERROR DotnetBackendHandler: public final void java.lang.Object.wait(long,int) throws java.lang.InterruptedException
19/06/29 10:44:32 ERROR DotnetBackendHandler: public final native void java.lang.Object.wait(long) throws java.lang.InterruptedException
19/06/29 10:44:32 ERROR DotnetBackendHandler: public final void java.lang.Object.wait() throws java.lang.InterruptedException
19/06/29 10:44:32 ERROR DotnetBackendHandler: public boolean java.lang.Object.equals(java.lang.Object)
19/06/29 10:44:32 ERROR DotnetBackendHandler: public java.lang.String java.lang.Object.toString()
19/06/29 10:44:32 ERROR DotnetBackendHandler: public native int java.lang.Object.hashCode()
19/06/29 10:44:32 ERROR DotnetBackendHandler: public final native java.lang.Class java.lang.Object.getClass()
19/06/29 10:44:32 ERROR DotnetBackendHandler: public final native void java.lang.Object.notify()
19/06/29 10:44:32 ERROR DotnetBackendHandler: public final native void java.lang.Object.notifyAll()
19/06/29 10:44:32 ERROR DotnetBackendHandler: args:

**vscode console info：**
[2019-06-29T02:44:32.8047615Z] [wxzz-pc0] [Exception] [JvmBridge] JVM method execution failed: Nonstatic method awaitTermination failed for class 42 when called with no arguments
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)

**how to solve problems？？？？**

**Comment by suhsteve** [comment]
`java.net.UnknownHostException: local`  can you try localhost ?

**Comment by wxzz** [comment]
thanks
