### ISSUE TITLE
[Need help] Udf used in WithColumn not working

### ISSUE THREAD

**Issue by raberana** [dotnet/spark#177]
I tried using a UDF inside a WithColumn but it seems to be not working. 

            SparkSession spark = SparkSession
                         .Builder()
                         .AppName("saturn")
                         .GetOrCreate();

            DataFrame df = spark.Read().Json("sample-application");

            df.PrintSchema();

            df.Show();
            
            Func<Column, Column> mapFromAnotherColumn = Udf<string, string>((name) => "A" + name);
            
            df = df.WithColumn("oldApplicationNumber", mapFromAnotherColumn(df["applicationNumber"]));

            df.Show();

The initial data frame is shown successfully but the next display (show()) is not happening.

I understand that the second parameter of WithColumn must accept a Spark.Sql.Column and I know that the UDFs return this type. I'm not just sure why this fails though.

I'm not sure but these logs may help.

        at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:452)
        at org.apache.spark.sql.execution.python.PythonUDFRunner$$anon$1.read(PythonUDFRunner.scala:81)
        at org.apache.spark.sql.execution.python.PythonUDFRunner$$anon$1.read(PythonUDFRunner.scala:64)
        at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:406)
        at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:255)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:247)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:121)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:403)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:409)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
        er\Processor\PayloadProcessor.cs:line 71
        at Microsoft.Spark.Worker.TaskRunner.ProcessStream(Stream inputStream, Stream 
        outputStream, Version version, Boolean& readComplete) in 
        D:\a\1\s\src\csharp\Microsoft.Spark.Worker\TaskRunner.cs:line 136

**Comment by rapoth** [comment]
@raberana: Can you provide the full log trace please?

**Comment by raberana** [comment]
Here's the complete logs. Thank you. [logs.txt](https://github.com/dotnet/spark/files/3402889/logs.txt)

**Comment by imback82** [comment]
```
[2019-07-17T16:37:53.7308874Z] [RBLADE] [Error] [TaskRunner] [0] ProcessStream() failed with exception: System.IO.FileNotFoundException: Could not load file or assembly 'C:\spark\Microsoft.Spark.Worker-0.3.0\Saturn.dll'. The system cannot find the file specified.
File name: 'C:\spark\Microsoft.Spark.Worker-0.3.0\Saturn.dll'
```
Can you ensure `Saturn.dll` is located either in the directory you are launching `spark-submit` or in the worker directory?

**Comment by raberana** [comment]
@imback82 wow it worked! to be honest i didn't mind that error because i see it even in a very simple dataframe show sample (no udfs or withcolumn), and the [tutorial](https://dotnet.microsoft.com/learn/data/spark-tutorial/run) didn't mention this thing though.

thanks!
