### ISSUE TITLE
how to use debug mode

### ISSUE THREAD

**Issue by liugaocn** [dotnet/spark#195]
**I use the new version of dotnet-spark 0.4.0. And Spark 2.4.3, VS 2019, .NetCore 2.2, Windows 10.
I just generated the right jars with command lines. But the only difference is that I didn't use git. Instead, I downloaded the files and unzipped to a "random" folder.**
spark-submit   --class org.apache.spark.deploy.DotnetRunner   --master local C:\Spark\dotnet-spark\src\scala\microsoft-spark-2.4.x\target\microsoft-spark-2.4.x-0.4.0.jar debug
**then I get:**
log4j:WARN No appenders could be found for logger (org.apache.spark.deploy.SparkSubmit$$anon$2).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

**If I don't use a full path to the jar file as:**
spark-submit   --class org.apache.spark.deploy.DotnetRunner   --master local microsoft-spark-2.4.x-0.4.0.jar debug
**then I get:**
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
19/08/01 09:09:36 WARN DependencyUtils: Local jar C:\Users\Gao\microsoft-spark-2.4.x-0.4.0.jar does not exist, skipping.
19/08/01 09:09:36 WARN SparkSubmit$$anon$2: Failed to load org.apache.spark.deploy.DotnetRunner.
java.lang.ClassNotFoundException: org.apache.spark.deploy.DotnetRunner
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.apache.spark.util.Utils$.classForName(Utils.scala:238)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:810)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
19/08/01 09:09:36 INFO ShutdownHookManager: Shutdown hook called
19/08/01 09:09:36 INFO ShutdownHookManager: Deleting directory C:\Users\Gao\AppData\Local\Temp\spark-238f0320-4d85-478d-955c-e4a9cd369aae
**I guess this is kinda as expected, since my computer doesn't know where this file is.**

I used spark with c# on another PC, but it worked fine.

**Comment by imback82** [comment]
Can you try `org.apache.spark.deploy.dotnet.DotnetRunner`? There was a change in 0.4.0 which is described in the release notes.

**Comment by liugaocn** [comment]
Thanks. It worked for me. I didn't notice the release note.
But when I read json
``var df = spark.Read().Json("people.json");``
It wouldn't run.
``System.Exception
  HResult=0x80131500
  Message=JVM method execution failed: Nonstatic method json failed for class 5 when called with 1 arguments ([Index=1, Type=String[], Value=System.String[]], )
  Source=Microsoft.Spark
  StackTrace:
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object arg0)
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallNonStaticJavaMethod(JvmObjectReference objectId, String methodName, Object arg0)
   at Microsoft.Spark.Sql.DataFrameReader.LoadSource(String source, String[] paths)
   at ConsoleApp2.Program.Main(String[] args) in C:\Users\Gao\source\repos\ConsoleApp2\ConsoleApp2\Program.cs:line 11``
IT seems to me that there is no other problems. Java, mvn, spark-shell all work fine.

**Comment by suhsteve** [comment]
Can you pass the full path to `people.json` ?

**Comment by liugaocn** [comment]
It is fine now. I just found out the problem. IT is the wrong path. Thanks @suhsteve
