### ISSUE TITLE
 [Info] [ConfigurationService] 'DOTNETBACKEND_PORT' environment variable is not set.

### ISSUE THREAD

**Issue by 939481896** [dotnet/spark#218]
我环境都调试好了，运行我的demo也能正常出结果，但是有一个问题，就是开始运行的时候始终会出现标题中的提示，不知道是什么问题，谁能帮助一下我呢？
![image](https://user-images.githubusercontent.com/35762769/63652056-801a4700-c78e-11e9-8191-fde83a209781.png)

**Comment by imback82** [comment]
Can you please translate this to English?

**Comment by imback82** [comment]
Looks like you are running this in debug mode.

**Comment by 939481896** [comment]
I am sorry.Yes ,you are right.I'm running the application in debug mode.But when I run this,the program show me  the 'DOTNETBACKEND_PORT environment variable is not set'.I don't know why ?Could you tell me?Thanks.

**Comment by imback82** [comment]
In debug mode, 5567 port is always used so that the C# application knows which port to connect to.

**Comment by gopala000** [comment]
I'm stuck with this issue in both release and debug mode. What needs to be run to listen in port 5567 of localhost?

```
[2020-07-01T05:46:47.4522623Z] [DESKTOP-R0OOU67] [Info] [ConfigurationService] 'DOTNETBACKEND_PORT' environment variable is not set.
[2020-07-01T05:46:47.4532615Z] [DESKTOP-R0OOU67] [Info] [ConfigurationService] Using port 5567 for connection.
[2020-07-01T05:46:47.4552597Z] [DESKTOP-R0OOU67] [Info] [JvmBridge] JvMBridge port is 5567
[2020-07-01T05:46:53.1147348Z] [DESKTOP-R0OOU67] [Exception] [JvmBridge] No connection could be made because the target machine actively refused it 127.0.0.1:5567
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at Microsoft.Spark.Network.DefaultSocketWrapper.Connect(IPAddress remoteaddr, Int32 port, String secret)
   at Microsoft.Spark.Interop.Ipc.JvmBridge.GetConnection()
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:5567
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at Microsoft.Spark.Network.DefaultSocketWrapper.Connect(IPAddress remoteaddr, Int32 port, String secret)
   at Microsoft.Spark.Interop.Ipc.JvmBridge.GetConnection()
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallStaticJavaMethod(String className, String methodName, Object[] args)
   at Microsoft.Spark.Sql.Builder..ctor()
   at Microsoft.Spark.Examples.Sql.Streaming.StructuredNetworkWordCount.Run(String[] args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.Spark.Examples.Program.Main(String[] args)

C:\Marketly\git\spark\artifacts\bin\Microsoft.Spark.CSharp.Examples\Release\net461\Microsoft.Spark.CSharp.Examples.exe (process 39212) exited with code -532462766.
Press any key to close this window . . .
```

**Comment by imback82** [comment]
Looks like you are running it from visual studio? If so, you should follow https://github.com/dotnet/spark/blob/master/docs/developer-guide.md#debugging-spark-net-application

**Comment by gopala000** [comment]
Yes, I'm running the examples from VS 2019.  I just opened the `Microsoft.Spark ` solution in VS and set the startup project as `Microsoft.Spark.CSharp.Examples` and ran it.  But, the link you sent is about running `spark-submit`.  The example's readme.md doesn't mention about running it. Am I missing some step? @imback82

**Comment by imback82** [comment]
If you are launching your C# application directly from VS, you need to run `spark-submit` as described above. (C# application is just a wrapper around the JAVA application launched from `spark-submit`, so you need the JAVA app - `DotnetRunner` - running). The tutorial launches your C# application via `spark-submit` (indirectly launched by JAVA app - `DotnetRunner`). Does this make sense?

**Comment by chen-xin-lay** [comment]
> Looks like you are running it from visual studio? If so, you should follow https://github.com/dotnet/spark/blob/master/docs/developer-guide.md#debugging-spark-net-application

Thank you for your help

**Comment by Devtr0n** [comment]
I am also trying to accomplish debugging a .NET app (example) and get this error. I made sure my environment variables are correct, but I am unsure where the .jar file is located for this step?

`spark-submit \
  --class org.apache.spark.deploy.dotnet.DotnetRunner \
  --master local \
  <path-to-microsoft-spark-jar> \
  debug`
  
  where the heck is this hiding?
  
  `<path-to-microsoft-spark-jar>`

**Comment by 939481896** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Devtr0n** [comment]
Nevermind, I see the .jar files in the nuget package files. My apologies.
