### ISSUE TITLE
How to Connect to the SqlServer?

### ISSUE THREAD

**Issue by 939481896** [dotnet/spark#220]
I use this code ' DataFrame jdbcDf = spark.Read()
                .Format("jdbc")
                .Options(
                    new Dictionary<string, string>
                    {
                        {"url", "jdbc:sqlserver://localhost:1433;DatabaseName=hifit"},
                        {"dbtable", "Customer"},
                        {"user", "sa"},
                        {"password", "P@ssword"}
                    })
                .Load();' to connect the sqlserver,when I debug this,it tells me that ' java.sql.SQLException: No suitable driver'.Need I install some drivers?

**Comment by 939481896** [comment]
Yes,I have downloaded the driver from  https://download.microsoft.com/download/0/7/C/07CC7CE4-D7F9-44FC-B2FD-8C289A4F941F/sqljdbc_7.0.0.0_chs.tar.gz,and seted it up.But it doesn't work.I don't know why? Maybe some config was wrong!

**Comment by 939481896** [comment]
Here is the error info:

**Comment by 939481896** [comment]
And this is the console error info:

[2019-08-28T16:07:10.2710448Z] [WIN-WUYUSHAN] [Error] [JvmBridge] JVM method execution failed: Nonstatic method load failed for class 49 when called with 1 arguments ([Index=1, Type=String[], Value=System.String[]], )
[2019-08-28T16:07:10.2713234Z] [WIN-WUYUSHAN] [Error] [JvmBridge] java.sql.SQLException: No suitable driver
        at java.sql.DriverManager.getDriver(Unknown Source)
        at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions$$anonfun$7.apply(JDBCOptions.scala:85)
        at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions$$anonfun$7.apply(JDBCOptions.scala:85)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:84)
        at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:35)
        at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:34)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:341)
        at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:239)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:227)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:184)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.handleMethodCall(DotnetBackendHandler.scala:162)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.handleBackendRequest(DotnetBackendHandler.scala:102)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.channelRead0(DotnetBackendHandler.scala:29)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.channelRead0(DotnetBackendHandler.scala:24)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Unknown Source)

**Comment by 939481896** [comment]
This is the classpath config:
![image](https://user-images.githubusercontent.com/35762769/63873444-316ce700-c9f2-11e9-8a81-265c0080100d.png)

**Comment by GoEddie** [comment]
Two things, first include the name of the driver in the options:

`var df = spark.Read().Format("jdbc")
                .Options(
                    new Dictionary<string, string>
                    {
                        {"url", "jdbc:sqlserver://localhost:1433;DatabaseName=databaseName"},
                        {"driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver" },
                        {"dbtable", "sysprocesses"},
                        {"user", "sa"},
                        {"password", "blag"}
                    }).Load();`

Then instead of using classpath, get spark-submit to load the jar using: `--jars url`, in my case I have the sql server jdbc driver locally so run:

```
spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --jars file:///spark/drivers/sqljdbc_7.0/chs/mssql-jdbc-7.0.0.jre8.jar  --master local microsoft-spark-2.4.x-0.4.0.jar BLAH BLAH
```

**Comment by 939481896** [comment]
There is something wrong on my PC when I run the code 'spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --jars "c:/program files/Java/mssql-jdbc-7.0.0.jre8.jar"  --master local microsoft-spark-2.3.x-0.4.0.jar BLAH BLAH'.
The error info is :FirstSparkapp\FirstCoreSparkapp\bin\Debug\netcoreapp2.1> spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --jars "c:/program files/Java/mssql-jdbc-7.0.0.jre8.jar"  --master local microsoft-spark-2.3.x-0.4.0.jar BLAH BLAH
2019-08-29 09:11:32 INFO  DotnetRunner:54 - Starting DotnetBackend with BLAH.
2019-08-29 09:11:32 INFO  DotnetRunner:54 - Port number used by DotnetBackend is 56101
2019-08-29 09:11:32 INFO  DotnetRunner:54 - Adding key=spark.jars and value=file:///c:/program%20files/Java/mssql-jdbc-7.0.0.jre8.jar,file:/H:/WorkSpace/dotnet/大数据/FirstSparkapp/FirstCoreSparkapp/bin/Debug/netcoreapp2.1/microsoft-spark-2.3.x-0.4.0.jar to environment
2019-08-29 09:11:32 INFO  DotnetRunner:54 - Adding key=spark.app.name and value=org.apache.spark.deploy.dotnet.DotnetRunner to environment
2019-08-29 09:11:32 INFO  DotnetRunner:54 - Adding key=spark.submit.deployMode and value=client to environment
2019-08-29 09:11:32 INFO  DotnetRunner:54 - Adding key=spark.master and value=local to environment
2019-08-29 09:11:32 INFO  DotnetRunner:54 - Adding key=spark.repl.local.jars and value=file:///c:/program%20files/Java/mssql-jdbc-7.0.0.jre8.jar to environment
2019-08-29 09:11:32 ERROR DotnetRunner:70 - Cannot run program "BLAH": CreateProcess error=2, 系统找不到指定的文件。
 [Ljava.lang.StackTraceElement;@241e8ea6
2019-08-29 09:11:32 INFO  ShutdownHookManager:54 - Shutdown hook called
2019-08-29 09:11:32 INFO  ShutdownHookManager:54 - Deleting directory C:\Users\Administrator\AppData\Local\Temp\spark-215a5632-5647-4377-8a1f-1c679241e0e2.

And then I user code 'spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --jars "c:/progra~1/Java/mssql-jdbc-7.0.0.jre8.jar"  --master local microsoft-spark-2.3.x-0.4.0.jar BLAH BLAH' .The error info is :
FirstSparkapp\FirstCoreSparkapp\bin\Debug\netcoreapp2.1> spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --jars "c:/progra~1/Java/mssql-jdbc-7.0.0.jre8.jar"  --master local microsoft-spark-2.3.x-0.4.0.jar BLAH BLAH
Exception in thread "main" java.io.IOException: No FileSystem for scheme: c
        at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2660)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
        at org.apache.spark.deploy.DependencyUtils$.org$apache$spark$deploy$DependencyUtils$$resolveGlobPath(DependencyUtils.scala:165)
        at org.apache.spark.deploy.DependencyUtils$$anonfun$resolveGlobPaths$2.apply(DependencyUtils.scala:146)
        at org.apache.spark.deploy.DependencyUtils$$anonfun$resolveGlobPaths$2.apply(DependencyUtils.scala:144)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
        at org.apache.spark.deploy.DependencyUtils$.resolveGlobPaths(DependencyUtils.scala:144)
        at org.apache.spark.deploy.SparkSubmit$$anonfun$doPrepareSubmitEnvironment$3.apply(SparkSubmit.scala:403)
        at org.apache.spark.deploy.SparkSubmit$$anonfun$doPrepareSubmitEnvironment$3.apply(SparkSubmit.scala:403)
        at scala.Option.map(Option.scala:146)
        at org.apache.spark.deploy.SparkSubmit$.doPrepareSubmitEnvironment(SparkSubmit.scala:403)
        at org.apache.spark.deploy.SparkSubmit$.prepareSubmitEnvironment(SparkSubmit.scala:250)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:171)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala).

**Comment by 939481896** [comment]
Sorry,this is the error info :
![image](https://user-images.githubusercontent.com/35762769/63903071-bda4fb80-ca3e-11e9-9da7-b65566815fc9.png)

**Comment by 939481896** [comment]
OK，I have dealed with this question.Some config is wrong!I set JAVA_HONE ='C:\Program Files\Java\jdk1.8.0_201' but not 'C:\Program Files\Java\jre1.8.0_201'.
And I don't use 'spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --jars "c:/program files/Java/mssql-jdbc-7.0.0.jre8.jar"  --master local microsoft-spark-2.4.x-0.4.0.jar BLAH BLAH' to deal it!
