### ISSUE TITLE
When .NET core 3 is used to try the samples, path to binaries indicated may not work as expected. Will be good to call out this specifically.

### ISSUE THREAD

**Issue by rajasekarshanmugam** [dotnet/spark#261]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/run
Operating System: windows

OS: Win10
.NET Core: 3.0

Walk-through of the usage is really good. However for a beginner, its possible when using .NET core 3, output paths are different and copy/paste of commands will fail with obscure errors. Is it possible to call-out that the output paths could vary depending on the .NET core version, so folks copying it directly to command line will not run into issues. If incorrect path is used exception is -

9/09/25 08:42:43 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
19/09/25 08:42:43 WARN DependencyUtils: Local jar d:\temp\mySparkApp\mySparkApp\bin\Debug\netcoreapp2.2\microsoft-spark-2.4.x-0.4.0.jar does not exist, skipping.
19/09/25 08:42:43 WARN SparkSubmit$$anon$2: Failed to load org.apache.spark.deploy.dotnet.DotnetRunner.
java.lang.ClassNotFoundException: org.apache.spark.deploy.dotnet.DotnetRunner
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.apache.spark.util.Utils$.classForName(Utils.scala:238)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:810)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
19/09/25 08:42:43 INFO ShutdownHookManager: Shutdown hook called

**Comment by imback82** [comment]
@bamurtaugh / @rowanmiller can you help updating the doc? The download link [here](https://dotnet.microsoft.com/learn/data/spark-tutorial/install-dotnet) now points to 3.0, so [this](https://dotnet.microsoft.com/learn/data/spark-tutorial/run) needs to be updated.

**Comment by rowanmiller** [comment]
Sure thing, is it just a matter of updating this to `netcoreapp3.0`?

![image](https://user-images.githubusercontent.com/4741851/65619651-5d3da700-df75-11e9-866d-54fd69128b93.png)

**Comment by bamurtaugh** [comment]
@rowanmiller Yes I think that's all that would need to be updated!

**Comment by imback82** [comment]
This is fixed by https://github.com/dotnet/dotnet-core-website/pull/1545
