### ISSUE TITLE
Unsupported major.minor

### ISSUE THREAD

**Issue by liangb4009** [dotnet/spark#300]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/install-spark
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by liangb4009** [comment]
![Uploading 01-issue_for_installed.jpg…]()

**Comment by liangb4009** [comment]
the error message as below:
C:\Users\CN093128>%SPARK_HOME%\bin\spark-submit --version
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/sp
ark/launcher/Main : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:14
1)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Could not find the main class: org.apache.spark.launcher.Main.  Program will exi
t.

**Comment by suhsteve** [comment]
There may be something wrong with your java and spark setup.  What version of java and spark have you installed ?

**Comment by liangb4009** [comment]
@suhsteve thank you for your reply, i have solved it.
This is my steps record as below:
1 download jdk 1.8.0_231 and install it to "C:\Program Files\java\jde1.8.0_231"
2 set the Env Var "JAVA_HOME", as "C:\Program Files\java\jde1.8.0_231"
3 set the Env Var "Path", add "%JAVA_HOME\bin%;%JAVA_HOME\jre\bin%"
4 set the Env Var "%JAVA_HOME\lib;%JAVA_HOME\lib\tool.jar%"
5 close all cmd window
6 open cmd window and type "%SPARK_HOME%\bin\spark-submit --version"
