### ISSUE TITLE
SparkSession config

### ISSUE THREAD

**Issue by bouyeijiang** [dotnet/spark#330]
SparkSession spSession = SparkSession.Builder().AppName("words").GetOrCreate();
the default port is 5567.
how to change connect port?

**Comment by imback82** [comment]
You must be running this in a debug mode. If so, please follow https://github.com/dotnet/spark/blob/master/docs/developer-guide.md#debugging-spark-net-application.

Otherwise, please launch your application thru `spark-submit` as described here:  https://github.com/dotnet/spark/blob/master/docs/getting-started/windows-instructions.md#running-your-net-for-apache-spark-app

**Comment by bouyeijiang** [comment]
E:\Projects\Demo\SparkWorkerGather\bin\Debug\netcoreapp3.0>spark-submit \
Exception in thread "main" org.apache.spark.SparkException: Cannot load main class from JAR file:/E:/
        at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:657)
        at org.apache.spark.deploy.SparkSubmitArguments.loadEnvironmentArguments(SparkSubmitArguments.scala:221)
        at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:116)
        at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$1.<init>(SparkSubmit.scala:907)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:907)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:81)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by elvaliuliuliu** [comment]
@bouyeijiang, thanks for your question. Could you provide your full command for us to better troubleshoot? Thanks.

**Comment by bouyeijiang** [comment]
this problen has been solved.but have new a question,chinese encoding error

**Comment by elvaliuliuliu** [comment]
Good to hear that the problem has been solved. Could you provide more details about Chinese encoding error here at #335? Thanks.

**Comment by bouyeijiang** [comment]
the more detail has been at #335
