### ISSUE TITLE
I am not able to debug spark application using dot net 

### ISSUE THREAD

**Issue by PraveshDev** [dotnet/spark#340]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/run
Operating System: windows

On running of below command in cmd to enable debugging using visual studio 2019
**spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local C:\Users\pkumar\.nuget\packages\microsoft.spark\0.6.0\jars\microsoft-spark-2.3.x-0.6.0.jar \ debug**

I am getting the following error.

Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Exception in thread "main" java.lang.IllegalArgumentException: Unsupported spark version used: 2.4.1. Normalized spark version used: 2.4.1. Supported versions: 2.3.3, 2.3.4, 2.3.0, 2.3.1, 2.3.2
        at org.apache.spark.deploy.dotnet.DotnetRunner$.validateSparkVersions(DotnetRunner.scala:167)
        at org.apache.spark.deploy.dotnet.DotnetRunner$.main(DotnetRunner.scala:46)
        at org.apache.spark.deploy.dotnet.DotnetRunner.main(DotnetRunner.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
log4j:WARN No appenders could be found for logger (org.apache.spark.util.ShutdownHookManager).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

**Comment by elvaliuliuliu** [comment]
Thanks for your question. Can you try `microsoft-spark-2.4.x-0.6.0.jar `?

**Comment by imback82** [comment]
@PraveshDev please reopen the issue if @elvaliuliuliu's suggestion didn't work (it should work).
