### ISSUE TITLE
[BUG]: Unable to debug UDF on Apply

### ISSUE THREAD

**Issue by anduran** [dotnet/spark#373]
**Describe the bug**
When following Debugging instructions (making the Worker hit a breakpoint using an env var) my UDF never breaks. Is debugging UDFs in the context of an Apply supported?

**To Reproduce**

Call UDF:
```c#
            var a = spark.Sql("SELECT * FROM Messages")
                .WithColumn("mock", Functions.Lit("1"))
                .GroupBy("mock") // Force everything to go to a single node
                .Apply(ev.Schema(), UdfHelpers.PersistToFile)
                .WriteStream().Format("console").Start();
```
UDF Definition:
```c#
        static class UdfHelpers
        {
           // Write rows content to a file for debugging since Breakpoint is not hit
            public static RecordBatch PersistToFile(RecordBatch rows)
            {
                Debugger.Break();
                File.WriteAllText($@".\out\{Guid.NewGuid()}.txt", JsonConvert.SerializeObject(rows));
                return rows;
            }
        }
```

**Comment by imback82** [comment]
Does the debugger break in `TaskRunner.cs` as explained here? https://github.com/dotnet/spark/blob/master/docs/developer-guide.md#debugging-user-defined-function-udf

**Comment by anduran** [comment]
Yes, after pressing F5 it simply completes.

**Comment by imback82** [comment]
When it breaks in `TaskRunner.cs`, can you open the file that contains `UdfHelpers` in the same VS instance, create a breakpoint, then F5? Did you try this as well?

**Comment by anduran** [comment]
Yeah, that's exactly why I did. I believe the UDF is not even being called (because the side effect of writing to a file is not executed either). However... I can see the output on the Console.

**Comment by anduran** [comment]
Ok, found the right logs to debug the issue. Turned out it wasn't finding the .dll

I have updated my UDF to this to create a mock UDF:

```c#
            public static RecordBatch PersistToFile(RecordBatch rows)
            {
                    return new RecordBatch(rows.Schema, new IArrowArray[0], 0);
            }
```
or:
```c#
            public static RecordBatch PersistToFile(RecordBatch rows)
            {
                    return rows
            }
```

and I'm getting:

```
[2019-12-12T22:16:17.2627148Z] [ANDURAN-DEV2] [Info] [ConfigurationService] 'DOTNETBACKEND_PORT' environment variable is not set.
[2019-12-12T22:16:17.2938662Z] [ANDURAN-DEV2] [Info] [ConfigurationService] Using port 5567 for connection.
[2019-12-12T22:16:17.3139002Z] [ANDURAN-DEV2] [Info] [JvmBridge] JvMBridge port is 5567
[2019-12-12T22:16:18.8937032Z] [ANDURAN-DEV2] [Debug] [ConfigurationService] Using the environment variable to construct .NET worker path: C:\bin\Microsoft.Spark.Worker-0.6.0\Microsoft.Spark.Worker.exe.
[2019-12-12T22:17:33.8200827Z] [ANDURAN-DEV2] [Error] [JvmBridge] JVM method execution failed: Nonstatic method awaitTermination failed for class 98 when called with no arguments
[2019-12-12T22:17:33.8202791Z] [ANDURAN-DEV2] [Error] [JvmBridge] org.apache.spark.sql.streaming.StreamingQueryException: Writing job aborted.
=== Streaming Query ===
Identifier: [id = 421ce68a-2e45-43ef-a381-a17bcae65925, runId = b26ea48c-1ecb-4c69-b95d-b145f72fa78d]
Current Committed Offsets: {}
Current Available Offsets: {org.apache.spark.sql.eventhubs.EventHubsSource@4f7b7b16: {"test":{"1":1512,"0":2188}}}

Current State: ACTIVE
Thread State: RUNNABLE

Logical Plan:
FlatMapGroupsInPandas [mock#148], Apache.Arrow.RecordBatch PersistToFile(Apache.Arrow.RecordBatch)(Tenant#135, Message#129, enqueuedTime#108-T60000ms, mock#148), [Tenant#158, Message#159, enqueuedTime#160-T60000ms]
+- Project [mock#148, Tenant#135, Message#129, enqueuedTime#108-T60000ms, mock#148]
   +- Project [Tenant#135, Message#129, enqueuedTime#108-T60000ms, 1 AS mock#148]
      +- Project [Tenant#135, Message#129, enqueuedTime#108-T60000ms]
         +- SubqueryAlias `messages`
            +- EventTimeWatermark enqueuedTime#108: timestamp, interval 1 minutes
               +- Project [Tenant#135, Message#129, enqueuedTime#108]
                  +- Project [Raw#122, enqueuedTime#108, parsed#125, Message#129, parsed#125.Tenant AS Tenant#135]
                     +- Project [Raw#122, enqueuedTime#108, parsed#125, parsed#125.Message AS Message#129]
                        +- Project [Raw#122, enqueuedTime#108, jsontostructs(StructField(Message,StringType,true), StructField(Tenant,StringType,true), Raw#122, Some(America/Los_Angeles)) AS parsed#125]
                           +- Project [cast(body#104 as string) AS Raw#122, enqueuedTime#108]
                              +- StreamingExecutionRelation org.apache.spark.sql.eventhubs.EventHubsSource@4f7b7b16, [body#104, partition#105, offset#106, sequenceNumber#107L, enqueuedTime#108, publisher#109, partitionKey#110, properties#111, systemProperties#112]

        at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:297)
        at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:193)
Caused by: org.apache.spark.SparkException: Writing job aborted.
        at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec.doExecute(WriteToDataSourceV2Exec.scala:92)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
        at org.apache.spark.sql.execution.SparkPlan.getByteArrayRdd(SparkPlan.scala:247)
        at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:296)
        at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collectFromPlan(Dataset.scala:3383)
        at org.apache.spark.sql.Dataset$$anonfun$collect$1.apply(Dataset.scala:2782)
        at org.apache.spark.sql.Dataset$$anonfun$collect$1.apply(Dataset.scala:2782)
        at org.apache.spark.sql.Dataset$$anonfun$53.apply(Dataset.scala:3364)
        at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:78)
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
        at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3363)
        at org.apache.spark.sql.Dataset.collect(Dataset.scala:2782)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$5$$anonfun$apply$17.apply(MicroBatchExecution.scala:540)
        at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:78)
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$5.apply(MicroBatchExecution.scala:535)
        at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351)
        at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution.org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch(MicroBatchExecution.scala:534)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply$mcV$sp(MicroBatchExecution.scala:198)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:166)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:166)
        at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351)
        at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1.apply$mcZ$sp(MicroBatchExecution.scala:166)
        at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:56)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:160)
        at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:281)
        ... 1 more
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 3.0 failed 1 times, most recent failure: Lost task 0.0 in stage 3.0 (TID 6, localhost, executor driver): java.lang.UnsupportedOperationException
        at org.apache.spark.sql.vectorized.ArrowColumnVector.<init>(ArrowColumnVector.java:173)
        at org.apache.spark.sql.execution.python.ArrowPythonRunner$$anon$1$$anonfun$read$1.apply(ArrowPythonRunner.scala:165)
        at org.apache.spark.sql.execution.python.ArrowPythonRunner$$anon$1$$anonfun$read$1.apply(ArrowPythonRunner.scala:164)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at org.apache.spark.sql.execution.python.ArrowPythonRunner$$anon$1.read(ArrowPythonRunner.scala:164)
        at org.apache.spark.sql.execution.python.ArrowPythonRunner$$anon$1.read(ArrowPythonRunner.scala:122)
        at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:406)
        at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
        at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$$anonfun$run$3.apply(WriteToDataSourceV2Exec.scala:117)
        at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$$anonfun$run$3.apply(WriteToDataSourceV2Exec.scala:116)
        at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1394)
        at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:146)
        at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec$$anonfun$doExecute$2.apply(WriteToDataSourceV2Exec.scala:67)
        at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec$$anonfun$doExecute$2.apply(WriteToDataSourceV2Exec.scala:66)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:121)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:403)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:409)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

Driver stacktrace:
        at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1889)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1877)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1876)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1876)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:926)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:926)
        at scala.Option.foreach(Option.scala:257)
        at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:926)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2110)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2059)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2048)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
        at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:737)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2061)
        at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec.doExecute(WriteToDataSourceV2Exec.scala:64)
        ... 35 more
Caused by: java.lang.UnsupportedOperationException
        at org.apache.spark.sql.vectorized.ArrowColumnVector.<init>(ArrowColumnVector.java:173)
        at org.apache.spark.sql.execution.python.ArrowPythonRunner$$anon$1$$anonfun$read$1.apply(ArrowPythonRunner.scala:165)
        at org.apache.spark.sql.execution.python.ArrowPythonRunner$$anon$1$$anonfun$read$1.apply(ArrowPythonRunner.scala:164)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at org.apache.spark.sql.execution.python.ArrowPythonRunner$$anon$1.read(ArrowPythonRunner.scala:164)
        at org.apache.spark.sql.execution.python.ArrowPythonRunner$$anon$1.read(ArrowPythonRunner.scala:122)
        at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:406)
        at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
        at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$$anonfun$run$3.apply(WriteToDataSourceV2Exec.scala:117)
        at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$$anonfun$run$3.apply(WriteToDataSourceV2Exec.scala:116)
        at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1394)
        at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:146)
        at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec$$anonfun$doExecute$2.apply(WriteToDataSourceV2Exec.scala:67)
        at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec$$anonfun$doExecute$2.apply(WriteToDataSourceV2Exec.scala:66)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:121)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:403)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:409)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

[2019-12-12T22:17:33.9963977Z] [ANDURAN-DEV2] [Exception] [JvmBridge] JVM method execution failed: Nonstatic method awaitTermination failed for class 98 when called with no arguments
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)
```

**Comment by anduran** [comment]
Seems like I was hitting this issue because I'm using a date column...  #359 

Aside from supporting new ApacheArrow I would recommend adding some clarification unto this error message.
