### ISSUE TITLE
 Unable to load native-hadoop library for your platform.

### ISSUE THREAD

**Issue by arulsmith** [dotnet/spark#383]
The build  has successful  as 👍 

C:\Users\Nivethan\mySparkApp>dotnet build
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 55.01 ms for C:\Users\Nivethan\mySparkApp\mySparkApp.csproj.
  mySparkApp -> C:\Users\Nivethan\mySparkApp\bin\Debug\netcoreapp2.2\mySparkApp.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.17

-----
 And finally, try to execute on apache spark will throw an error.

C:\Users\Nivethan\mySparkApp>%SPARK_HOME%\bin\spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local bin\Debug\netcoreapp3.0\microsoft-spark-2.4.x-0.6.0.jar dotnet bin\Debug\netcoreapp3.0\mySparkApp.dll
20/01/02 12:25:09 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
20/01/02 12:25:09 WARN DependencyUtils: Local jar C:\Users\Nivethan\mySparkApp\bin\Debug\netcoreapp3.0\microsoft-spark-2.4.x-0.6.0.jar does not exist, skipping.
20/01/02 12:25:09 WARN SparkSubmit$$anon$2: Failed to load org.apache.spark.deploy.dotnet.DotnetRunner.
java.lang.ClassNotFoundException: org.apache.spark.deploy.dotnet.DotnetRunner
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.apache.spark.util.Utils$.classForName(Utils.scala:238)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:810)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
20/01/02 12:25:09 INFO ShutdownHookManager: Shutdown hook called
20/01/02 12:25:09 INFO ShutdownHookManager: Deleting directory C:\Users\Nivethan\AppData\Local\Temp\spark-92f4cb54-b23a-42c3-9e4b-96fe956df3e7

C:\Users\Nivethan\mySparkApp>%SPARK_HOME%\bin\spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local bin\Debug\netcoreapp3.0\microsoft-spark-2.4.x-0.6.0.jar dotnet bin\Debug\netcoreapp3.0\mySparkApp.dll
20/01/02 12:33:28 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
20/01/02 12:33:29 WARN DependencyUtils: Local jar C:\Users\Nivethan\mySparkApp\bin\Debug\netcoreapp3.0\microsoft-spark-2.4.x-0.6.0.jar does not exist, skipping.
20/01/02 12:33:29 WARN SparkSubmit$$anon$2: Failed to load org.apache.spark.deploy.dotnet.DotnetRunner.
java.lang.ClassNotFoundException: org.apache.spark.deploy.dotnet.DotnetRunner
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.apache.spark.util.Utils$.classForName(Utils.scala:238)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:810)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
20/01/02 12:33:29 INFO ShutdownHookManager: Shutdown hook called
20/01/02 12:33:29 INFO ShutdownHookManager: Deleting directory C:\Users\Nivethan\AppData\Local\Temp\spark-adef883b-ecee-434b-b19a-76c1fbf189cc

C:\Users\Nivethan\mySparkApp> ------------------
and my java verion details 👍 java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

kindly help me to resolve this issue.

**Comment by GoEddie** [comment]
Spark can’t find your jar that contains DotnetRunner:

“ Local jar C:\Users\Nivethan\mySparkApp\bin\Debug\netcoreapp3.0\microsoft-spark-2.4.x-0.6.0.jar does not exist, skipping.”

Make sure the jar is there or you pass in the correct path.

**Comment by imback82** [comment]
@arulsmith You can try the full path of the jar file as well.

**Comment by imback82** [comment]
@arulsmith did the suggested solution work?

**Comment by imback82** [comment]
Closing this. Please reopen if the suggested solution didn't work.
