### ISSUE TITLE
 [BUG]: Error while running a .net application containing a UDF against remote databricks apache spark (e.g. Azure Databricks)

### ISSUE THREAD

**Issue by zwitbaum** [dotnet/spark#384]
**Describe the bug**

**To Reproduce**

Prerequisites: simple .net application with a simple SQL query and a UDF, which runs properly against a local apache spark.
1. Setup connection to a remote databricks apache spark (I have tested against an Azure Databricks) on your local dev machine using "databricks-connect configure". Test the connection using the "databricks-connect test"
2. Test the .net application without UDF: comment out UDF related line codes and make sure the simple query runs against configured remote Azure Databricks.
3. Uncomment UDF related line codes.
4. See error.

**Expected behavior**
A .net application containing a UDF works properly using connection to a remote databricks.

**Additional context**
Similar program in Python (same SQL query and similar UDF) works using the same configured remote connection properly.

**Comment by imback82** [comment]
@zwitbaum did you follow this https://github.com/dotnet/spark/blob/master/deployment/README.md#databricks?

cc: @suhsteve @Niharikadutta @elvaliuliuliu

**Comment by zwitbaum** [comment]
@imback82 : the .net application works properly, if it is deployed on the azure databricks. But what I mean is something else.

The issue occurred only if the .net app is started **on the local windows machine** (my dev pc) and should query the data from the remote azure databricks. So what I mean
- .net app without UDF <-> remote azure databricks: works
- .net app with UDF <-> remote azure databricks: does not work

What do you mean exactly should be additionally done? Microsoft.Spark.Worker should be additionally deployed on the azure databricks cluster where the data is queried from?

**Comment by imback82** [comment]
I see. Can you check if you see any log messages like the following? `Using the environment variable to construct .NET worker path`

**Comment by elvaliuliuliu** [comment]
Moreover, I saw the error message is `Exception: Python in worker has different version 3.7 than that in driver 0.4.0, PySpark cannot run with different minor versions.Please check environment variables PYSPARK_PYTHON and PYSPARK_DRIVER_PYTHON are correctly set.`

Can you check and verify the version?

**Comment by zwitbaum** [comment]
@elvaliuliuliu: I have investigated the correct values for and set the PYSPARK_PYTHON and PYSPARK_DRIVER_PYTHON as follow, but it does not solve the problem:
- PYSPARK_PYTHON=python3
- PYSPARK_DRIVER_PYTHON=python3

@imback82: what you mean by "remote path where worker binaries are installed"? An URL to the cluster or to the worker file in the cluster? Or the file path to the worker file in the cluster? Can you please provide an example?

**Comment by imback82** [comment]
I meant the path on the cluster. So if the worker binaries are installed under `/usr/bin`, you would set `DOTNET_WORKER_DIR` to `/usr/bin` on the driver side. Looking at your error log, `/databricks/spark/python/pyspark/worker.py` is being launched instead of the .NET worker. Also, how do you plan to ship your DLLs that contain your UDFs? I don't believe we tested your scenario, but you are always welcomed to contribute back your findings!

**Comment by zwitbaum** [comment]
If I change the DOTNET_WORKER_DIR on my local windows machine, the app writes in cmd, e.g.:
"Using the environment variable to construct .NET worker path: /usr/bin/Microsoft.Spark.Worker\Microsoft.Spark.Worker.exe", what IMO makes no sense.
If you mean the environment variable should be set on the cluster by the the db-init.sh or install-worker.sh instead, **please describe how to extend one of these scripts**. Currently, we use a default version of the scripts described on https://docs.microsoft.com/en-ie/dotnet/spark/tutorials/databricks-deployment.

I will try to describe the whole desired development and deployment process later, so you can better understand how we want and need to use the .net for apache spark in our software development process, in order to develop our application locally in the VS by using the remote azure databricks.

**Comment by imback82** [comment]
After setting the env variable, does `/databricks/spark/python/pyspark/worker.py` still get launched? The worker path gets inserted into UDF on the driver side if the env is set, otherwise, it will look for the binary under `PATH`. See this function https://github.com/dotnet/spark/blob/5e9c08b430b4bc56b5f42252c4b73437377afaed/src/csharp/Microsoft.Spark/Services/ConfigurationService.cs#L58

If `worker.py` is still getting launched, there could be a missing link. @zwitbaum can you share the exact repro steps so we can try on our side?

@elvaliuliuliu / @Niharikadutta does any one of you want to take this up?

**Comment by elvaliuliuliu** [comment]
@imback82  I will follow up on this.

**Comment by zwitbaum** [comment]
@imback82 If I set the DOTNET_WORKER_DIR to the azure worker path on **my local dev pc**, e.g. "setx DOTNET_WORKER_DIR /usr/bin" (or /usr/local/bin, or /usr/bin/Microsoft.Spark.Worker) the `/databricks/spark/python/pyspark/worker.py` still get launched.
Must the DOTNET_WORKER_DIR be set **on the azure databricks cluster instead**? If yes, please advice how to do it in the init-script provided mentioned above.

**Comment by elvaliuliuliu** [comment]
Can you try set up DOTNET_WORKER_DIR to the local path of Microsoft.Spark.Worker? Please make sure path is set correctly and Microsoft.Spark.Worker.exe is in the path.

**Comment by imback82** [comment]
@zwitbaum before moving furhther, can you please provide the exact command to submit your spark application to azure databricks?

**Comment by zwitbaum** [comment]
@elvaliuliuliu : the DOTNET_WORKER_DIR was already set to the local path of Microsoft.Spark.Worker before I have posted the bug (setx DOTNET_WORKER_DIR "C:\bin\Microsoft.Spark.Worker-0.7.0"). Unfortunately, it does not help to solve the problem.

**Comment by zwitbaum** [comment]
Once again to describe our requirements for a .net spark software development:
![grafik](https://user-images.githubusercontent.com/6919145/72175008-52e7d180-33db-11ea-959f-98b9853fcaa3.png)
We want to develop our .net spark application on a local dev PC with Visual Studio and use all IDE benefits like debugger, source control, static code checker, refactoring, etc. It means, we must "hit F5" and run the app from the visual studio. Because typically we don't have the necessary spark "big data" on the local machine, we need to connect to the remote spark and use it from (as well as to test queries). As soon as the development iteration done the app is deployed to the cluster and will run there.
As I already mentioned most of our dev scenarios can already be done by now except if we need to use an UDF. In this case is a huge blocker for us, because we can only test our code after deploying to the cluster. We have tested both alternatives: place an UDF in the executing assembly or move it to a separate (referenced) assembly. Both are failed by now.

**Comment by imback82** [comment]
Can't you do the following?
1. Develop/debug your application locally. We have docs how to debug your application: https://github.com/dotnet/spark/blob/master/docs/developer-guide.md
2. Once you are ready to deploy your app, follow this https://github.com/dotnet/spark/blob/master/deployment/README.md#databricks.

Again, can you share the exact command you are using to submit so we can get a better idea how you are doing this? If you want to submit a job from outside databricks, you should follow this: https://docs.databricks.com/dev-tools/api/latest/jobs.html

cc: @suhsteve

**Comment by zwitbaum** [comment]
@imback82 : we develop and debug our application on the windows local machine exactly as described in the link you've provided:
`%SPARK_HOME%\bin\spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local microsoft-spark-2.4.x-0.7.0.jar debug`

Because we want to query the data from the azure databricks we do following:
1. Let's imagine a following query:
```
var spark = SparkSession.Builder().AppName(nameof(ActiveDevices)).GetOrCreate();
var dataFrame = spark.Table("bigdata.table1").Select("testData");
dataFrame.Show();
```
Because the data is stored **not on the local machine, but in azure databricks instead**, we need to configure a connection to this databricks.

2. We have configured the connection to the azure databricks using the "databricks-connect configure" and tested it by the "databricks-connect test" like described here: https://docs.microsoft.com/en-us/azure/databricks/dev-tools/databricks-connect
It requires, that the spark home is set properly:
`setx SPARK_HOME "c:\users\zwitbaum\appdata\local\programs\python\python37\lib\site-packages\pyspark"`

3. Now we can run our .net app:
-- open command prompt and start %SPARK_HOME%\bin\spark-submit ... debug like described above
-- in visual studio set a breakpoint e.g. on the first line in the main method and hit the F5.
-- the app runs properly and shows the queried data.

4. Now let's extend the application with a UDF, like
```
spark.Sql("SELECT T1 FROM VALUES ('one'), ('two'), ('three') as (T1)").CreateOrReplaceTempView("Test");
var sqlDf = spark.Sql("SELECT T1 from Test");
sqlDf.Show();

spark.Udf().Register<string, string>("my_udf", UserDefinedFunctions.Udf.ToUpper);
sqlDf = spark.Sql("SELECT *, my_udf(*) FROM Test");
sqlDf.Show();
```
Start the app in the visual studio again by hitting the F5. The app failed with exception, which you can find in the description of the issue.

That are the steps you can do to reproduce the error easily.

What we have additionally tested before to submit the bug:

- Check, whether the same app can run properly **with a local windows spark: yes, it works**
-- Install spark on the local windows machine (like described https://docs.microsoft.com/en-ie/dotnet/spark/tutorials/get-started)
-- switch to the local spark: setx SPARK_HOME C:\bin\spark-2.4.1-bin-hadoop2.7\
-- open command prompt and start %SPARK_HOME%\bin\spark-submit ... debug like described above
-- comment the lines, which are relates to remote azure databricks:
```
//var dataFrame = spark.Table("bigdata.table1").Select("testData");
//dataFrame.Show();
```
Start the app in the visual studio again by hitting the F5.  The app runs properly and shows the queried data. UDF works well converting the values to upper.

- Check, whether a **similar app with a UDF written in python** can run locally using the data from the remote azure databricks:  **yes, it works**
-- switch to the remote databricks connection by `setx SPARK_HOME "c:\users\zwitbaum\appdata\local\programs\python\python37\lib\site-packages\pyspark"` and testing it with "databricks-connect test"
-- run the python script locally: it works properly

I hope this information can be useful for you to investigate the bug.

**Comment by imback82** [comment]
Thanks @zwitbaum! @elvaliuliuliu will investigate this.

**Comment by elvaliuliuliu** [comment]
@zwitbaum We have been investigating on this scenario. I can reproduce the error you mentioned. Looks like there are some architecture differences which cause SparkDotnet worker is not invoked but PySpark worker. We may need more time investigating this but I am on top of this. Thanks for your patience and feel free to let me know if you have any new findings/updates!

Details of my repro, settings are as below:
```bash
set SPARK_HOME=c:\users\ruinliu\appdata\local\continuum\anaconda3\lib\site-packages\pyspark
set DOTNET_WORKER_DIR=/usr/local/bin/spark-dotnet/Microsoft.Spark.Worker-0.8.0/ # Remote SparkDotnet worker path on DBx cluster
```
And I query the data table stored on the cluster and run an UDF on it. I got the same error as you have. The logical plan from the submission are as below which SparkDotnet worker is passed correctly but not invoked.
```
env_vars {
  key: "DOTNET_WORKER_SPARK_VERSION"
  nullableValue: "2.4.3"
}
env_vars {
  key: "DOTNET_ASSEMBLY_SEARCH_PATHS"
  nullableValue: "C:\\Users\\<user name>\\AppData\\Local\\Temp\\spark-57c30aba-9b9e-4529-8bc3-de075ff4c76b\\userFiles-260a2a14-346e-434f-9401-650b5add8d30"
}
python_exec: "/usr/local/bin/spark-dotnet/Microsoft.Spark.Worker-0.8.0/Microsoft.Spark.Worker.exe"
python_ver: "0.4.0"
```

**Comment by elvaliuliuliu** [comment]
@zwitbaum: Just FYI, we have opened a ticket with Azure Databricks, this is currently being investigated. I will update you once I hear back from them.

**Comment by elvaliuliuliu** [comment]
@zwitbaum : We had a discussion with Databricks today and will get back to you once there are any updates from their side.

**Comment by alexoss68** [comment]
Another way around is using the compatible python version in dotNet app so it matches spark cluster

**Comment by elvaliuliuliu** [comment]
Which compatible python version you mean here? For example, error shows the python version "0.4.0" mismatches, this version is from `Microsoft.Spark.Worker.exe`. 
So looks like the logic plan is correct, but when sending it to driver in the cluster through `databricks-connect`, the `Microsoft.Spark.Worker.exe` is overrided by `worker.py`.

**Comment by alexoss68** [comment]
Are you sure that spark cluster runs Microsoft.Spark.Worker.exe? Why Microsoft.Spark.Worker.exe uses python version "0.4.0" which is quite old.

**Comment by mllab-nl** [comment]
Having a UDF breaks consistently on local and on Azure HDInsights/Spark 2.4 setup whne using "Microsoft.Spark.Worker-0.10.0" with: 
FileNotFoundException


[2020-04-24T08:56:24.0906298Z] [DESKTOP-XXXXX] [Error] [TaskRunner] [0] ProcessStream() failed with exception: System.IO.FileNotFoundException: Assembly 'mySparkApp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' file not found 'mySparkApp.dll' in 'C:\Users\XXXX\AppData\Local\Temp\spark-5fd960ac-2e4f-4f84-b726-7d7e72aeca23\userFiles-d016a082-5d84-411c-91c5-ec8e859bd516,C:\src\Spark\mySparkApp,C:\bin\Microsoft.Spark.Worker-0.10.0\'
   at Microsoft.Spark.Utils.AssemblyLoader.LoadAssembly(String assemblyName, String assemblyFileName) in /_/src/csharp/Microsoft.Spark/Utils/AssemblyLoader.cs:line 122
   at Microsoft.Spark.Utils.UdfSerDe.<>c.<DeserializeType>b__10_0(TypeData td) in /_/src/csharp/Microsoft.Spark/Utils/UdfSerDe.cs:line 260
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Spark.Utils.UdfSerDe.DeserializeType(TypeData typeData) in /_/src/csharp/Microsoft.Spark/Utils/UdfSerDe.cs:line 258
   at Microsoft.Spark.Utils.UdfSerDe.Deserialize(UdfData udfData) in /_/src/csharp/Microsoft.Spark/Utils/UdfSerDe.cs:line 160
   at Microsoft.Spark.Utils.CommandSerDe.DeserializeUdfs[T](UdfWrapperData data, Int32& nodeIndex, Int32& udfIndex) in /_/src/csharp/Microsoft.Spark/Utils/CommandSerDe.cs:line 267
   at Microsoft.Spark.Utils.CommandSerDe.Deserialize[T](Stream stream, SerializedMode& serializerMode, SerializedMode& deserializerMode, String& runMode) in /_/src/csharp/Microsoft.Spark/Utils/CommandSerDe.cs:line 243
   at Microsoft.Spark.Worker.Processor.CommandProcessor.ReadSqlCommands(PythonEvalType evalType, Stream stream) in D:\a\1\s\src\csharp\Microsoft.Spark.Worker\Processor\CommandProcessor.cs:line 190
   at Microsoft.Spark.Worker.Processor.CommandProcessor.ReadSqlCommands(PythonEvalType evalType, Stream stream, Version version) in D:\a\1\s\src\csharp\Microsoft.Spark.Worker\Processor\CommandProcessor.cs:line 117
   at Microsoft.Spark.Worker.Processor.CommandProcessor.Process(Stream stream) in D:\a\1\s\src\csharp\Microsoft.Spark.Worker\Processor\CommandProcessor.cs:line 62
   at Microsoft.Spark.Worker.Processor.PayloadProcessor.Process(Stream stream) in D:\a\1\s\src\csharp\Microsoft.Spark.Worker\Processor\PayloadProcessor.cs:line 74
   at Microsoft.Spark.Worker.TaskRunner.ProcessStream(Stream inputStream, Stream outputStream, Version version, Boolean& readComplete) in D:\a\1\s\src\csharp\Microsoft.Spark.Worker\TaskRunner.cs:line 143

**Comment by zwitbaum** [comment]
Any progress in the version 2.0?

**Comment by selvavm** [comment]
Hi May I know if this is fixed?

**Comment by zwitbaum** [comment]
My last test indicated that the issue is still not fixed.

**Comment by selvavm** [comment]
I came to update that I was able to make this work with UDF with Databricks. Moreover, I was able to do debugging in Visual studio as well. However, it is not practical because I will have to copy the dlls in Debug folder to Databricks cluster each and every time I make a code change. This impacts productivity :(.
