### ISSUE TITLE
 ERROR DotnetBackendHandler: methods:

### ISSUE THREAD

**Issue by shreyshahh** [dotnet/spark#396]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/run
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**my Program.cs** 

```
using System;
using Microsoft.Spark.Sql;

namespace mysparkapp
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

           var spark = SparkSession
                .Builder()
                .AppName("word_count_sample")
                .GetOrCreate();

            // Create initial DataFrame
            DataFrame dataFrame = spark.Read().Text("input.txt");


            // Count words
            var words = dataFrame
                .Select(Functions.Split(Functions.Col("value"), " ").Alias("words"))
                .Select(Functions.Explode(Functions.Col("words"))
                .Alias("word"))
                .GroupBy("word")
                .Count()
                .OrderBy(Functions.Col("count").Desc());

            // Show results
            words.Show();

            // Stop Spark session
            spark.Stop();
        }
    }
}

```
**I am running this using following command**
spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local bin\Debug\netcoreapp2.1\microsoft-spark-2.4.x-0.6.0.jar dotnet bin\Debug\netcoreapp2.1\mysparkapp.dll

**The error I am getting is**

20/01/23 14:30:41 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Hello World!
[2020-01-23T09:00:42.2073762Z] [SUPP-INF-DEV-20] [Info] [ConfigurationService] Using port 61451 for connection.
[2020-01-23T09:00:42.2086499Z] [SUPP-INF-DEV-20] [Info] [JvmBridge] JvMBridge port is 61451
20/01/23 14:30:43 ERROR DotnetBackendHandler: methods:
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.slf4j.Logger org.apache.spark.sql.DataFrameReader.log()
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.DataFrameReader org.apache.spark.sql.DataFrameReader.format(java.lang.String)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.load(java.lang.String[])
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.load()
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.load(scala.collection.Seq)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.load(java.lang.String)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.table(java.lang.String)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.initializeLogIfNecessary(boolean)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public boolean org.apache.spark.sql.DataFrameReader.initializeLogIfNecessary(boolean,boolean)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.logInfo(scala.Function0,java.lang.Throwable)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.logInfo(scala.Function0)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.logTrace(scala.Function0,java.lang.Throwable)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.logTrace(scala.Function0)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public boolean org.apache.spark.sql.DataFrameReader.isTraceEnabled()
20/01/23 14:30:43 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.logError(scala.Function0,java.lang.Throwable)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.logError(scala.Function0)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public java.lang.String org.apache.spark.sql.DataFrameReader.logName()
20/01/23 14:30:43 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.logDebug(scala.Function0)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.logDebug(scala.Function0,java.lang.Throwable)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.logWarning(scala.Function0)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.logWarning(scala.Function0,java.lang.Throwable)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.slf4j.Logger org.apache.spark.sql.DataFrameReader.org$apache$spark$internal$Logging$$log_()
20/01/23 14:30:43 ERROR DotnetBackendHandler: public boolean org.apache.spark.sql.DataFrameReader.initializeLogIfNecessary$default$2()
20/01/23 14:30:43 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.org$apache$spark$internal$Logging$$log__$eq(org.slf4j.Logger)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.text(java.lang.String[])
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.text(scala.collection.Seq)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.text(java.lang.String)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.DataFrameReader org.apache.spark.sql.DataFrameReader.options(java.util.Map)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.DataFrameReader org.apache.spark.sql.DataFrameReader.options(scala.collection.Map)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.DataFrameReader org.apache.spark.sql.DataFrameReader.option(java.lang.String,java.lang.String)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.DataFrameReader org.apache.spark.sql.DataFrameReader.option(java.lang.String,boolean)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.DataFrameReader org.apache.spark.sql.DataFrameReader.option(java.lang.String,long)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.DataFrameReader org.apache.spark.sql.DataFrameReader.option(java.lang.String,double)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.DataFrameReader org.apache.spark.sql.DataFrameReader.schema(java.lang.String)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.DataFrameReader org.apache.spark.sql.DataFrameReader.schema(org.apache.spark.sql.types.StructType)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.textFile(scala.collection.Seq)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.textFile(java.lang.String)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.textFile(java.lang.String[])
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.jdbc(java.lang.String,java.lang.String,java.lang.String[],java.util.Properties)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.jdbc(java.lang.String,java.lang.String,java.lang.String,long,long,int,java.util.Properties)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.jdbc(java.lang.String,java.lang.String,java.util.Properties)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.csv(scala.collection.Seq)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.csv(java.lang.String)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.csv(org.apache.spark.sql.Dataset)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.csv(java.lang.String[])
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.parquet(scala.collection.Seq)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.parquet(java.lang.String[])
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.parquet(java.lang.String)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.orc(java.lang.String)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.orc(scala.collection.Seq)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.orc(java.lang.String[])
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.json(org.apache.spark.rdd.RDD)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.json(java.lang.String[])
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.json(org.apache.spark.sql.Dataset)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.json(org.apache.spark.api.java.JavaRDD)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.json(scala.collection.Seq)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.json(java.lang.String)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public final void java.lang.Object.wait() throws java.lang.InterruptedException
20/01/23 14:30:43 ERROR DotnetBackendHandler: public final void java.lang.Object.wait(long,int) throws java.lang.InterruptedException
20/01/23 14:30:43 ERROR DotnetBackendHandler: public final native void java.lang.Object.wait(long) throws java.lang.InterruptedException
20/01/23 14:30:43 ERROR DotnetBackendHandler: public boolean java.lang.Object.equals(java.lang.Object)
20/01/23 14:30:43 ERROR DotnetBackendHandler: public java.lang.String java.lang.Object.toString()
20/01/23 14:30:43 ERROR DotnetBackendHandler: public native int java.lang.Object.hashCode()
20/01/23 14:30:43 ERROR DotnetBackendHandler: public final native java.lang.Class java.lang.Object.getClass()
20/01/23 14:30:43 ERROR DotnetBackendHandler: public final native void java.lang.Object.notify()
20/01/23 14:30:43 ERROR DotnetBackendHandler: public final native void java.lang.Object.notifyAll()
20/01/23 14:30:43 ERROR DotnetBackendHandler: args:
20/01/23 14:30:43 ERROR DotnetBackendHandler: argType: java.lang.String[], argValue: [Ljava.lang.String;@7b2e5daa
[2020-01-23T09:00:43.7228932Z] [SUPP-INF-DEV-20] [Error] [JvmBridge] JVM method execution failed: Nonstatic method text failed for class 6 when called with 1 arguments ([Index=1, Type=String[], Value=System.String[]], )
[2020-01-23T09:00:43.7229556Z] [SUPP-INF-DEV-20] [Error] [JvmBridge] org.apache.spark.sql.AnalysisException: Path does not exist: file:/C:/Users/sshah/mysparkapp/input.txt;
        at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary$1.apply(DataSource.scala:558)
        at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary$1.apply(DataSource.scala:545)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
        at scala.collection.immutable.List.flatMap(List.scala:355)
        at org.apache.spark.sql.execution.datasources.DataSource.org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary(DataSource.scala:545)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:359)
        at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
        at org.apache.spark.sql.DataFrameReader.text(DataFrameReader.scala:714)
        at org.apache.spark.sql.DataFrameReader.text(DataFrameReader.scala:714)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.handleMethodCall(DotnetBackendHandler.scala:162)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.handleBackendRequest(DotnetBackendHandler.scala:102)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.channelRead0(DotnetBackendHandler.scala:29)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.channelRead0(DotnetBackendHandler.scala:24)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Unknown Source)

[2020-01-23T09:00:43.7382230Z] [SUPP-INF-DEV-20] [Exception] [JvmBridge] JVM method execution failed: Nonstatic method text failed for class 6 when called with 1 arguments ([Index=1, Type=String[], Value=System.String[]], )
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)

Unhandled Exception: System.Exception: JVM method execution failed: Nonstatic method text failed for class 6 when called with 1 arguments ([Index=1, Type=String[], Value=System.String[]], )
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object arg0)
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallNonStaticJavaMethod(JvmObjectReference objectId, String methodName, Object arg0)
   at Microsoft.Spark.Sql.DataFrameReader.LoadSource(String source, String[] paths)
   at mysparkapp.Program.Main(String[] args) in C:\Users\sshah\mysparkapp\Program.cs:line 18

**Comment by elvaliuliuliu** [comment]
The following error can be found in your stack trace:
```
[2020-01-23T09:00:43.7229556Z] [SUPP-INF-DEV-20] [Error] [JvmBridge] org.apache.spark.sql.AnalysisException: Path does not exist: file:/C:/Users/sshah/mysparkapp/input.txt;
```

Can you please make sure `input.txt` exists in path `C:/Users/sshah/mysparkapp/`?

**Comment by shreyshahh** [comment]
@elvaliuliuliu My bad, I completely missed it. Thanks for the solution.
