### ISSUE TITLE
JVM error at the last step. Nonstatic method text failed for class 6 when called with 1 arguments

### ISSUE THREAD

**Issue by hgrewa** [dotnet/spark#397]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/run
Operating System: windows

The program fails at the last step.

[2020-01-23T20:47:54.2185880Z] [WGC110490J5H2] [Exception] [JvmBridge] JVM method execution failed: Nonstatic method text failed for class 6 when called with 1 arguments ([Index=1, Type=String[], Value=System.String[]], )
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)
Unhandled exception. System.Exception: JVM method execution failed: Nonstatic method text failed for class 6 when called with 1 arguments ([Index=1, Type=String[], Value=System.String[]], )
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object arg0)
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallNonStaticJavaMethod(JvmObjectReference objectId, String methodName, Object arg0)
   at Microsoft.Spark.Interop.Ipc.JvmObjectReference.Invoke(String methodName, Object arg0)
   at Microsoft.Spark.Sql.DataFrameReader.LoadSource(String source, String[] paths)
   at Microsoft.Spark.Sql.DataFrameReader.Text(String[] paths)
   at mySparkApp.Program.Main(String[] args) in C:\temp\mySparkApp\Program.cs:line 17

**Comment by imback82** [comment]
@hgrewa can you paste the whole log please?

**Comment by hgrewa** [comment]
Just fixed it. The input.txt file used for the input analysis was not copied over to the debug folder (or it was placed in a wrong folder). Just used the full path to the data frame and it worked without an issue. 
`// Create initial DataFrame
DataFrame dataFrame = spark.Read().Text("C:/temp/mySparkApp/input.txt");
`
instead of 
`// Create initial DataFrame
DataFrame dataFrame = spark.Read().Text("input.txt");
`
Thanks for the help.
