### ISSUE TITLE
Error while running sample program for Dotnet for spark 

### ISSUE THREAD

**Issue by dkjha811** [dotnet/spark#401]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/run
Operating System: windows

I have gone through this tutotials and intall every package listed down and was able to get the desired results till the last command to get the word count . 
Here is the command which gives the error. I am not able to understand where is the gap . 
%SPARK_HOME%\bin\spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local bin\Debug\netcoreapp3.0\microsoft-spark-2.4.x-0.6.0.jar dotnet bin\Debug\netcoreapp3.0\mySparkApp.dll

C:\Users\mc73892\mySparkApp>%SPARK_HOME%\bin\spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local bin\Debug\netcoreapp3.0\microsoft-spark-2.4.x-0.6.0.jar dotnet bin\Debug\netcoreapp3.0\mySparkApp.dll
20/01/24 13:18:53 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
20/01/24 13:18:53 WARN DependencyUtils: Local jar C:\Users\mc73892\mySparkApp\bin\Debug\netcoreapp3.0\microsoft-spark-2.4.x-0.6.0.jar does not exist, skipping.
20/01/24 13:18:53 WARN SparkSubmit$$anon$2: Failed to load org.apache.spark.deploy.dotnet.DotnetRunner.
java.lang.ClassNotFoundException: org.apache.spark.deploy.dotnet.DotnetRunner
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.apache.spark.util.Utils$.classForName(Utils.scala:238)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:810)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
20/01/24 13:18:53 INFO ShutdownHookManager: Shutdown hook called
20/01/24 13:18:53 INFO ShutdownHookManager: Deleting directory C:\Users\mc73892\AppData\Local\Temp\spark-fd869262-8ec5-47aa-8392-dad3b6b02f04

C:\Users\mc73892\mySparkApp>

**Comment by elvaliuliuliu** [comment]
Can you try run the following command?
```
%SPARK_HOME%\bin\spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local bin\Debug\netcoreapp3.1\microsoft-spark-2.4.x-0.6.0.jar dotnet bin\Debug\netcoreapp3.1\mySparkApp.dll
```

**Comment by imback82** [comment]
> 20/01/24 13:18:53 WARN DependencyUtils: Local jar C:\Users\mc73892\mySparkApp\bin\Debug\netcoreapp3.0\microsoft-spark-2.4.x-0.6.0.jar does not exist,

Can you try @elvaliuliuliu's suggestion?

**Comment by sharadagarwal** [comment]
I was getting a similar error, and @elvaliuliuliu 's suggestion fixed it. Thanks @elvaliuliuliu !

**Comment by dkjha811** [comment]
Yes
Thank you .it's fixed now with the updated command.

**Comment by elvaliuliuliu** [comment]
This [PR](https://github.com/dotnet/website/pull/1709) should address this issue.
