### ISSUE TITLE
Problema al ejecutar el proyecto apache spark con .NET 

### ISSUE THREAD

**Issue by JoseTala23** [dotnet/spark#405]
WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/internal/Logging$class

**Comment by elvaliuliuliu** [comment]
Can you please provide more detailed information? e.g. command line you use, full error log, etc

**Comment by JoseTala23** [comment]
he utilizado esta linea de comando:
spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local c:\mySparkApp\bin\Debug\netcoreapp2.1\microsoft-spark-2.4.x-0.8.0.jar dotnet C:\mySparkApp\bin\Debug\netcoreapp2.1\mySparkApp.dll

y el ERROR:
20/01/28 09:31:00 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/internal/Logging$class
        at org.apache.spark.deploy.dotnet.DotnetRunner$.<init>(DotnetRunner.scala:35)
        at org.apache.spark.deploy.dotnet.DotnetRunner$.<clinit>(DotnetRunner.scala)
        at org.apache.spark.deploy.dotnet.DotnetRunner.main(DotnetRunner.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.internal.Logging$class
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 15 more
log4j:WARN No appenders could be found for logger (org.apache.spark.util.ShutdownHookManager).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

**Comment by elvaliuliuliu** [comment]
Can you confirm the Apache Spark version you are using?

**Comment by JoseTala23** [comment]
spark-3.0.0-preview2-bin-hadoop3.2

**Comment by elvaliuliuliu** [comment]
Spark 3.0 is not supported currently. And it might be supported in the upcoming releases. 

Please check supported Spark version here: https://github.com/dotnet/spark#supported-apache-spark

**Comment by JoseTala23** [comment]
Thank you very much! I have already solved it.
