### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by el-genius** [dotnet/spark#434]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/run
Operating System: windows

 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
20/02/26 17:42:52 INFO DotnetRunner: Starting DotnetBackend with D:/Projects/Test/ProcessStreaming/ProcessStreamPOC/Test/bin/Debug/netcoreapp3.1/Test.exe.
20/02/26 17:42:53 INFO DotnetRunner: Port number used by DotnetBackend is 54228
20/02/26 17:42:53 INFO DotnetRunner: Adding key=spark.jars and value=file:/D:/Projects/Test/ProcessStreaming/ProcessStreamPOC/Test/bin/Debug/netcoreapp3.1/microsoft-spark-2.4.x-0.9.0.jar to environment
20/02/26 17:42:53 INFO DotnetRunner: Adding key=spark.app.name and value=org.apache.spark.deploy.dotnet.DotnetRunner to environment
20/02/26 17:42:53 INFO DotnetRunner: Adding key=spark.submit.deployMode and value=client to environment
20/02/26 17:42:53 INFO DotnetRunner: Adding key=spark.master and value=local to environment
[2020-02-26T14:42:53.3378027Z] [TTC-PC-146] [Info] [ConfigurationService] Using port 54228 for connection.
[2020-02-26T14:42:53.3416217Z] [TTC-PC-146] [Info] [JvmBridge] JvMBridge port is 54228
20/02/26 17:42:53 INFO SparkContext: Running Spark version 2.4.5
20/02/26 17:42:53 INFO SparkContext: Submitted application: word_count_sample
20/02/26 17:42:53 INFO SecurityManager: Changing view acls to: User
20/02/26 17:42:53 INFO SecurityManager: Changing modify acls to: User
20/02/26 17:42:53 INFO SecurityManager: Changing view acls groups to:
20/02/26 17:42:53 INFO SecurityManager: Changing modify acls groups to:
20/02/26 17:42:53 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(User); groups with view permissions: Set(); users  with modify permissions: Set(User); groups with modify permissions: Set()
20/02/26 17:42:53 INFO Utils: Successfully started service 'sparkDriver' on port 54236.
20/02/26 17:42:53 INFO SparkEnv: Registering MapOutputTracker
20/02/26 17:42:53 INFO SparkEnv: Registering BlockManagerMaster
20/02/26 17:42:53 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
20/02/26 17:42:53 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
20/02/26 17:42:53 INFO DiskBlockManager: Created local directory at C:\Users\User\AppData\Local\Temp\blockmgr-37f08c27-909a-41ac-af10-1a034665a1d4
20/02/26 17:42:53 INFO MemoryStore: MemoryStore started with capacity 366.3 MB
20/02/26 17:42:53 INFO SparkEnv: Registering OutputCommitCoordinator
20/02/26 17:42:53 INFO Utils: Successfully started service 'SparkUI' on port 4040.
20/02/26 17:42:53 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://TTC-PC-146:4040
20/02/26 17:42:53 INFO SparkContext: Added JAR file:/D:/Projects/Test/ProcessStreaming/ProcessStreamPOC/Test/bin/Debug/netcoreapp3.1/microsoft-spark-2.4.x-0.9.0.jar at spark://TTC-PC-146:54236/jars/microsoft-spark-2.4.x-0.9.0.jar with timestamp 1582728173977
20/02/26 17:42:54 INFO Executor: Starting executor ID driver on host localhost
20/02/26 17:42:54 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 54251.
20/02/26 17:42:54 INFO NettyBlockTransferService: Server created on TTC-PC-146:54251
20/02/26 17:42:54 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
20/02/26 17:42:54 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, TTC-PC-146, 54251, None)
20/02/26 17:42:54 INFO BlockManagerMasterEndpoint: Registering block manager TTC-PC-146:54251 with 366.3 MB RAM, BlockManagerId(driver, TTC-PC-146, 54251, None)
20/02/26 17:42:54 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, TTC-PC-146, 54251, None)
20/02/26 17:42:54 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, TTC-PC-146, 54251, None)
20/02/26 17:42:54 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir ('file:/D:/Projects/Test/ProcessStreaming/ProcessStreamPOC/spark-warehouse').
20/02/26 17:42:54 INFO SharedState: Warehouse path is 'file:/D:/Projects/Test/ProcessStreaming/ProcessStreamPOC/spark-warehouse'.
20/02/26 17:42:54 INFO StateStoreCoordinatorRef: Registered StateStoreCoordinator endpoint
20/02/26 17:42:54 ERROR DotnetBackendHandler: methods:
20/02/26 17:42:54 ERROR DotnetBackendHandler: public org.slf4j.Logger org.apache.spark.sql.DataFrameReader.log()
20/02/26 17:42:54 ERROR DotnetBackendHandler: public org.apache.spark.sql.DataFrameReader org.apache.spark.sql.DataFrameReader.format(java.lang.String)
20/02/26 17:42:54 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.load(scala.collection.Seq)
20/02/26 17:42:54 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.load(java.lang.String[])
20/02/26 17:42:54 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.load(java.lang.String)
20/02/26 17:42:54 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.load()
20/02/26 17:42:54 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.table(java.lang.String)
20/02/26 17:42:54 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.jdbc(java.lang.String,java.lang.String,java.lang.String,long,long,int,java.util.Properties)
20/02/26 17:42:54 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.jdbc(java.lang.String,java.lang.String,java.lang.String[],java.util.Properties)
20/02/26 17:42:54 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.jdbc(java.lang.String,java.lang.String,java.util.Properties)
20/02/26 17:42:54 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.textFile(java.lang.String)
20/02/26 17:42:54 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.textFile(java.lang.String[])
20/02/26 17:42:54 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.textFile(scala.collection.Seq)
20/02/26 17:42:54 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.csv(java.lang.String[])
20/02/26 17:42:54 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.csv(org.apache.spark.sql.Dataset)
20/02/26 17:42:54 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.csv(java.lang.String)
20/02/26 17:42:54 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.csv(scala.collection.Seq)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.parquet(java.lang.String)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.parquet(java.lang.String[])
20/02/26 17:42:55 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.parquet(scala.collection.Seq)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.orc(scala.collection.Seq)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.orc(java.lang.String[])
20/02/26 17:42:55 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.orc(java.lang.String)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.json(org.apache.spark.sql.Dataset)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.json(org.apache.spark.rdd.RDD)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.json(org.apache.spark.api.java.JavaRDD)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.json(java.lang.String)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.json(java.lang.String[])
20/02/26 17:42:55 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.json(scala.collection.Seq)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public org.slf4j.Logger org.apache.spark.sql.DataFrameReader.org$apache$spark$internal$Logging$$log_()
20/02/26 17:42:55 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.org$apache$spark$internal$Logging$$log__$eq(org.slf4j.Logger)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public boolean org.apache.spark.sql.DataFrameReader.initializeLogIfNecessary$default$2()
20/02/26 17:42:55 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.initializeLogIfNecessary(boolean)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public boolean org.apache.spark.sql.DataFrameReader.initializeLogIfNecessary(boolean,boolean)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public boolean org.apache.spark.sql.DataFrameReader.isTraceEnabled()
20/02/26 17:42:55 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.logTrace(scala.Function0,java.lang.Throwable)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.logTrace(scala.Function0)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.logDebug(scala.Function0,java.lang.Throwable)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.logDebug(scala.Function0)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public java.lang.String org.apache.spark.sql.DataFrameReader.logName()
20/02/26 17:42:55 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.logInfo(scala.Function0,java.lang.Throwable)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.logInfo(scala.Function0)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.logWarning(scala.Function0,java.lang.Throwable)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.logWarning(scala.Function0)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.logError(scala.Function0)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.logError(scala.Function0,java.lang.Throwable)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public org.apache.spark.sql.DataFrameReader org.apache.spark.sql.DataFrameReader.options(java.util.Map)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public org.apache.spark.sql.DataFrameReader org.apache.spark.sql.DataFrameReader.options(scala.collection.Map)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public org.apache.spark.sql.DataFrameReader org.apache.spark.sql.DataFrameReader.schema(java.lang.String)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public org.apache.spark.sql.DataFrameReader org.apache.spark.sql.DataFrameReader.schema(org.apache.spark.sql.types.StructType)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public org.apache.spark.sql.DataFrameReader org.apache.spark.sql.DataFrameReader.option(java.lang.String,double)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public org.apache.spark.sql.DataFrameReader org.apache.spark.sql.DataFrameReader.option(java.lang.String,boolean)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public org.apache.spark.sql.DataFrameReader org.apache.spark.sql.DataFrameReader.option(java.lang.String,long)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public org.apache.spark.sql.DataFrameReader org.apache.spark.sql.DataFrameReader.option(java.lang.String,java.lang.String)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.text(java.lang.String)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.text(scala.collection.Seq)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.text(java.lang.String[])
20/02/26 17:42:55 ERROR DotnetBackendHandler: public final void java.lang.Object.wait() throws java.lang.InterruptedException
20/02/26 17:42:55 ERROR DotnetBackendHandler: public final void java.lang.Object.wait(long,int) throws java.lang.InterruptedException
20/02/26 17:42:55 ERROR DotnetBackendHandler: public final native void java.lang.Object.wait(long) throws java.lang.InterruptedException
20/02/26 17:42:55 ERROR DotnetBackendHandler: public boolean java.lang.Object.equals(java.lang.Object)
20/02/26 17:42:55 ERROR DotnetBackendHandler: public java.lang.String java.lang.Object.toString()
20/02/26 17:42:55 ERROR DotnetBackendHandler: public native int java.lang.Object.hashCode()
20/02/26 17:42:55 ERROR DotnetBackendHandler: public final native java.lang.Class java.lang.Object.getClass()
20/02/26 17:42:55 ERROR DotnetBackendHandler: public final native void java.lang.Object.notify()
20/02/26 17:42:55 ERROR DotnetBackendHandler: public final native void java.lang.Object.notifyAll()
20/02/26 17:42:55 ERROR DotnetBackendHandler: args:
20/02/26 17:42:55 ERROR DotnetBackendHandler: argType: scala.collection.mutable.WrappedArray.ofRef, argValue: WrappedArray(input.txt)
[2020-02-26T14:42:55.0528670Z] [TTC-PC-146] [Error] [JvmBridge] JVM method execution failed: Nonstatic method text failed for class 7 when called with 1 arguments ([Index=1, Type=String[], Value=System.String[]], )
[2020-02-26T14:42:55.0530386Z] [TTC-PC-146] [Error] [JvmBridge] org.apache.spark.sql.AnalysisException: Path does not exist: file:/D:/Projects/Test/ProcessStreaming/ProcessStreamPOC/input.txt;
        at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary$1.apply(DataSource.scala:558)
        at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary$1.apply(DataSource.scala:545)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
        at scala.collection.immutable.List.flatMap(List.scala:355)
        at org.apache.spark.sql.execution.datasources.DataSource.org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary(DataSource.scala:545)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:359)
        at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
        at org.apache.spark.sql.DataFrameReader.text(DataFrameReader.scala:715)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.handleMethodCall(DotnetBackendHandler.scala:162)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.handleBackendRequest(DotnetBackendHandler.scala:102)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.channelRead0(DotnetBackendHandler.scala:29)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.channelRead0(DotnetBackendHandler.scala:24)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

[2020-02-26T14:42:55.0859038Z] [TTC-PC-146] [Exception] [JvmBridge] JVM method execution failed: Nonstatic method text failed for class 7 when called with 1 arguments ([Index=1, Type=String[], Value=System.String[]], )
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)
Unhandled exception. System.Exception: JVM method execution failed: Nonstatic method text failed for class 7 when called with 1 arguments ([Index=1, Type=String[], Value=System.String[]], )
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object arg0)
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallNonStaticJavaMethod(JvmObjectReference objectId, String methodName, Object arg0)
   at Microsoft.Spark.Interop.Ipc.JvmObjectReference.Invoke(String methodName, Object arg0)
   at Microsoft.Spark.Sql.DataFrameReader.LoadSource(String source, String[] paths)
   at Microsoft.Spark.Sql.DataFrameReader.Text(String[] paths)
   at Test.Program.Main(String[] args) in D:\Projects\Test\ProcessStreaming\ProcessStreamPOC\Test\Program.cs:line 19
20/02/26 17:43:31 INFO DotnetRunner: Closing DotnetBackend
20/02/26 17:43:31 INFO DotnetBackend: Requesting to close all call back sockets
20/02/26 17:43:31 INFO SparkContext: Invoking stop() from shutdown hook
20/02/26 17:43:31 INFO SparkUI: Stopped Spark web UI at http://TTC-PC-146:4040
20/02/26 17:43:31 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
20/02/26 17:43:31 INFO MemoryStore: MemoryStore cleared
20/02/26 17:43:31 INFO BlockManager: BlockManager stopped
20/02/26 17:43:31 INFO BlockManagerMaster: BlockManagerMaster stopped
20/02/26 17:43:31 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
20/02/26 17:43:31 INFO SparkContext: Successfully stopped SparkContext
20/02/26 17:43:31 INFO ShutdownHookManager: Shutdown hook called
20/02/26 17:43:31 INFO ShutdownHookManager: Deleting directory C:\Users\User\AppData\Local\Temp\spark-1b7a3800-7555-450d-a7a1-1b3950fd8dfa
20/02/26 17:43:31 INFO ShutdownHookManager: Deleting directory C:\Users\User\AppData\Local\Temp\spark-c78b3955-9a04-435c-8103-1bc6f201ffa2

**Comment by elvaliuliuliu** [comment]
I see the error `Path does not exist: file:/D:/Projects/Test/ProcessStreaming/ProcessStreamPOC/input.txt; `, can you make sure input.txt exists in the path specified?

**Comment by el-genius** [comment]
no, I'm sure the path is correct the problem in jvm bridge i think but i don't know the reason

**Comment by elvaliuliuliu** [comment]
Can you make sure please? Please refer to https://github.com/dotnet/spark/issues/396.

**Comment by el-genius** [comment]
different error

**Comment by elvaliuliuliu** [comment]
Can you point out what different error you are seeing?

And please provide the code snippet and command you are using.

**Comment by el-genius** [comment]
code is the same in microsoft example get started

**Comment by elvaliuliuliu** [comment]
I noticed that your `Program.cs` is in `D:\Projects\Test\ProcessStreaming\ProcessStreamPOC\Test\Program.cs` **Test** folder. Please make sure `input.txt` and `Program.cs`  are in the same folder.

**Comment by el-genius** [comment]
yes in the same folder and i try to pass it as an argument but also the same error

**Comment by el-genius** [comment]
also i try to debug but i couldn't.
there is any way to debug to make it easy for me to identify the issue

**Comment by elvaliuliuliu** [comment]
Can you try with specifying the full path of `input.txt`? Like `DataFrame dataFrame = spark.Read().Text("D:/Projects/Test/ProcessStreaming/ProcessStreamPOC/Test/Program.cs/input.txt");`

You can check [how to debug .NET for Apache Spark application](https://docs.microsoft.com/en-us/dotnet/spark/how-to-guides/debug).

**Comment by Niharikadutta** [comment]
@el-genius Please try out @elvaliuliuliu  suggestion and let us know if it solves your issue. Also we have released 0.10.0 version, please try with this latest version.

**Comment by el-genius** [comment]
after update to new release the error changed to be:

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

**Comment by el-genius** [comment]
It's working (Y) 
I think it's the path of the file because it's not in the build location
Thank you
