### ISSUE TITLE
Unable to find Spark Driver after 16 retries

### ISSUE THREAD

**Issue by aslotte** [dotnet/spark#435]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/run
Operating System: windows

When following the initial setup steps, I got an error saying it `Service SparkDriver failed after 16 retries`

I solved this by adding `.Config("spark.driver.host","127.0.0.1")` to the code building my `SparkSession`, which finally looked like:
```
            SparkSession spark = SparkSession
                .Builder()
                .Config("spark.driver.host","127.0.0.1")
                .AppName("word_count_sample")
                .GetOrCreate();
```

**Comment by elvaliuliuliu** [comment]
Can you share the full log?

**Comment by aslotte** [comment]
```
20/02/28 11:32:11 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
20/02/28 11:32:11 INFO DotnetRunner: Starting DotnetBackend with dotnet.
20/02/28 11:32:12 INFO DotnetRunner: Port number used by DotnetBackend is 51050
20/02/28 11:32:12 INFO DotnetRunner: Adding key=spark.jars and value=file:/C:/Users/Admin/source/repos/Spark/bin/Debug/netcoreapp3.1/microsoft-spark-2.4.x-0.8.0.jar to environment
20/02/28 11:32:12 INFO DotnetRunner: Adding key=spark.app.name and value=org.apache.spark.deploy.dotnet.DotnetRunner to environment
20/02/28 11:32:12 INFO DotnetRunner: Adding key=spark.submit.deployMode and value=client to environment
20/02/28 11:32:12 INFO DotnetRunner: Adding key=spark.master and value=local to environment
[2020-02-28T16:32:12.7774349Z] [DESKTOP-H8AH0LO] [Info] [ConfigurationService] Using port 51050 for connection.
[2020-02-28T16:32:12.7848621Z] [DESKTOP-H8AH0LO] [Info] [JvmBridge] JvMBridge port is 51050
20/02/28 11:32:13 INFO SparkContext: Running Spark version 2.4.1
20/02/28 11:32:13 INFO SparkContext: Submitted application: word_count_sample
20/02/28 11:32:13 INFO SecurityManager: Changing view acls to: Admin
20/02/28 11:32:13 INFO SecurityManager: Changing modify acls to: Admin
20/02/28 11:32:13 INFO SecurityManager: Changing view acls groups to:
20/02/28 11:32:13 INFO SecurityManager: Changing modify acls groups to:
20/02/28 11:32:13 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(Admin); groups with view permissions: Set(); users  with modify permissions: Set(Admin); groups with modify permissions: Set()
20/02/28 11:32:13 WARN Utils: Service 'sparkDriver' could not bind on a random free port. You may check whether configuring an appropriate binding address.
20/02/28 11:32:13 WARN Utils: Service 'sparkDriver' could not bind on a random free port. You may check whether configuring an appropriate binding address.
20/02/28 11:32:13 WARN Utils: Service 'sparkDriver' could not bind on a random free port. You may check whether configuring an appropriate binding address.
20/02/28 11:32:13 WARN Utils: Service 'sparkDriver' could not bind on a random free port. You may check whether configuring an appropriate binding address.
20/02/28 11:32:13 WARN Utils: Service 'sparkDriver' could not bind on a random free port. You may check whether configuring an appropriate binding address.
20/02/28 11:32:13 WARN Utils: Service 'sparkDriver' could not bind on a random free port. You may check whether configuring an appropriate binding address.
20/02/28 11:32:13 WARN Utils: Service 'sparkDriver' could not bind on a random free port. You may check whether configuring an appropriate binding address.
20/02/28 11:32:13 WARN Utils: Service 'sparkDriver' could not bind on a random free port. You may check whether configuring an appropriate binding address.
20/02/28 11:32:13 WARN Utils: Service 'sparkDriver' could not bind on a random free port. You may check whether configuring an appropriate binding address.
20/02/28 11:32:13 WARN Utils: Service 'sparkDriver' could not bind on a random free port. You may check whether configuring an appropriate binding address.
20/02/28 11:32:13 WARN Utils: Service 'sparkDriver' could not bind on a random free port. You may check whether configuring an appropriate binding address.
20/02/28 11:32:13 WARN Utils: Service 'sparkDriver' could not bind on a random free port. You may check whether configuring an appropriate binding address.
20/02/28 11:32:13 WARN Utils: Service 'sparkDriver' could not bind on a random free port. You may check whether configuring an appropriate binding address.
20/02/28 11:32:13 WARN Utils: Service 'sparkDriver' could not bind on a random free port. You may check whether configuring an appropriate binding address.
20/02/28 11:32:13 WARN Utils: Service 'sparkDriver' could not bind on a random free port. You may check whether configuring an appropriate binding address.
20/02/28 11:32:13 WARN Utils: Service 'sparkDriver' could not bind on a random free port. You may check whether configuring an appropriate binding address.
20/02/28 11:32:13 ERROR SparkContext: Error initializing SparkContext.
java.net.BindException: Cannot assign requested address: bind: Service 'sparkDriver' failed after 16 retries (on a random free port)! Consider explicitly setting the appropriate binding address for the service 'sparkDriver' (for example spark.driver.bindAddress for SparkDriver) to the correct binding address.
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:558)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1283)
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:989)
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:254)
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:364)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:748)
20/02/28 11:32:13 INFO SparkContext: Successfully stopped SparkContext
20/02/28 11:32:13 ERROR DotnetBackendHandler: methods:
20/02/28 11:32:13 ERROR DotnetBackendHandler: public org.slf4j.Logger org.apache.spark.sql.SparkSession$Builder.log()
20/02/28 11:32:13 ERROR DotnetBackendHandler: public synchronized org.apache.spark.sql.SparkSession$Builder org.apache.spark.sql.SparkSession$Builder.withExtensions(scala.Function1)
20/02/28 11:32:13 ERROR DotnetBackendHandler: public void org.apache.spark.sql.SparkSession$Builder.initializeLogIfNecessary(boolean)
20/02/28 11:32:13 ERROR DotnetBackendHandler: public boolean org.apache.spark.sql.SparkSession$Builder.initializeLogIfNecessary(boolean,boolean)
20/02/28 11:32:13 ERROR DotnetBackendHandler: public java.lang.String org.apache.spark.sql.SparkSession$Builder.logName()
20/02/28 11:32:13 ERROR DotnetBackendHandler: public void org.apache.spark.sql.SparkSession$Builder.logInfo(scala.Function0,java.lang.Throwable)
20/02/28 11:32:13 ERROR DotnetBackendHandler: public void org.apache.spark.sql.SparkSession$Builder.logInfo(scala.Function0)
20/02/28 11:32:13 ERROR DotnetBackendHandler: public void org.apache.spark.sql.SparkSession$Builder.logError(scala.Function0,java.lang.Throwable)
20/02/28 11:32:13 ERROR DotnetBackendHandler: public void org.apache.spark.sql.SparkSession$Builder.logError(scala.Function0)
20/02/28 11:32:13 ERROR DotnetBackendHandler: public boolean org.apache.spark.sql.SparkSession$Builder.isTraceEnabled()
20/02/28 11:32:13 ERROR DotnetBackendHandler: public void org.apache.spark.sql.SparkSession$Builder.logTrace(scala.Function0,java.lang.Throwable)
20/02/28 11:32:13 ERROR DotnetBackendHandler: public void org.apache.spark.sql.SparkSession$Builder.logTrace(scala.Function0)
20/02/28 11:32:13 ERROR DotnetBackendHandler: public void org.apache.spark.sql.SparkSession$Builder.logDebug(scala.Function0)
20/02/28 11:32:13 ERROR DotnetBackendHandler: public void org.apache.spark.sql.SparkSession$Builder.logDebug(scala.Function0,java.lang.Throwable)
20/02/28 11:32:13 ERROR DotnetBackendHandler: public void org.apache.spark.sql.SparkSession$Builder.logWarning(scala.Function0)
20/02/28 11:32:13 ERROR DotnetBackendHandler: public void org.apache.spark.sql.SparkSession$Builder.logWarning(scala.Function0,java.lang.Throwable)
20/02/28 11:32:13 ERROR DotnetBackendHandler: public synchronized org.apache.spark.sql.SparkSession$Builder org.apache.spark.sql.SparkSession$Builder.config(java.lang.String,double)
20/02/28 11:32:13 ERROR DotnetBackendHandler: public synchronized org.apache.spark.sql.SparkSession$Builder org.apache.spark.sql.SparkSession$Builder.config(java.lang.String,java.lang.String)
20/02/28 11:32:13 ERROR DotnetBackendHandler: public synchronized org.apache.spark.sql.SparkSession$Builder org.apache.spark.sql.SparkSession$Builder.config(java.lang.String,long)
20/02/28 11:32:13 ERROR DotnetBackendHandler: public synchronized org.apache.spark.sql.SparkSession$Builder org.apache.spark.sql.SparkSession$Builder.config(java.lang.String,boolean)
20/02/28 11:32:13 ERROR DotnetBackendHandler: public synchronized org.apache.spark.sql.SparkSession$Builder org.apache.spark.sql.SparkSession$Builder.config(org.apache.spark.SparkConf)
20/02/28 11:32:13 ERROR DotnetBackendHandler: public org.slf4j.Logger org.apache.spark.sql.SparkSession$Builder.org$apache$spark$internal$Logging$$log_()
20/02/28 11:32:13 ERROR DotnetBackendHandler: public boolean org.apache.spark.sql.SparkSession$Builder.initializeLogIfNecessary$default$2()
20/02/28 11:32:13 ERROR DotnetBackendHandler: public void org.apache.spark.sql.SparkSession$Builder.org$apache$spark$internal$Logging$$log__$eq(org.slf4j.Logger)
20/02/28 11:32:13 ERROR DotnetBackendHandler: public org.apache.spark.sql.SparkSession$Builder org.apache.spark.sql.SparkSession$Builder.master(java.lang.String)
20/02/28 11:32:13 ERROR DotnetBackendHandler: public org.apache.spark.sql.SparkSession$Builder org.apache.spark.sql.SparkSession$Builder.appName(java.lang.String)
20/02/28 11:32:13 ERROR DotnetBackendHandler: public synchronized org.apache.spark.sql.SparkSession$Builder org.apache.spark.sql.SparkSession$Builder.sparkContext(org.apache.spark.SparkContext)
20/02/28 11:32:13 ERROR DotnetBackendHandler: public synchronized org.apache.spark.sql.SparkSession$Builder org.apache.spark.sql.SparkSession$Builder.enableHiveSupport()
20/02/28 11:32:13 ERROR DotnetBackendHandler: public synchronized org.apache.spark.sql.SparkSession org.apache.spark.sql.SparkSession$Builder.getOrCreate()
20/02/28 11:32:13 ERROR DotnetBackendHandler: public final void java.lang.Object.wait() throws java.lang.InterruptedException
20/02/28 11:32:13 ERROR DotnetBackendHandler: public final void java.lang.Object.wait(long,int) throws java.lang.InterruptedException
20/02/28 11:32:13 ERROR DotnetBackendHandler: public final native void java.lang.Object.wait(long) throws java.lang.InterruptedException
20/02/28 11:32:13 ERROR DotnetBackendHandler: public boolean java.lang.Object.equals(java.lang.Object)
20/02/28 11:32:13 ERROR DotnetBackendHandler: public java.lang.String java.lang.Object.toString()
20/02/28 11:32:13 ERROR DotnetBackendHandler: public native int java.lang.Object.hashCode()
20/02/28 11:32:13 ERROR DotnetBackendHandler: public final native java.lang.Class java.lang.Object.getClass()
20/02/28 11:32:13 ERROR DotnetBackendHandler: public final native void java.lang.Object.notify()
20/02/28 11:32:13 ERROR DotnetBackendHandler: public final native void java.lang.Object.notifyAll()
20/02/28 11:32:13 ERROR DotnetBackendHandler: args:
[2020-02-28T16:32:13.8810217Z] [DESKTOP-H8AH0LO] [Error] [JvmBridge] JVM method execution failed: Nonstatic method getOrCreate failed for class 1 when called with no arguments
[2020-02-28T16:32:13.8811613Z] [DESKTOP-H8AH0LO] [Error] [JvmBridge] java.net.BindException: Cannot assign requested address: bind: Service 'sparkDriver' failed after 16 retries (on a random free port)! Consider explicitly setting the appropriate binding address for the service 'sparkDriver' (for example spark.driver.bindAddress for SparkDriver) to the correct binding address.
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:558)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1283)
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:989)
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:254)
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:364)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:748)

[2020-02-28T16:32:13.9135762Z] [DESKTOP-H8AH0LO] [Exception] [JvmBridge] JVM method execution failed: Nonstatic method getOrCreate failed for class 1 when called with no arguments
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)
Unhandled exception. System.Exception: JVM method execution failed: Nonstatic method getOrCreate failed for class 1 when called with no arguments
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallNonStaticJavaMethod(JvmObjectReference objectId, String methodName, Object[] args)
   at Microsoft.Spark.Sql.Builder.GetOrCreate()
   at MySparkApp.Program.Main(String[] args) in C:\Users\Admin\source\repos\Spark\Program.cs:line 10
20/02/28 11:32:28 INFO DotnetRunner: Closing DotnetBackend
20/02/28 11:32:28 INFO DotnetBackend: Requesting to close all call back sockets
20/02/28 11:32:28 INFO ShutdownHookManager: Shutdown hook called
20/02/28 11:32:28 INFO ShutdownHookManager: Deleting directory C:\Users\Admin\AppData\Local\Temp\spark-786785fc-327a-4e44-86ac-2dc2a5b3efa0
```

**Comment by imback82** [comment]
Can you share your `spark-submit` command?

Btw, any reason why you want to set the driver address explicitly? Can you also try setting ` SPARK_LOCAL_IP` env variable to `127.0.0.1` or try `.Config("spark.driver.bindAddress", "127.0.0.1")`?

**Comment by aslotte** [comment]
Here's the command I'm using:
```
C:\Users\Admin\source\repos\Spark> %SPARK_HOME%\bin\spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local bin\Debug\netcoreapp3.1\microsoft-spark-2.4.x-0.8.0.jar dotnet bin\Debug\netcoreapp3.1\Spark.dll
```

The only reason I added the driver address explicitly was because that came up as a solution to this problem when googling it. Thanks!

**Comment by imback82** [comment]
Got it. Did `SPARK_LOCAL_IP` or `spark.driver.bindAddress` help you, or no?

**Comment by fithisux** [comment]
In my case It solved the exact same issue on my Mac OS Catalina, both for spark-shell and SparkR.

I installed SparkR in R 4.0.0. from master

and had to use (I use java 14 for dev)

library(SparkR)
Sys.setenv(SPARK_HOME = "(my home dir)/Downloads/spark-3.0.0-bin-hadoop3.2")
Sys.setenv(SPARK_LOCAL_IP = "127.0.0.1")
Sys.setenv(JAVA_HOME = "/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home")
sparkR.session(master = "local[*]", sparkConfig = list(spark.driver.memory = "2g"))

**Comment by imback82** [comment]
Thanks @fithisux. In this case, I will close this issue. Please feel free to reopen if you encounter any other issues.
