### ISSUE TITLE
Issue Following Tutorial

### ISSUE THREAD

**Issue by rmart10** [dotnet/spark#448]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/run
Operating System: windows

Thought I followed the tutorial to a tee, got the following when attempting to run the code:

`c:\Users\Username\mySparkApp\bin\Debug\netcoreapp3.1>mySparkApp.exe
[2020-03-09T17:37:05.7783466Z] [MachineName] [Info] [ConfigurationService] 'DOTNETBAC
KEND_PORT' environment variable is not set.
[2020-03-09T17:37:05.7903466Z] [MachineName] [Info] [ConfigurationService] Using port
 5567 for connection.
[2020-03-09T17:37:05.7953466Z] [MachineName] [Info] [JvmBridge] JvMBridge port is 556
7
[2020-03-09T17:37:07.0203466Z] [MachineName] [Exception] [JvmBridge] No connection co
uld be made because the target machine actively refused it. 127.0.0.1:5567
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddre
ss socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at Microsoft.Spark.Network.DefaultSocketWrapper.Connect(IPAddress remoteaddr,
 Int32 port, String secret)
   at Microsoft.Spark.Interop.Ipc.JvmBridge.GetConnection()
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Obj
ect classNameOrJvmObjectReference, String methodName, Object[] args)
Unhandled exception. System.Net.Internals.SocketExceptionFactory+ExtendedSocketE
xception (10061): No connection could be made because the target machine activel
y refused it. 127.0.0.1:5567
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddre
ss socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at Microsoft.Spark.Network.DefaultSocketWrapper.Connect(IPAddress remoteaddr,
 Int32 port, String secret)
   at Microsoft.Spark.Interop.Ipc.JvmBridge.GetConnection()
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Obj
ect classNameOrJvmObjectReference, String methodName, Object[] args)
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallStaticJavaMethod(String classNam
e, String methodName, Object[] args)
   at Microsoft.Spark.Sql.Builder..ctor()
   at Microsoft.Spark.Sql.SparkSession.Builder()
   at MySparkApp.Program.Main(String[] args) in C:\Users\UserName\mySparkApp\Pro
gram.cs:line 10`

**Comment by elvaliuliuliu** [comment]
Thanks for your question. Can you share the command you use to run?

**Comment by rmart10** [comment]
Sure can, I initially just used command prompt window and CD'd into the dir with the exe (which did compile successfully): 

C:\Users\[me]>cd C:\Users\[me]\mySparkApp\bin\Debug\netcoreapp3.1

C:\Users\[me]\mySparkApp\bin\Debug\netcoreapp3.1>mySparkApp.exe

I got the same results however by opening up VS and debugging via IDE.

Thank you!

**Comment by elvaliuliuliu** [comment]
Please follow the command line in the tutorial to run:
`%SPARK_HOME%\bin\spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local bin\Debug\netcoreapp3.1\microsoft-spark-2.4.x-0.10.0.jar dotnet bin\Debug\netcoreapp3.1\mySparkApp.dll `

**Comment by elvaliuliuliu** [comment]
@rmart10 : Does the precious suggestion work for you?

**Comment by imback82** [comment]
@rmart10 Please reopen the issue if the solution provided by @elvaliuliuliu didn't solve your issue.
