### ISSUE TITLE
[BUG]: DataFrame.Count() method fails

### ISSUE THREAD

**Issue by jimishbhayani** [dotnet/spark#450]
**Describe the bug**
Getting following error when running DataFrame.Count().

[2020-03-18T21:53:59.8533131Z] [wn15-o365cc] [Exception] [JvmBridge] JVM method execution failed: Nonstatic method count failed for class 36 when called with no arguments
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)
SystemLog: 3/18/20 9:54:00 PM unexpected exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: JVM method execution failed: Nonstatic method count failed for class 36 when called with no arguments
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)
   at Microsoft.Spark.Sql.DataFrame.Count()
   at <redacted>
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at <redacted>
SystemLog: .NET EndTime 3/18/20 9:54:00 PM

**To Reproduce**
Loading few json files and doing at distinct count on one of the column.

Sample Code: 
string IdColumnName = "Id";
string TypeColumnName = "Type";
string FilePathColumnName = "FilePath";
var filePathCol = Col(FilePathColumnName);
var typeCol = Col(TypeColumnName);

Func<Column, Column> GetFileName = Udf<string, string>((str) => Path.GetFileName(str));
Func<Column, Column> SplitFileName = Udf<string, string[]>((str) => str.Split('_'));

var directoryDF = spark.Read().Json(directoryInputPath).As("directoryDF");
directoryDF = directoryDF.WithColumn(FilePathColumnName, GetFileName(InputFileName()))
				.WithColumn("_tmp", SplitFileName(filePathCol))
				.WithColumn(TypeColumnName, Col("_tmp").GetItem(0))
				.WithColumn(IdColumnName, Col("_tmp").GetItem(1))
				.Drop("_tmp");

Console.WriteLine($"DirectoryDF schema : {directoryDF.Schema().Json}");

var files = directoryDF.Select(FilePathColumnName).Distinct();
Console.WriteLine($"Number of Files through Spark : {files.Count()}");

Spark Version : 2.3.2
Spark dotnet Version : 0.10.0

Code should print the number of rows.

**Desktop (please complete the following information):**
 - OS: ubuntu.16.04-x64

**Comment by elvaliuliuliu** [comment]
I will take a look!

**Comment by elvaliuliuliu** [comment]
@jimishbhayani : Can you paste the full log here and the cmd you used to submit the job? Thank you!

**Comment by jimishbhayani** [comment]
Seems to be known issue. Closing the duplicate issue.
