### ISSUE TITLE
Failed to load org.apache.spark.deploy.dotnet.DotnetRunner

### ISSUE THREAD

**Issue by initinli** [dotnet/spark#571]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

unable to run demo app, getting below error - 

C:\Z\Test\Spark.net\mySparkApp>%SPARK_HOME%\bin\spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local bin\Debug\netcoreapp3.1\microsoft-spark-2.4.x-0.10.0.jar dotnet bin\Debug\netcoreapp3.1\mySparkApp.dll
20/06/27 16:11:55 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
20/06/27 16:11:55 WARN DependencyUtils: Local jar C:\Z\Test\Spark.net\mySparkApp\bin\Debug\netcoreapp3.1\microsoft-spark-2.4.x-0.10.0.jar does not exist, skipping.
20/06/27 16:11:55 WARN SparkSubmit$$anon$2: **Failed to load org.apache.spark.deploy.dotnet.DotnetRunner**.
java.lang.ClassNotFoundException: org.apache.spark.deploy.dotnet.DotnetRunner
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.apache.spark.util.Utils$.classForName(Utils.scala:238)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:810)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
20/06/27 16:11:55 INFO ShutdownHookManager: Shutdown hook called
20/06/27 16:11:55 INFO ShutdownHookManager: Deleting directory C:\Users\G547482\AppData\Local\Temp\spark-6b1ed2f6-294a-4a74-8823-d34d55fcc175

**Comment by imback82** [comment]
> 20/06/27 16:11:55 WARN DependencyUtils: Local jar C:\Z\Test\Spark.net\mySparkApp\bin\Debug\netcoreapp3.1\microsoft-spark-2.4.x-0.10.0.jar does not exist, skipping.

Can you verify this jar exists first?

**Comment by initinli** [comment]
Hi @imback82,

You are right, this jar didn't exists, I updated the **Microsoft.Spark** nuget version from latest **0.12** to **0.10** and it worked.

Thank you.

**Comment by imback82** [comment]
I see. In this case, the jar name should have been `microsoft-spark-2.4.x-0.12.0.jar` to match the Nuget version.
