### ISSUE TITLE
[BUG]: Hyperspace CreateIndex failed

### ISSUE THREAD

**Issue by pherbel** [dotnet/spark#580]
**Describe the bug**
I try to test Hyperspace index with our dataset (CSV) and it seems failed during the creation.

**To Reproduce**

1. Create new .Net Spark Console app
2. Add .Net spark extension nuget package Hyperspace 
3. Create Session
4. Add data frame
5. Create index

```csharp
            var hs = new Hyperspace(spark);
            hs.CreateIndex(dataFrame, new IndexConfig("CarIndex", new string[] { "Car" }));
            hs.CreateIndex(dataFrame, new IndexConfig("TimeIndex", new string[] { "Tim" }));

            hs.Indexes().Show();
```

**Expected behavior**
New index created and app will show in the log.

**Desktop (please complete the following information):**
 - OS: Win 10 2004
 - Spark Version: 2.4.6
 - .Net Spark Version: 0.12.1

**Additional context**
Log
20/07/06 13:06:53 ERROR DotnetBackendHandler: Failed to execute 'createIndex' on 'com.microsoft.hyperspace.Hyperspace' with args=([Type=org.apache.spark.sql.Dataset, Value: [Car: int, Tim: int ... 16 more fields]], [Type=com.microsoft.hyperspace.index.IndexConfig, Value: [indexName: TimeIndex; indexedColumns: tim; includedColumns: ]])
[2020-07-06T11:06:53.2501359Z] [PHERBEL-DESKTOP] [Error] [JvmBridge] JVM method execution failed: Nonstatic method 'createIndex' failed for class '13' when called with 2 arguments ([Index=1, Type=DataFrame, Value=Microsoft.Spark.Sql.DataFrame], [Index=2, Type=IndexConfig, Value=[indexName: TimeIndex; indexedColumns: tim; includedColumns: ]], )
[2020-07-06T11:06:53.2501973Z] [PHERBEL-DESKTOP] [Error] [JvmBridge] com.esotericsoftware.kryo.KryoException: java.util.ConcurrentModificationException
Serialization trace:
classes (sun.misc.Launcher$AppClassLoader)
classloader (java.security.ProtectionDomain)
context (java.security.AccessControlContext)
acc (org.apache.spark.util.MutableURLClassLoader)
classLoader (org.apache.hadoop.conf.Configuration)
conf (org.apache.hadoop.io.compress.BZip2Codec)
codecs (org.apache.hadoop.io.compress.CompressionCodecFactory)
codecFactory (org.apache.spark.sql.execution.datasources.csv.CSVFileFormat)
fileFormat (com.microsoft.hyperspace.index.serde.package$HadoopFsRelationWrapper)
relation (com.microsoft.hyperspace.index.serde.package$LogicalRelationWrapper)
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:101)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:651)
        at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:361)
        at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:302)
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
        at com.esotericsoftware.kryo.Kryo.writeObjectOrNull(Kryo.java:629)
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:86)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:651)
        at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:113)
        at com.esotericsoftware.kryo.serializers.DefaultSerializers$TreeMapSerializer.write(DefaultSerializers.java:684)
        at com.esotericsoftware.kryo.serializers.DefaultSerializers$TreeMapSerializer.write(DefaultSerializers.java:680)
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:651)
        at com.microsoft.hyperspace.index.serde.KryoSerDeUtils$.serialize(KryoSerDeUtils.scala:41)
        at com.microsoft.hyperspace.index.serde.LogicalPlanSerDeUtils$.serialize(LogicalPlanSerDeUtils.scala:46)
        at com.microsoft.hyperspace.actions.CreateActionBase.getIndexLogEntry(CreateActionBase.scala:61)
        at com.microsoft.hyperspace.actions.CreateAction.logEntry$lzycompute(CreateAction.scala:36)
        at com.microsoft.hyperspace.actions.CreateAction.logEntry(CreateAction.scala:35)
        at com.microsoft.hyperspace.actions.Action$class.begin(Action.scala:49)
        at com.microsoft.hyperspace.actions.Action$class.run(Action.scala:86)
        at com.microsoft.hyperspace.actions.CreateAction.run(CreateAction.scala:27)
        at com.microsoft.hyperspace.index.IndexCollectionManager.create(IndexCollectionManager.scala:42)
        at com.microsoft.hyperspace.index.CachingIndexCollectionManager.create(CachingIndexCollectionManager.scala:77)
        at com.microsoft.hyperspace.Hyperspace.createIndex(Hyperspace.scala:41)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.handleMethodCall(DotnetBackendHandler.scala:145)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.handleBackendRequest(DotnetBackendHandler.scala:85)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.channelRead0(DotnetBackendHandler.scala:28)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.channelRead0(DotnetBackendHandler.scala:23)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.util.ConcurrentModificationException
        at java.util.Vector$Itr.checkForComodification(Unknown Source)
        at java.util.Vector$Itr.next(Unknown Source)
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:99)
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:40)
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
        ... 81 more

[2020-07-06T11:06:53.2638537Z] [PHERBEL-DESKTOP] [Exception] [JvmBridge] JVM method execution failed: Nonstatic method 'createIndex' failed for class '13' when called with 2 arguments ([Index=1, Type=DataFrame, Value=Microsoft.Spark.Sql.DataFrame], [Index=2, Type=IndexConfig, Value=[indexName: TimeIndex; indexedColumns: tim; includedColumns: ]], )
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)
Unhandled exception. System.Exception: JVM method execution failed: Nonstatic method 'createIndex' failed for class '13' when called with 2 arguments ([Index=1, Type=DataFrame, Value=Microsoft.Spark.Sql.DataFrame], [Index=2, Type=IndexConfig, Value=[indexName: TimeIndex; indexedColumns: tim; includedColumns: ]], )
 ---> Microsoft.Spark.JvmException: com.esotericsoftware.kryo.KryoException: java.util.ConcurrentModificationException
Serialization trace:
classes (sun.misc.Launcher$AppClassLoader)
classloader (java.security.ProtectionDomain)
context (java.security.AccessControlContext)
acc (org.apache.spark.util.MutableURLClassLoader)
classLoader (org.apache.hadoop.conf.Configuration)
conf (org.apache.hadoop.io.compress.BZip2Codec)
codecs (org.apache.hadoop.io.compress.CompressionCodecFactory)
codecFactory (org.apache.spark.sql.execution.datasources.csv.CSVFileFormat)
fileFormat (com.microsoft.hyperspace.index.serde.package$HadoopFsRelationWrapper)
relation (com.microsoft.hyperspace.index.serde.package$LogicalRelationWrapper)
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:101)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:651)
        at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:361)
        at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:302)
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
        at com.esotericsoftware.kryo.Kryo.writeObjectOrNull(Kryo.java:629)
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:86)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:651)
        at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:113)
        at com.esotericsoftware.kryo.serializers.DefaultSerializers$TreeMapSerializer.write(DefaultSerializers.java:684)
        at com.esotericsoftware.kryo.serializers.DefaultSerializers$TreeMapSerializer.write(DefaultSerializers.java:680)
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:651)
        at com.microsoft.hyperspace.index.serde.KryoSerDeUtils$.serialize(KryoSerDeUtils.scala:41)
        at com.microsoft.hyperspace.index.serde.LogicalPlanSerDeUtils$.serialize(LogicalPlanSerDeUtils.scala:46)
        at com.microsoft.hyperspace.actions.CreateActionBase.getIndexLogEntry(CreateActionBase.scala:61)
        at com.microsoft.hyperspace.actions.CreateAction.logEntry$lzycompute(CreateAction.scala:36)
        at com.microsoft.hyperspace.actions.CreateAction.logEntry(CreateAction.scala:35)
        at com.microsoft.hyperspace.actions.Action$class.begin(Action.scala:49)
        at com.microsoft.hyperspace.actions.Action$class.run(Action.scala:86)
        at com.microsoft.hyperspace.actions.CreateAction.run(CreateAction.scala:27)
        at com.microsoft.hyperspace.index.IndexCollectionManager.create(IndexCollectionManager.scala:42)
        at com.microsoft.hyperspace.index.CachingIndexCollectionManager.create(CachingIndexCollectionManager.scala:77)
        at com.microsoft.hyperspace.Hyperspace.createIndex(Hyperspace.scala:41)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.handleMethodCall(DotnetBackendHandler.scala:145)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.handleBackendRequest(DotnetBackendHandler.scala:85)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.channelRead0(DotnetBackendHandler.scala:28)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.channelRead0(DotnetBackendHandler.scala:23)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.util.ConcurrentModificationException
        at java.util.Vector$Itr.checkForComodification(Unknown Source)
        at java.util.Vector$Itr.next(Unknown Source)
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:99)
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:40)
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
        ... 81 more

   --- End of inner exception stack trace ---
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object arg0, Object arg1)
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallNonStaticJavaMethod(JvmObjectReference objectId, String methodName, Object arg0, Object arg1)
   at Microsoft.Spark.Interop.Ipc.JvmObjectReference.Invoke(String methodName, Object arg0, Object arg1)
   at Microsoft.Spark.Extensions.Hyperspace.Hyperspace.CreateIndex(DataFrame df, IndexConfig indexConfig)
   at SparkConsoleAppTest.Program.Main(String[] args) in C:\Repos\src\SparkConsoleAppTest\Program.cs:line 37

**Comment by suhsteve** [comment]
@AFFogarty can you look into this ?

**Comment by imback82** [comment]
I see the following:
```
at com.microsoft.hyperspace.index.serde.KryoSerDeUtils$.serialize(KryoSerDeUtils.scala:41)
at com.microsoft.hyperspace.index.serde.LogicalPlanSerDeUtils$.serialize(LogicalPlanSerDeUtils.scala:46)
at com.microsoft.hyperspace.actions.CreateActionBase.getIndexLogEntry(CreateActionBase.scala:61)
at com.microsoft.hyperspace.actions.CreateAction.logEntry$lzycompute(CreateAction.scala:36)
at com.microsoft.hyperspace.actions.CreateAction.logEntry(CreateAction.scala:35)
at com.microsoft.hyperspace.actions.Action$class.begin(Action.scala:49)
at com.microsoft.hyperspace.actions.Action$class.run(Action.scala:86)
at com.microsoft.hyperspace.actions.CreateAction.run(CreateAction.scala:27)
at com.microsoft.hyperspace.index.IndexCollectionManager.create(IndexCollectionManager.scala:42)
at com.microsoft.hyperspace.index.CachingIndexCollectionManager.create(CachingIndexCollectionManager.scala:77)
at com.microsoft.hyperspace.Hyperspace.createIndex(Hyperspace.scala:41)
```

@pherbel Can you share how you are creating `dataFrame`?

cc: @apoorvedave1 / @pirz Can you try to repro with a CSV file format?

**Comment by apoorvedave1** [comment]
Thanks, @imback82
I couldn't repro the issue with this simple code
```
object Test extends App {
  val spark: SparkSession = SparkSession
    .builder()
    .master(s"local[*]")
    .getOrCreate()
  import spark.implicits._
  val df = spark.range(1,5).toDF("id")
  df.write.mode("overwrite").option("header", true).csv("parquettest")

  val df2 = spark.read.option("header", true).csv("parquettest")
  df2.printSchema()
  val hs = new Hyperspace(spark)

  hs.createIndex(df2, new IndexConfig("ic1", Seq("id"), Seq()))      // worked fine
}
```

**Comment by pherbel** [comment]
@imback82 

Here is the other part of the source code.
``` csharp

            // Create a Spark session
            SparkSession spark = SparkSession
                .Builder()
                .AppName("CSVMessage_Processing")
                .GetOrCreate()
                .EnableHyperspace();


            // Create initial DataFrame
            DataFrame dataFrame = spark
                .Read()
                .Option("header", true)
                .Option("sep", "|")
                .Schema("Car INT, Tim INT,Msg INT, Lat INT, Lon INT, Dir INT,Spd INT," +
                        "Sta INT, Sns INT, Par INT, An0 INT, An1 INT, An2 INT, An3 INT," +
                        "An4 INT, An5 INT, An6 INT, An7 INT")
                .Csv(@"C:\Repos\sampledata\datalake\year=2020\month=06\day=22\hour=11\*\*.txt");
```

CSV format:

```
Car|Tim|Msg|Lat|Lon|Dir|Spd|Sta|Sns|Par|An0|An1|An2|An3|An4|An5|An6|An7|
4562344|1592823595|2|47393500|17375500|240|6|1|67108865|0|431|615|0|590|1023|1023|1592823596|0|
```

**Comment by pherbel** [comment]
Also I don't know exactly that it could be a problem or not, but I installed the jar files manually for local development.

So, I downloaded the jar files (Delta, Hyperspace) and installed into the "jars" directory in my local spark install.
It seems to start working, but got the error.

**Comment by apoorvedave1** [comment]
Thanks @pherbel, I could repro the issue. I will update with my findings soon.

**Comment by apoorvedave1** [comment]
Thanks @pherbel, did you materialize the data before creating the index? I could repro the issue only if I call `df.show()` before `hs.createIndex()`. If I don't call `df.show()`, it works fine and creates index without issue.

We are working to fix this problem. In the mean time, could you avoid calling `df.show()` or any other form of materializing the df before creating index?

Here's my repro
```
object Test extends App {
  val spark: SparkSession = ...
  
  val df = spark.read.csv("csv/*/*")
  df.show()                            // commenting this line eliminates the issue
  val hs = new Hyperspace(spark)
  hs.createIndex(df, new IndexConfig("ic2", Seq("_c0"), Seq()))
}
```

**Comment by apoorvedave1** [comment]
Explanation: In case of csv, on materializing the df before creating index, it creates some internal objects which don't support serialization (specifically [this](https://github.com/apache/spark/blob/90b9099064059e414bf3535f7f250aad384288b5/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/FileFormat.scala#L171)

**Comment by imback82** [comment]
@pherbel This issue has been fixed and SNAPSHOT artifacts have been published. And you can consume it as follows:
```
spark-submit --packages com.microsoft.hyperspace:hyperspace-core_2.11:0.2.0-SNAPSHOT --repositories https://oss.sonatype.org/content/repositories/snapshots/  <other args>
```
Please let us know if this fixes your issue. Thanks!

**Comment by pherbel** [comment]
@apoorvedave1 Thanks for the quick work on it. This is great.
I don't call dataframe.Show() before the index creation. 


@imback82 Unfortunately, I couldn't get the packages with this method. Does this need authentication?
Can I access the jar directly somehow?

**Comment by imback82** [comment]
@pherbel Can you get to this? https://oss.sonatype.org/content/repositories/snapshots/com/microsoft/hyperspace/hyperspace-core_2.11/0.2.0-SNAPSHOT/

**Comment by pherbel** [comment]
@imback82 Thanks. I could download it.

Now It seems works! Great!

I really appreciate your quick work on it. Thanks for everybody.

Now I can start to test the index.

**Comment by pherbel** [comment]
After the next version will be out. I will check and we can close this.
