### ISSUE TITLE
spark-submit command have one error

### ISSUE THREAD

**Issue by zwhrenxiaoxue** [dotnet/spark#605]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/run
Operating System: windows

When run the spark-submit command, shows error below:

C:\bin\spark-3.0.0-bin-hadoop2.7\bin\spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local C:\MySparkApp\MySparkApp\bin\Debug\netcoreapp3.1\microsoft-spark-2.4.x-0.12.1.jar dotnet C:\MySparkApp\MySparkApp\bin\Debug\netcoreapp3.1\mySparkApp.dll
20/07/28 14:34:47 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/internal/Logging$class
        at org.apache.spark.deploy.dotnet.DotnetRunner$.<init>(DotnetRunner.scala:35)
        at org.apache.spark.deploy.dotnet.DotnetRunner$.<clinit>(DotnetRunner.scala)
        at org.apache.spark.deploy.dotnet.DotnetRunner.main(DotnetRunner.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.internal.Logging$class
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 15 more
20/07/28 14:34:47 INFO util.ShutdownHookManager: Shutdown hook called
20/07/28 14:34:47 INFO util.ShutdownHookManager: Deleting directory C:\Users\AppData\Local\Temp\spark-5dcf252b-4f2e-4183-bc73-69c7d5b209dd

**Comment by imback82** [comment]
.NET for Apache Spark doesn't support Spark 3.0 yet. Can you try with [Spark 2.4.6](https://spark.apache.org/news/spark-2-4-6.html)?

**Comment by zwhrenxiaoxue** [comment]
> .NET for Apache Spark doesn't support Spark 3.0 yet. Can you try with [Spark 2.4.6](https://spark.apache.org/news/spark-2-4-6.html)?

Already try. Now it works fine. Thanks for your answer.
