### ISSUE TITLE
Run the code from VS with error

### ISSUE THREAD

**Issue by zwhrenxiaoxue** [dotnet/spark#606]
When directly run the code from visual studio, show below error.

[2020-07-28T07:03:19.0230469Z] [] [Info] [ConfigurationService] 'DOTNETBACKEND_PORT' environment variable is not set.
[2020-07-28T07:03:19.0569705Z] [] [Info] [ConfigurationService] Using port 5567 for connection.
[2020-07-28T07:03:19.0657704Z] [] [Info] [JvmBridge] JvMBridge port is 5567
[2020-07-28T07:03:20.4328674Z] [] [Exception] [JvmBridge] No connection could be made because the target machine actively refused it. 127.0.0.1:5567
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at Microsoft.Spark.Network.DefaultSocketWrapper.Connect(IPAddress remoteaddr, Int32 port, String secret)
   at Microsoft.Spark.Interop.Ipc.JvmBridge.GetConnection()
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)

C:\Winnie\MySparkApp\MySparkApp\bin\Debug\netcoreapp3.1\MySparkApp.exe (process 16544) exited with code -1.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .

**Comment by imback82** [comment]
For this experience, you need to have a Spark process running as described here: https://github.com/dotnet/spark/blob/master/docs/developer-guide.md#debugging-spark-net-application
