### ISSUE TITLE
[BUG]: Python worker exited unexpectedly (crashed). Increased the executor instance memory but still, it is facing the same issue.

### ISSUE THREAD

**Issue by PavankumarM1** [dotnet/spark#607]
Source: Delta
Sink: Delta
Processing engine: Spark structured streaming API
Streaming job running continuously.
 
Below error is throwing few times a day. We are not able to reproduce the issue. 
First task is failing but in the next attempts same task is getting succeeded. What is the RCA and How to resolve the issue?
 
WHAT ACTION HAVE YOU DONE SO FAR?
Increased the executor instance memory but still, it is facing the same issue
 

WARN TaskSetManager: Lost task 1.0 in stage XYX.0 (TID 121658, 10.ZZ.XX.YY, executor 0): org.apache.spark.SparkException: Python worker exited unexpectedly (crashed)

at org.apache.spark.api.python.BasePythonRunner$ReaderIterator$$anonfun$3.applyOrElse(PythonRunner.scala:574)

at org.apache.spark.api.python.BasePythonRunner$ReaderIterator$$anonfun$3.applyOrElse(PythonRunner.scala:563)

at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)

at org.apache.spark.sql.execution.python.PythonUDFRunner$$anon$1.read(PythonUDFRunner.scala:86)

at org.apache.spark.sql.execution.python.PythonUDFRunner$$anon$1.read(PythonUDFRunner.scala:64)

at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:494)

at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)

at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)

at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)

at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)

at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)

at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)

at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)

at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:640)

at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:235)

at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:173)

at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:172)

at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)

at org.apache.spark.scheduler.Task.doRunTask(Task.scala:140)

at org.apache.spark.scheduler.Task.run(Task.scala:113)

at org.apache.spark.executor.Executor$TaskRunner$$anonfun$13.apply(Executor.scala:537)

at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1541)

at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:543)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

at java.lang.Thread.run(Thread.java:748)

Caused by: java.io.EOFException

at java.io.DataInputStream.readInt(DataInputStream.java:392)

at org.apache.spark.sql.execution.python.PythonUDFRunner$$anon$1.read(PythonUDFRunner.scala:71)

... 22 more

**Comment by imback82** [comment]
@PavankumarM1 Can you describe what C# UDF does in this application (sample code will be helpful)?

Also can you share the full logs for this job?

**Comment by imback82** [comment]
Also, without a simple repro locally, it will be hard to debug. Looking at the exception, it could be caused by user data, UDF, etc.

Just looking at the logs you shared, I don't see anything suspicious from the .NET for Apache Spark side.

**Comment by PavankumarM1** [comment]
Hello Terry,

I have the code for UDFs
If you wish to see I can share with you over personal email.

Thanks,
Pavankumar Manchala

**Comment by rapoth** [comment]
@PavankumarM1 Would you be able to provide a simple repro using a UDF and dataset that you would feel comfortable sharing? (this is for the benefit of our broader community)

**Comment by suhsteve** [comment]
Hi, we are going to close this issue as it has been inactive for a while. Please feel free to re-open it if the issue persists and/or there are any new updates. Thank you!

**Comment by moredatapls** [comment]
If someone encounters a similar exception: make sure that you set a valid checkpoint path for your streaming job. For me, the job crashed on Databricks because I had my checkpoint location set to `dbfs:/checkpoints/...` instead of `dbfs://checkpoints/...`

A similar issue related to the Spark CosmosDB connector: https://github.com/Azure/azure-cosmosdb-spark/issues/143
