### ISSUE TITLE
failed to connect the SQL server in spark APP 

### ISSUE THREAD

**Issue by zwhrenxiaoxue** [dotnet/spark#610]
Add below jar, the error still shows.
https://github.com/sfrechette/spark-jdbc-mssql

[2020-08-03T07:40:02.1306428Z] [US84EXUO2S] [Error] [JvmBridge] java.sql.SQLException: No suitable driver
        at java.sql.DriverManager.getDriver(Unknown Source)
        at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions$$anonfun$6.apply(JDBCOptions.scala:105)
        at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions$$anonfun$6.apply(JDBCOptions.scala:105)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:104)
        at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:35)
        at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:32)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:318)
        at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:167)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.handleMethodCall(DotnetBackendHandler.scala:145)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.handleBackendRequest(DotnetBackendHandler.scala:85)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.channelRead0(DotnetBackendHandler.scala:28)

my code:

            DataFrame jdbcDf = spark.Read().Format("jdbc").Options(
                new Dictionary<string, string>
                {
                        {"url", "jdbc:sqlserver://servername;databaseName=dddd;"},
                        {"dbtable", "dddd"},
                        {"user", "ddd"},
                        {"password", "ddd"}
        })
    .Load();

**Comment by imback82** [comment]
Can you try stackoverflow for this message "java.sql.SQLException: No suitable driver"? There are many answers like [this](https://stackoverflow.com/questions/8146793/no-suitable-driver-found-for-jdbcmysql-localhost3306-mysql).

**Comment by zwhrenxiaoxue** [comment]
> Can you try stackoverflow for this message "java.sql.SQLException: No suitable driver"? There are many answers like [this](https://stackoverflow.com/questions/8146793/no-suitable-driver-found-for-jdbcmysql-localhost3306-mysql).

The link shows the database is MYsql. However, I want to connect to SQL server.

**Comment by imback82** [comment]
Yes, that was just one example. Since I do not know your SQL server settings, you should just search online with the exception message.

**Comment by rrekapalli** [comment]
@zwhrenxiaoxue , I was able to write to SQL Server using another version of the JDBC driver (mssql-jdbc-8.2.2.jre8.jar).  This has to be copied to JARS in "\Spark\bin\spark-2.4.5-bin-hadoop2.7\jars".  However, depending on volume of data that you are rying to write, you may need to increase the worker memory and driver memory settings while submitting the spark job with the following config settings:

--conf spark.driver.memory=4g
--conf spark.executor.memory=8g.  Otherwise, you may get some GC exceeded error messages. 

You can find the driver at [here](https://docs.microsoft.com/en-us/sql/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server?view=sql-server-ver15)

**Comment by zwhrenxiaoxue** [comment]
> @zwhrenxiaoxue , I was able to write to SQL Server using another version of the JDBC driver (mssql-jdbc-8.2.2.jre8.jar). This has to be copied to "\Spark\bin\spark-2.4.5-bin-hadoop2.7\jars". However, depending on volume of data that you are trying to write, you may need to increase the worker memory and driver memory settings while submitting the spark job with following config settings:
> 
> --conf spark.driver.memory=4g
> --conf spark.executor.memory=8g. Otherwise, you may get some GC exceeded error messages.
> 
> A sample read call could be like this:
> 
> Spark.Read()
> .Format("jdbc")
> .Option("driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver")
> .Option("url", @"jdbc:sqlserver://localhost:1433;databaseName=" + dbName + ";")
> .Option("dbtable", tableName)
> .Option("username", userName)
> .Option("password", password)
> .Load();
> 
> You can find the driver at [here](https://docs.microsoft.com/en-us/sql/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server?view=sql-server-ver15)
> 
> Please be advised, this is pretty slow while writing data to SQL Server.

Thank you for your answer. It works now. Thank you again.

**Comment by chen-xin-lay** [comment]
I also had problems with connection data.
java.lang.ClassNotFoundException: com.microsoft.sqlserver.jdbc.SQLServerDriver

**Comment by chen-xin-lay** [comment]
![image](https://user-images.githubusercontent.com/69895291/91289495-fea42d00-e7c4-11ea-9797-9aa768271b0a.png)
