### ISSUE TITLE
Issue with Multiple Spark Sessions on single context

### ISSUE THREAD

**Issue by rrekapalli** [dotnet/spark#630]
**Describe the bug**

When trying to create multiple sessions on a single context, getting the following error. 

Basically, trying to create multiple sessions as shown below:

```
foreach(Rule rule in _rules)
{
         // Create a brand new session object for each rule.
         // _Spark is the original session created
         /*
             var _Spark = SparkSession.Builder().AppName("myApp").GetOrCreate();
         */
         SparkSession ruleSession = _Spark.NewSession();
         
         // Pass the session object to the rle
         rule.SetSparkSession(ruleSession, _batchGuid, _batchName + "-" + rule.GetMnemonic());

          // Pass the global data to the rule object
          rule.SetData(_ruleData);

          // Execute the rule after validation with the provided session
          if (rule.PreCondition()) ExecuteRule(rule);

          // Dispose the created session object
          ruleSession.Dispose();
}

```
I believe, getting this error in second pass of the loop and may be because of the call to  "ruleSession.Dispose();" which might be stopping all the sessions!! Not sure though. Any help is much appreciated.

20/08/14 23:31:57 ERROR DotnetBackendHandler: Failed to execute 'newSession' on 'org.apache.spark.sql.SparkSession' with args=()
[2020-08-14T18:01:57.6877102Z] [RR-DESKTOP] [Error] [JvmBridge] JVM method execution failed: Nonstatic method 'newSession' failed for class '6' when called with no arguments
[2020-08-14T18:01:57.6878436Z] [RR-DESKTOP] [Error] [JvmBridge] java.lang.IllegalStateException: **Cannot call methods on a stopped SparkContext.
This stopped SparkContext was created at:**

org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:926)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
java.lang.reflect.Method.invoke(Unknown Source)
org.apache.spark.api.dotnet.DotnetBackendHandler.handleMethodCall(DotnetBackendHandler.scala:145)
org.apache.spark.api.dotnet.DotnetBackendHandler.handleBackendRequest(DotnetBackendHandler.scala:85)
org.apache.spark.api.dotnet.DotnetBackendHandler.channelRead0(DotnetBackendHandler.scala:28)
org.apache.spark.api.dotnet.DotnetBackendHandler.channelRead0(DotnetBackendHandler.scala:23)
io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)

**The currently active SparkContext was created at:**

**(No active SparkContext.)**

        at org.apache.spark.SparkContext.assertNotStopped(SparkContext.scala:100)
        at org.apache.spark.sql.SparkSession.<init>(SparkSession.scala:91)
        at org.apache.spark.sql.SparkSession.newSession(SparkSession.scala:240)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.handleMethodCall(DotnetBackendHandler.scala:145)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.handleBackendRequest(DotnetBackendHandler.scala:85)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.channelRead0(DotnetBackendHandler.scala:28)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.channelRead0(DotnetBackendHandler.scala:23)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)

[2020-08-14T18:01:57.7213497Z] [RR-DESKTOP] [Exception] [JvmBridge] JVM method execution failed: Nonstatic method 'newSession' failed for class '6' when called with no arguments
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)
Exception Message: JVM method execution failed: Nonstatic method 'newSession' failed for class '6' when called with no arguments
 Stack Trace:    at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallNonStaticJavaMethod(JvmObjectReference objectId, String methodName, Object[] args)
   at Microsoft.Spark.Interop.Ipc.JvmObjectReference.Invoke(String methodName, Object[] args)

**Comment by suhsteve** [comment]
The `NewSession`s share the underlying `SparkContext`.  When you call `SparkSession.Dispose`, it is effectively calling `SparkSession.Stop` which in will call `SparkContext.Stop` on the scala side.

**Comment by rrekapalli** [comment]
Gotcha!  Would there anyway to identify the these individual sessions in the Spark WebUI?  I have removed that ruleSession.Dispose(), and re-executed my app.  However, I do not see any difference with my previous attempts without these new sessions.  In other words, I am expecting to see a separate application for each of these new sessions but I see only one.

![image](https://user-images.githubusercontent.com/533433/90282985-fbd43e80-de8c-11ea-8e72-9e1ee2361d40.png)

**Comment by suhsteve** [comment]
Have you tried using the `Builder` to change the names for each `SparkSession` ?

**Comment by Niharikadutta** [comment]
Multiple `SparkSessions` don't mean multiple applications. In Spark, an application is on the level of calling a `spark-submit` command. A `SparkSession` is just the entry point to programming Spark with the `Dataset` and `DataFrame` API. [Here](https://stackoverflow.com/questions/47723761/how-many-sparksessions-can-a-single-application-have) is a good explanation on what having multiple `SparkSessions` means for a developer. That being said, I am not sure there is a way to visualize individual `SparkSessions` in an application on the Spark WebUI. @suhsteve , @imback82  please correct me if I'm mistaken.

**Comment by rrekapalli** [comment]
@suhsteve , yes I have tried with builder() as well like below (but without any luck):
`SparkSession.Builder().AppName(_batchName + " - " + rule.GetMnemonic()).GetOrCreate();`

@Niharikadutta , thank you for sharing the article.  I just came across another article which states it's possible.  [Here](https://www.waitingforcode.com/apache-spark-sql/multiple-sparksession-one-sparkcontext/read)
[https://www.waitingforcode.com/apache-spark-sql/multiple-sparksession-one-sparkcontext/read]

So, as per that article I tried below and again without any luck!

```
 foreach(Rule rule in _rules)
            {
                SparkSession ruleSession = SparkSession.Builder().AppName(_batchName + " - " + rule.GetMnemonic()).GetOrCreate(); 

                SparkSession.SetDefaultSession(ruleSession);

                rule.SetSparkSession(ruleSession, _batchGuid, _batchName + "-" + rule.GetMnemonic());

                rule.SetData(_ruleData);

                if (rule.PreCondition()) ExecuteRule(rule);

                SparkSession.ClearDefaultSession();
                SparkSession.SetDefaultSession(_Spark);
}

```

**Comment by Niharikadutta** [comment]
Are you getting any error with this, or just not able to see the different applications on the UI?

**Comment by rrekapalli** [comment]
Not getting any errors, don't see any new applications on the Web UI. It is executing in a single application as it was without these  new sessions.

**Comment by suhsteve** [comment]
In the link you [are referencing](https://www.waitingforcode.com/apache-spark-sql/multiple-sparksession-one-sparkcontext/read) at the bottom you can see that even if they have multiple spark sessions, it will only show up as one App in the UI.  

*"Notice however that SparkSession encapsulates SparkContext and since by default we can have only 1 context per JVM, all the SparkSessions from above example are **represented in the UI within a single one application - usually the first launched**."*

**Comment by rrekapalli** [comment]
That's correct. Sorry I missed it!  I think he has done it with multi thread model to simulate multiple applications. Which might not work for my use case.  I wonder how the notebooks (like Jupyter/databricks) are being implemented!  Any suggestions?

**Comment by Niharikadutta** [comment]
If it is your intention to spin up multiple different applications, you will have to do that by calling `spark-submit` command multiple times as that is responsible for submitting a spark job/application, I don't think there is a way to do that within one submit. As for how notebooks are implemented, you can think of a notebook as an active `spark-shell` (think of it as the interactive counterpart to batch `spark-submit`). Each Spark shell session also corresponds to one application. Hope that helps!

**Comment by rrekapalli** [comment]
Thank you, Steve & Niharika!  I guess I need a bit more control on how to create at least jobs with a Spark Session. Otherwise, my DAG is becoming so huge and taking around 12 mins to process a mere 8 million rows (just a few queries with filters, aggregations & couple of joins). If there's way to create jobs then I can create a pipeline for each such filter/aggregation/join queries in a separate jobs.

**Comment by rrekapalli** [comment]
Closing the issue. Thank you for all your support and suggestions, Guys!
