### ISSUE TITLE
[BUG]:  Failed to load org.apache.spark.deploy.dotnet.DotnetRunner. java.lang.ClassNotFoundException: org.apache.spark.deploy.dotnet.DotnetRunner   Developing .NET for Spark Applications on cluster

### ISSUE THREAD

**Issue by hihihihiwsf** [dotnet/spark#663]
**Describe the bug**
There are some errors when I submitted a spark job to cluster while it can work well in local. My job is submitted to Bing MT.
The returned results is:

`Picked up JAVA_TOOL_OPTIONS: -Dhadoop.root.logger.level=INFO -Dhadoop.root.logger.dest=console -Djava.security.krb5.conf=D:\data\java.latest\krb5.conf
log4j:WARN Continuable parsing error 2 and column 69
log4j:WARN Document root element "log4j:configuration", must match DOCTYPE root "null".
log4j:WARN Continuable parsing error 2 and column 69
log4j:WARN Document is invalid: no grammar found.
log4j:ERROR No appender named [] could be found.
Warning: Ignoring non-spark config property: hadoop.log.dir=${spark.yarn.app.container.log.dir}
i,09/09/2020 01:51:42,Common,CommonLibMain,SrcFile="main.cpp" SrcFunc="apsdk::CommonInit" SrcLine="103" Pid="17920" Tid="488" TS="0x01D6868670558C77" String1="CommonInit called at 2020-09-09T01:51:42.240L+7h, applicationDir=(null), defaultConfigName=(null), bootstrapConfigDir=d:\app"
i,09/09/2020 01:51:42,Common,Configuration,SrcFile="Configuration.cpp" SrcFunc="apsdk::configuration::Configuration::PreInitialize" SrcLine="146" Pid="17920" Tid="488" TS="0x01D6868670558C77" String1="CConfiguration::Preinitialize called at 2020-09-09T01:51:42.240L+7h"
i,09/09/2020 01:51:42,Common,ConfigurationManager,SrcFile="ConfigurationManager.cpp" SrcFunc="apsdk::configuration::ConfigurationManager::ProcessOverrides" SrcLine="268" Pid="17920" Tid="488" TS="0x01D6868670558C77" String1="Processing overrides at 2020-09-09T01:51:42.240L+7h"
i,09/09/2020 01:51:42,Common,ConfigurationCollection,SrcFile="ConfigurationCollection.cpp" SrcFunc="apsdk::configuration::internal::ConfigurationCollection::Init" SrcLine="114" Pid="17920" Tid="488" TS="0x01D6868670558C77" String1="unable to read configuration file D:\data\brs\brs.ini"
i,09/09/2020 01:51:42,Common,ConfigurationCollection,SrcFile="ConfigurationCollection.cpp" SrcFunc="apsdk::configuration::internal::ConfigurationCollection::Init" SrcLine="114" Pid="17920" Tid="488" TS="0x01D6868670558C77" String1="unable to read configuration file D:\data\brs\GlobalBrs.ini"
i,09/09/2020 01:51:42,Common,ChangeNotify,SrcFile="changenotify.cpp" SrcFunc="apsdk::ChangeNotifier::Init" SrcLine="87" Pid="17920" Tid="488" TS="0x01D6868670558C77" String1="First ChangeNotifier::Init called at 2020-09-09T01:51:42.240L+7h; ScanIntervalMSec=1000, MainLoopSleepIntervalMSec=100"
i,09/09/2020 01:51:42,Common,Configuration,SrcFile="Configuration.cpp" SrcFunc="apsdk::configuration::Configuration::CompleteInitialize" SrcLine="191" Pid="17920" Tid="488" TS="0x01D6868670558C77" String1="Configuration::CompleteInitialize called at 2020-09-09T01:51:42.240L+7h"
i,09/09/2020 01:51:42,Common,SysInfo::Init,SrcFile="sysinfo.cpp" SrcFunc="apsdk::SysInfo::Init" SrcLine="540" Pid="17920" Tid="488" TS="0x01D686867057EEC8" String1="Initializing SysInfo at 2020-09-09T01:51:42.255L+7h"
i,09/09/2020 01:51:42,Counters,Percentiles,SrcFile="counters.cpp" SrcFunc="apsdk::Counters::ReadTruePercentilesCountersConfiguration" SrcLine="2328" Pid="17920" Tid="488" TS="0x01D68686705A5165" String1="support true percentiles = 0, counters = , counters created = 0"
20/09/09 01:51:42 WARN [main] alias.APSecretStoreProvider: Cannot get credential for spark.ssl.trustStorePassword, D:\data\ASG_MTP\APSecretStoreCredentials\spark.ssl.trustStorePassword.encr file does not exist.
20/09/09 01:51:42 WARN [main] deploy.SparkSubmit$$anon$2: Failed to load org.apache.spark.deploy.dotnet.DotnetRunner.
java.lang.ClassNotFoundException: org.apache.spark.deploy.dotnet.DotnetRunner
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.apache.spark.util.Utils$.classForName(Utils.scala:238)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:809)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:923)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:932)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
20/09/09 01:51:42 INFO [shutdown-hook-0] util.ShutdownHookManager: Shutdown hook called
20/09/09 01:51:42 INFO [shutdown-hook-0] util.ShutdownHookManager: Deleting directory C:\Windows\Temp\spark-eb5546a8-40d4-4050-a711-0f2d15f4c1e6
20/09/09 01:51:42 ERROR [shutdown-hook-0] util.ShutdownHookManager: Exception while deleting Spark temp dir: C:\Windows\Temp\spark-eb5546a8-40d4-4050-a711-0f2d15f4c1e6
java.io.IOException: Failed to delete: C:\Windows\Temp\spark-eb5546a8-40d4-4050-a711-0f2d15f4c1e6\structuredstreamforspark_2.11-2.3.0-1.1.7.jar
        at org.apache.spark.network.util.JavaUtils.deleteRecursivelyUsingJavaIO(JavaUtils.java:144)
        at org.apache.spark.network.util.JavaUtils.deleteRecursively(JavaUtils.java:118)
        at org.apache.spark.network.util.JavaUtils.deleteRecursivelyUsingJavaIO(JavaUtils.java:128)
        at org.apache.spark.network.util.JavaUtils.deleteRecursively(JavaUtils.java:118)
        at org.apache.spark.network.util.JavaUtils.deleteRecursively(JavaUtils.java:91)
        at org.apache.spark.util.Utils$.deleteRecursively(Utils.scala:1062)
        at org.apache.spark.util.ShutdownHookManager$$anonfun$1$$anonfun$apply$mcV$sp$3.apply(ShutdownHookManager.scala:65)
        at org.apache.spark.util.ShutdownHookManager$$anonfun$1$$anonfun$apply$mcV$sp$3.apply(ShutdownHookManager.scala:62)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at org.apache.spark.util.ShutdownHookManager$$anonfun$1.apply$mcV$sp(ShutdownHookManager.scala:62)
        at org.apache.spark.util.SparkShutdownHook.run(ShutdownHookManager.scala:216)
        at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ShutdownHookManager.scala:188)
        at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1$$anonfun$apply$mcV$sp$1.apply(ShutdownHookManager.scala:188)
        at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1$$anonfun$apply$mcV$sp$1.apply(ShutdownHookManager.scala:188)
        at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1966)
        at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1.apply$mcV$sp(ShutdownHookManager.scala:188)
        at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1.apply(ShutdownHookManager.scala:188)
        at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1.apply(ShutdownHookManager.scala:188)
        at scala.util.Try$.apply(Try.scala:192)
        at org.apache.spark.util.SparkShutdownHookManager.runAll(ShutdownHookManager.scala:188)
        at org.apache.spark.util.SparkShutdownHookManager$$anon$2.run(ShutdownHookManager.scala:178)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Picked up JAVA_TOOL_OPTIONS: -Dhadoop.root.logger.level=INFO -Dhadoop.root.logger.dest=console -Djava.security.krb5.conf=D:\data\java.latest\krb5.conf 
`

**To Reproduce**
My spark command submitted to cluster is:
`spark-submit.cmd \
--jars hdfs://BN2-4/user/t-sifwu/kafkaspark_test/spark-sql-kafka-0-10_2.11-2.3.1.jar \
--class org.apache.spark.deploy.dotnet.DotnetRunner \
--conf spark.yarn.appMasterEnv.DOTNET_WORKER_DIR=.\worker\Microsoft.Spark.Worker-0.4.0 \
--conf spark.yarn.appMasterEnv.DOTNET_ASSEMBLY_SEARCH_PATHS=.\udfs\Debug\net472 \
hdfs://BN2-4/user/t-sifwu/kafkaspark_test/structuredstreamforspark_2.11-2.3.0-1.1.7.jar \
--archives hdfs://BN2-4/user/t-sifwu/kafkaspark_test/Microsoft.Spark.Worker.net461.win-x64-0.4.0.zip#worker,hdfs://BN2-4/user/t-sifwu/kafkaspark_test/Debug.zip#udfs \
--master yarn \
--deploy-mode cluster \
hdfs://BN2-4/user/t-sifwu/kafkaspark_test/microsoft-spark-2.3.x-0.4.0.jar \
hdfs://BN2-4/user/t-sifwu/kafkaspark_test/Debug.zip sparkcsharp.exe`

**Comment by Niharikadutta** [comment]
In your `spark-submit` command, are you trying to also pass the `hdfs://BN2-4/user/t-sifwu/kafkaspark_test/structuredstreamforspark_2.11-2.3.0-1.1.7.jar` file through the `--jars` option? If that is so, please add that right after the `sql-kafka` file separated by a comma, otherwise spark thinks you are trying to find the class `org.apache.spark.deploy.dotnet.DotnetRunner` in that jar file instead of the `microsoft-spark` jar file. 
Additionally, please note that if you want to pass jar files that are needed by your application as runtime dependencies, you would need to use the `spark.driver/executor.extraClassPath` configs to point to those jars paths.

**Comment by Niharikadutta** [comment]
@hihihihiwsf Are you still facing this issue?

**Comment by hihihihiwsf** [comment]
> @hihihihiwsf Are you still facing this issue?

yes, this issue has not occurred.
