### ISSUE TITLE
[BUG]: class "org.apache.spark.internal.config.Dotnet$"'s signer information does not match signer information of other classes in the same package

### ISSUE THREAD

**Issue by zbills** [dotnet/spark#751]
**Describe the bug**
Exception in thread "DotnetBackend" java.lang.SecurityException: class "org.apache.spark.internal.config.Dotnet$"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:892)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:662)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:755)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at org.apache.spark.api.dotnet.DotnetBackend.init(DotnetBackend.scala:36)
	at org.apache.spark.deploy.dotnet.DotnetRunner$$anon$1.run(DotnetRunner.scala:102)
**To Reproduce**
Azure HDInsight cluster,
Using Scala version 2.11.12, OpenJDK 64-Bit Server VM, 1.8.0_262
Branch Clearlake/Releases/hdi-2.4.4

Dotnet spark:
Microsoft.Spark.Worker.netcoreapp3.1.linux-x64-1.0.0.tar.gz
microsoft.spark.1.0.0.nupkg 

I checked the log of microsoft-spark-*jar loaded, the following is the only one ( I am so confused where the conflict coming from) 

[Loaded org.apache.spark.deploy.dotnet.DotnetRunner from file:/usr/hdp/4.1.0.26/spark2/jars/microsoft-spark-2-4_2.11-1.0.0.jar]

If you think the bug depends on external factors (e.g., dataset), please provide us with a minimal reproducible example that consists of the following items:

- a minimal dataset, necessary to reproduce the error
- the minimal runnable code necessary to reproduce the error, which can be run on the given dataset
- the necessary information on any used packages, .NET runtime version, and system it is run on
- in the case of random processes, a seed for reproducibility

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/64989707/96953122-34078700-14a5-11eb-92a1-8967199529a8.png)

![image](https://user-images.githubusercontent.com/64989707/96953073-1cc89980-14a5-11eb-9812-ffebeae9887d.png)

**Additional context**
Thank you

**Comment by imback82** [comment]
Thanks @zbills for reporting this. I think this is a valid bug, and I am looking into this.

**Comment by rapoth** [comment]
CC: @suhsteve

**Comment by imback82** [comment]
@zbills I created a PR to address the issue: #752. Meanwhile, could you use the attached JAR to unblock yourself? (I created this based off the PR + updated the version to 1.0.1). Thanks! (Please let me know if it doesn't address the issue.)

[microsoft-spark-2-4_2.11-1.0.1.zip](https://github.com/dotnet/spark/files/5427231/microsoft-spark-2-4_2.11-1.0.1.zip)

**Comment by elvaliuliuliu** [comment]
I have tested the `microsoft-spark-2-4_2.11-1.0.1.jar` provided by @imback82. It works fine on HDI cluster. @zbills Please try the new jar and let us know if the issue still occurs. Thanks!

**Comment by zbills** [comment]
> @zbills I created a PR to address the issue: #752. Meanwhile, could you use the attached JAR to unblock yourself? (I created this based off the PR + updated the version to 1.0.1). Thanks! (Please let me know if it doesn't address the issue.)
> 
> [microsoft-spark-2-4_2.11-1.0.1.zip](https://github.com/dotnet/spark/files/5427231/microsoft-spark-2-4_2.11-1.0.1.zip)

Yes, it's working now. Thank you

**Comment by zbills** [comment]
Yes, it's working now. Thank you for the quick response @imback82
