### ISSUE TITLE
[BUG]: Cannot call read.parquet on Spark 2.4.4

### ISSUE THREAD

**Issue by akamor** [dotnet/spark#772]
**Describe the bug**

Calling _sparkSession.Read().Parquet(tablePath) on an EMR 5.28.0 using Spark 2.4.4 causes an exception.  This exception does not on Spark 3.0.

We are currently using v1.0.0 of dotnet+spark.  This issue did not occur before we upgraded from v0.12.1.

**To Reproduce**

Using data in S3 the above function calls throws an exception.  The stack trace is below.  The reason appears to be that dotnet+spark is trying to invoke the "read" method from the class org.apache.spark.sql.execution.datasources.v2.FileDataSourceV2.  This class, however, was not available in Spark 2.4.4 (nor does it appear to be available until Spark 3).

[2020-11-11T01:11:14.4734209Z] [ip-172-31-92-64] [Exception] [JvmBridge] JVM method execution failed: Nonstatic method 'parquet' failed for class '14' when called with 1 arguments ([Index=1, Type=String[], Value=System.String[]], )
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args) in C:\Users\adam\Repos\spark\src\csharp\Microsoft.Spark\Interop\Ipc\JvmBridge.cs:line 245
Unhandled exception. System.Exception: JVM method execution failed: Nonstatic method 'parquet' failed for class '14' when called with 1 arguments ([Index=1, Type=String[], Value=System.String[]], )
 ---> Microsoft.Spark.JvmException: java.lang.NoClassDefFoundError: org/apache/spark/sql/execution/datasources/v2/FileDataSourceV2
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:43)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:247)
	at scala.collection.TraversableLike$class.filter(TraversableLike.scala:259)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:630)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:194)
	at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:644)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.api.dotnet.DotnetBackendHandler.handleMethodCall(DotnetBackendHandler.scala:159)
	at org.apache.spark.api.dotnet.DotnetBackendHandler$$anonfun$handleBackendRequest$1.apply$mcV$sp(DotnetBackendHandler.scala:99)
	at org.apache.spark.api.dotnet.ThreadPool$$anon$1.run(ThreadPool.scala:34)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.execution.datasources.v2.FileDataSourceV2
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 39 more

**Desktop (please complete the following information):**
 - OS: Linux
 - Version Using v1.0.0 of dotnet+spark on a Spark 2.4.4 Spark Cluster running on AWS EMR.

**Comment by imback82** [comment]
> Using data in S3 the above function calls throws an exception. The stack trace is below. The reason appears to be that dotnet+spark is trying to invoke the "read" method from the class org.apache.spark.sql.execution.datasources.v2.FileDataSourceV2. This class, however, was not available in Spark 2.4.4 (nor does it appear to be available until Spark 3).

From the .NET Spark side, it just calls `DataFrameReader.parquet` as you can see from the call stack you shared:
```
at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:644)
```

Seems like v2 datasource is being used by default in your Spark distro (usually, v1 datasource is used by default). Can you double check on your side?

**Comment by akamor** [comment]
@imback82 Thanks for fast reply.

Are you asking if the Spark distro is using v1 or v2 Datasource API?  If so, how do I check that?

**Comment by imback82** [comment]
From the callstack, it appears that your Spark distro cannot find `org.apache.spark.sql.execution.datasources.v2.FileDataSourceV2` while looking up data source (`lookupDataSource`). I don't have a visibility to Spark distro in Amazon EMR, so not sure what's happening.

Can you quickly check this in Scala? (`spark.read.parquet("/data_location")`)

**Comment by akamor** [comment]
I understand your point now.  Thanks for clarifying.

When I run spark.read.parquet(...) directly from spark-shell on EMR 5.28.0 with Spark 2.4.4 I get the same error.

**Comment by akamor** [comment]
When running it on EMR 6 with Spark 3 no such error occurs.

**Comment by akamor** [comment]
Looks like this problem is entirely on my side.

For anyone that encounters this in the future I've narrowed the problem down to a package I was importing when calling spark-shell and spark-submit which was incorrectly referencing spark3 (even when called on a spark 2 cluster).

Thanks @imback82 and sorry for the noise.

**Comment by imback82** [comment]
No problem!
