### ISSUE TITLE
[BUG]: Error when trying to process multiple csv files using Spark 2.4.1.

### ISSUE THREAD

**Issue by luciantimar** [dotnet/spark#774]
When version 2.4.1 of Spark is used the read multiple CSV files and exception is generated and csv processing is stoped. 
If a single file is provided then the execution finishes successfully.
I have tried also to use `Format("csv")` and the `Load `method but the exception is similar.

[JvmBridge] JVM method execution failed: Nonstatic method 'csv' failed for class '7' when called with 1 arguments

Is there something that I missed?

The same code is working fine with Spark 3.0.1

**To Reproduce**
 - OS: Windows 10
 - Version 1809
 - Microsoft.Spark.Worker-1.0.0
 - spark-2.4.1-bin-hadoop2.7
 - .Net Core 3.1

Build and run the following code.
```
SparkSession spark = SparkSession
                .Builder()
                .AppName("Sort CSV file")
                .GetOrCreate();
            // Create initial DataFrame
            DataFrame dataFrame =
                spark
                .Read()
                .Option("header", "true")
                .Option("inferSchema", "true")
                .Csv(@"c:\Work\RNP\SocialMedia\Generated\Test\*.csv")
                .PrintSchema()

```
Here is the execution output

%SPARK_HOME%\bin\spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local bin\Debug\netcoreapp3.1\microsoft-spark-2-4_2.11-1.0.0.jar dotnet bin\Debug\netcoreapp3.1\mySparkApp.dll
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/C:/bin/spark-2.4.1-bin-hadoop2.7/jars/spark-unsafe_2.11-2.4.1.jar) to method java.nio.Bits.unaligned()
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
20/11/12 13:17:57 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
20/11/12 13:17:57 INFO DotnetRunner: Starting DotnetBackend with dotnet.
20/11/12 13:17:57 INFO DotnetBackend: The number of DotnetBackend threads is set to 10.
20/11/12 13:17:58 INFO DotnetRunner: Port number used by DotnetBackend is 5353
20/11/12 13:17:58 INFO DotnetRunner: Adding key=spark.jars and value=file:/C:/Work/Spark/mySparkApp/bin/Debug/netcoreapp3.1/microsoft-spark-2-4_2.11-1.0.0.jar to environment
20/11/12 13:17:58 INFO DotnetRunner: Adding key=spark.app.name and value=org.apache.spark.deploy.dotnet.DotnetRunner to environment
20/11/12 13:17:58 INFO DotnetRunner: Adding key=spark.submit.deployMode and value=client to environment
20/11/12 13:17:58 INFO DotnetRunner: Adding key=spark.master and value=local to environment
[2020-11-12T11:17:59.1019224Z] [N-20N3PF1C0NK5] [Info] [ConfigurationService] Using port 5353 for connection.
[2020-11-12T11:17:59.1141437Z] [N-20N3PF1C0NK5] [Info] [JvmBridge] JvMBridge port is 5353
[2020-11-12T11:17:59.1192102Z] [N-20N3PF1C0NK5] [Info] [JvmBridge] The number of JVM backend thread is set to 10. The max number of concurrent sockets in JvmBridge is set to 7.
20/11/12 13:17:59 INFO SparkContext: Running Spark version 2.4.1
20/11/12 13:17:59 INFO SparkContext: Submitted application: Sort CSV file
20/11/12 13:17:59 INFO SecurityManager: Changing view acls groups to:
20/11/12 13:17:59 INFO SecurityManager: Changing modify acls groups to:
20/11/12 13:17:59 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(); groups with view permissions: Set(); users  with modify permissions: Set(); groups with modify permissions: Set()
20/11/12 13:17:59 INFO Utils: Successfully started service 'sparkDriver' on port 5360.
20/11/12 13:17:59 INFO SparkEnv: Registering MapOutputTracker
20/11/12 13:17:59 INFO SparkEnv: Registering BlockManagerMaster
20/11/12 13:17:59 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
20/11/12 13:17:59 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
20/11/12 13:17:59 INFO DiskBlockManager: Created local directory at C:\Users\\AppData\Local\Temp\blockmgr-8202b7e9-e723-4bbb-b228-b97c0817fdd6
20/11/12 13:17:59 INFO MemoryStore: MemoryStore started with capacity 434.4 MB
20/11/12 13:17:59 INFO SparkEnv: Registering OutputCommitCoordinator
20/11/12 13:18:00 INFO Utils: Successfully started service 'SparkUI' on port 4040.
20/11/12 13:18:00 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://host.docker.internal:4040
20/11/12 13:18:00 INFO SparkContext: Added JAR file:/C:/Work/Spark/mySparkApp/bin/Debug/netcoreapp3.1/microsoft-spark-2-4_2.11-1.0.0.jar at spark://host.docker.internal:5360/jars/microsoft-spark-2-4_2.11-1.0.0.jar with timestamp 1605179880112
20/11/12 13:18:00 INFO Executor: Starting executor ID driver on host localhost
20/11/12 13:18:00 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 5373.
20/11/12 13:18:00 INFO NettyBlockTransferService: Server created on host.docker.internal:5373
20/11/12 13:18:00 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
20/11/12 13:18:00 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, host.docker.internal, 5373, None)
20/11/12 13:18:00 INFO BlockManagerMasterEndpoint: Registering block manager host.docker.internal:5373 with 434.4 MB RAM, BlockManagerId(driver, host.docker.internal, 5373, None)
20/11/12 13:18:00 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, host.docker.internal, 5373, None)
20/11/12 13:18:00 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, host.docker.internal, 5373, None)
20/11/12 13:18:00 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir ('file:/C:/Work/Spark/mySparkApp/spark-warehouse/').
20/11/12 13:18:00 INFO SharedState: Warehouse path is 'file:/C:/Work/Spark/mySparkApp/spark-warehouse/'.
20/11/12 13:18:01 INFO StateStoreCoordinatorRef: Registered StateStoreCoordinator endpoint
20/11/12 13:18:02 INFO InMemoryFileIndex: Listing leaf files and directories in parallel under: file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_021055_0_0.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_0_0.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_0_1.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_0_10.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_0_11.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_0_12.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_0_13.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_0_14.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_0_15.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_0_16.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_0_2.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_0_3.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_0_4.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_0_5.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_0_6.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_0_7.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_0_8.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_0_9.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_1_0.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_1_1.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_1_10.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_1_11.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_1_12.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_1_13.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_1_14.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_1_15.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_1_16.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_1_2.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_1_3.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_1_4.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_1_5.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_1_6.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_1_7.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_1_8.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_1_9.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_2_0.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_2_1.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_2_2.csv, file:/c:/Work/RNP/SocialMedia/Generated/Test/Storey_031048_2_3.csv
20/11/12 13:18:02 ERROR DotnetBackendHandler: Failed to execute 'csv' on 'org.apache.spark.sql.DataFrameReader' with args=([Type=scala.collection.mutable.WrappedArray.ofRef, Value: WrappedArray(c:\Work\RNP\SocialMedia\Generated\Test\*.csv)])
[2020-11-12T11:18:02.5798220Z] [N-20N3PF1C0NK5] [Error] [JvmBridge] JVM method execution failed: Nonstatic method 'csv' failed for class '7' when called with 1 arguments ([Index=1, Type=String[], Value=System.String[]], )
[2020-11-12T11:18:02.5799283Z] [N-20N3PF1C0NK5] [Error] [JvmBridge] java.lang.IllegalArgumentException: Unsupported class file major version 55
        at org.apache.xbean.asm6.ClassReader.<init>(ClassReader.java:166)
        at org.apache.xbean.asm6.ClassReader.<init>(ClassReader.java:148)
        at org.apache.xbean.asm6.ClassReader.<init>(ClassReader.java:136)
        at org.apache.xbean.asm6.ClassReader.<init>(ClassReader.java:237)
        at org.apache.spark.util.ClosureCleaner$.getClassReader(ClosureCleaner.scala:49)
        at org.apache.spark.util.FieldAccessFinder$$anon$3$$anonfun$visitMethodInsn$2.apply(ClosureCleaner.scala:517)
        at org.apache.spark.util.FieldAccessFinder$$anon$3$$anonfun$visitMethodInsn$2.apply(ClosureCleaner.scala:500)
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
        at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:134)
        at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:134)
        at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:236)
        at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
        at scala.collection.mutable.HashMap$$anon$1.foreach(HashMap.scala:134)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
        at org.apache.spark.util.FieldAccessFinder$$anon$3.visitMethodInsn(ClosureCleaner.scala:500)
        at org.apache.xbean.asm6.ClassReader.readCode(ClassReader.java:2175)
        at org.apache.xbean.asm6.ClassReader.readMethod(ClassReader.java:1238)
        at org.apache.xbean.asm6.ClassReader.accept(ClassReader.java:631)
        at org.apache.xbean.asm6.ClassReader.accept(ClassReader.java:355)
        at org.apache.spark.util.ClosureCleaner$$anonfun$org$apache$spark$util$ClosureCleaner$$clean$14.apply(ClosureCleaner.scala:307)
        at org.apache.spark.util.ClosureCleaner$$anonfun$org$apache$spark$util$ClosureCleaner$$clean$14.apply(ClosureCleaner.scala:306)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:306)
        at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:162)
        at org.apache.spark.SparkContext.clean(SparkContext.scala:2326)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2100)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2126)
        at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:945)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
        at org.apache.spark.rdd.RDD.collect(RDD.scala:944)
        at org.apache.spark.sql.execution.datasources.InMemoryFileIndex$.bulkListLeafFiles(InMemoryFileIndex.scala:237)
        at org.apache.spark.sql.execution.datasources.InMemoryFileIndex.listLeafFiles(InMemoryFileIndex.scala:126)
        at org.apache.spark.sql.execution.datasources.InMemoryFileIndex.refresh0(InMemoryFileIndex.scala:91)
        at org.apache.spark.sql.execution.datasources.InMemoryFileIndex.<init>(InMemoryFileIndex.scala:67)
        at org.apache.spark.sql.execution.datasources.DataSource.org$apache$spark$sql$execution$datasources$DataSource$$createInMemoryFileIndex(DataSource.scala:533)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:371)
        at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
        at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:615)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.handleMethodCall(DotnetBackendHandler.scala:159)
        at org.apache.spark.api.dotnet.DotnetBackendHandler$$anonfun$handleBackendRequest$1.apply$mcV$sp(DotnetBackendHandler.scala:99)
        at org.apache.spark.api.dotnet.ThreadPool$$anon$1.run(ThreadPool.scala:34)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

[2020-11-12T11:18:02.6229045Z] [N-20N3PF1C0NK5] [Exception] [JvmBridge] JVM method execution failed: Nonstatic method 'csv' failed for class '7' when called with 1 arguments ([Index=1, Type=String[], Value=System.String[]], )
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)
Unhandled exception. System.Exception: JVM method execution failed: Nonstatic method 'csv' failed for class '7' when called with 1 arguments ([Index=1, Type=String[], Value=System.String[]], )
 ---> Microsoft.Spark.JvmException: java.lang.IllegalArgumentException: Unsupported class file major version 55
        at org.apache.xbean.asm6.ClassReader.<init>(ClassReader.java:166)
        at org.apache.xbean.asm6.ClassReader.<init>(ClassReader.java:148)
        at org.apache.xbean.asm6.ClassReader.<init>(ClassReader.java:136)
        at org.apache.xbean.asm6.ClassReader.<init>(ClassReader.java:237)
        at org.apache.spark.util.ClosureCleaner$.getClassReader(ClosureCleaner.scala:49)
        at org.apache.spark.util.FieldAccessFinder$$anon$3$$anonfun$visitMethodInsn$2.apply(ClosureCleaner.scala:517)
        at org.apache.spark.util.FieldAccessFinder$$anon$3$$anonfun$visitMethodInsn$2.apply(ClosureCleaner.scala:500)
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
        at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:134)
        at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:134)
        at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:236)
        at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
        at scala.collection.mutable.HashMap$$anon$1.foreach(HashMap.scala:134)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
        at org.apache.spark.util.FieldAccessFinder$$anon$3.visitMethodInsn(ClosureCleaner.scala:500)
        at org.apache.xbean.asm6.ClassReader.readCode(ClassReader.java:2175)
        at org.apache.xbean.asm6.ClassReader.readMethod(ClassReader.java:1238)
        at org.apache.xbean.asm6.ClassReader.accept(ClassReader.java:631)
        at org.apache.xbean.asm6.ClassReader.accept(ClassReader.java:355)
        at org.apache.spark.util.ClosureCleaner$$anonfun$org$apache$spark$util$ClosureCleaner$$clean$14.apply(ClosureCleaner.scala:307)
        at org.apache.spark.util.ClosureCleaner$$anonfun$org$apache$spark$util$ClosureCleaner$$clean$14.apply(ClosureCleaner.scala:306)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:306)
        at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:162)
        at org.apache.spark.SparkContext.clean(SparkContext.scala:2326)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2100)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2126)
        at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:945)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
        at org.apache.spark.rdd.RDD.collect(RDD.scala:944)
        at org.apache.spark.sql.execution.datasources.InMemoryFileIndex$.bulkListLeafFiles(InMemoryFileIndex.scala:237)
        at org.apache.spark.sql.execution.datasources.InMemoryFileIndex.listLeafFiles(InMemoryFileIndex.scala:126)
        at org.apache.spark.sql.execution.datasources.InMemoryFileIndex.refresh0(InMemoryFileIndex.scala:91)
        at org.apache.spark.sql.execution.datasources.InMemoryFileIndex.<init>(InMemoryFileIndex.scala:67)
        at org.apache.spark.sql.execution.datasources.DataSource.org$apache$spark$sql$execution$datasources$DataSource$$createInMemoryFileIndex(DataSource.scala:533)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:371)
        at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
        at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:615)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.handleMethodCall(DotnetBackendHandler.scala:159)
        at org.apache.spark.api.dotnet.DotnetBackendHandler$$anonfun$handleBackendRequest$1.apply$mcV$sp(DotnetBackendHandler.scala:99)
        at org.apache.spark.api.dotnet.ThreadPool$$anon$1.run(ThreadPool.scala:34)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

   --- End of inner exception stack trace ---
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object arg0)
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallNonStaticJavaMethod(JvmObjectReference objectId, String methodName, Object arg0)
   at Microsoft.Spark.Interop.Ipc.JvmObjectReference.Invoke(String methodName, Object arg0)
   at Microsoft.Spark.Sql.DataFrameReader.LoadSource(String source, String[] paths)
   at Microsoft.Spark.Sql.DataFrameReader.Csv(String[] paths)
   at MySparkApp.Program.Main(String[] args) in C:\Work\Spark\mySparkApp\Program.cs:line 26
20/11/12 13:18:04 INFO DotnetRunner: Closing DotnetBackend
20/11/12 13:18:04 INFO SparkContext: Invoking stop() from shutdown hook
20/11/12 13:18:04 INFO SparkUI: Stopped Spark web UI at http://host.docker.internal:4040
20/11/12 13:18:04 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
20/11/12 13:18:04 INFO MemoryStore: MemoryStore cleared
20/11/12 13:18:04 INFO BlockManager: BlockManager stopped
20/11/12 13:18:04 INFO BlockManagerMaster: BlockManagerMaster stopped
20/11/12 13:18:04 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
20/11/12 13:18:04 INFO SparkContext: Successfully stopped SparkContext
20/11/12 13:18:04 INFO ShutdownHookManager: Shutdown hook called
20/11/12 13:18:04 INFO ShutdownHookManager: Deleting directory C:\Users\\AppData\Local\Temp\spark-2158bc87-a87c-4b39-8a57-32724b1a9041
20/11/12 13:18:04 INFO ShutdownHookManager: Deleting directory C:\Users\\AppData\Local\Temp\spark-9023a23c-00eb-41ea-93fd-572ddfe26073

**Comment by luciantimar** [comment]
A small update may help.
The issue is reproduced only there are more than 32 files in that folder, each file with approx 1 mil lines

**Comment by imback82** [comment]
If you see `Unsupported class file`, it usually means the mismatch of Java versions. Can you share the Java version you are using? Note that Spark 2.4 only supports Java 8.

**Comment by luciantimar** [comment]
Hi, 
I had Java 11 installed.

With Java 8 works.

Anyway, what confused me was that if the folder contains less than 32 files, everything worked even with Java 11.

Thank you.

**Comment by imback82** [comment]
> Anyway, what confused me was that if the folder contains less than 32 files, everything worked even with Java 11.

Different code path - compatible with Java 11 - must have been taken.
