### ISSUE TITLE
[QUESTION]: How to use SparkSession.ExecuteCommand

### ISSUE THREAD

**Issue by this-fifo** [dotnet/spark#785]
I have found this page in the [documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.spark.sql.sparksession.executecommand?view=spark-dotnet) but I would like to know how to use it

I have tried doing the following example:

```csharp
var optionsDictionary = new Dictionary<string, string>
        {
            {"driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver"},
            {"jdbcUrl", $"jdbc:sqlserver://{server};database={db};user={user};password={password}"}
        };
_sparkSession.ExecuteCommand("runner", $"DROP TABLE {temporaryTable};", optionsDictionary);
```

StackTrace:
```
System.Exception: JVM method execution failed: Nonstatic method 'executeCommand' failed for class '6' when called with 3 arguments ([Index=1, Type=String, Value=runner], [Index=2, Type=String, Value=DROP TABLE TemporaryTable;], [Index=3, Type=Dictionary`2, Value=System.Collections.Generic.Dictionary`2[System.String,System.String]], )
 ---> Microsoft.Spark.JvmException
   --- End of inner exception stack trace ---
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallNonStaticJavaMethod(JvmObjectReference objectId, String methodName, Object[] args)
   at Microsoft.Spark.Interop.Ipc.JvmObjectReference.Invoke(String methodName, Object[] args)
   at Microsoft.Spark.Sql.SparkSession.ExecuteCommand(String runner, String command, Dictionary`2 options)
```

**Comment by imback82** [comment]
Can you share the full log please?

**Comment by this-fifo** [comment]
Sure, here's the full stack trace

```
System.AggregateException: One or more errors occurred. (JVM method execution failed: Nonstatic method 'executeCommand' failed for class '6' when called with 3 arguments ([Index=1, Type=String, Value=runner], [Index=2, Type=String, Value=DROP TABLE TemporaryTable;], [Index=3, Type=Dictionary`2, Value=System.Collections.Generic.Dictionary`2[System.String,System.String]], ))
 ---> System.Exception: JVM method execution failed: Nonstatic method 'executeCommand' failed for class '6' when called with 3 arguments ([Index=1, Type=String, Value=runner], [Index=2, Type=String, Value=DROP TABLE TemporaryTable;], [Index=3, Type=Dictionary`2, Value=System.Collections.Generic.Dictionary`2[System.String,System.String]], )
 ---> Microsoft.Spark.JvmException
   --- End of inner exception stack trace ---
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallNonStaticJavaMethod(JvmObjectReference objectId, String methodName, Object[] args)
   at Microsoft.Spark.Interop.Ipc.JvmObjectReference.Invoke(String methodName, Object[] args)
   at Microsoft.Spark.Sql.SparkSession.ExecuteCommand(String runner, String command, Dictionary`2 options)
   at System.Threading.CancellationToken.<>c.<.cctor>b__26_0(Object obj)
   at System.Threading.CancellationTokenSource.CallbackNode.<>c.<ExecuteCallback>b__9_0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.CancellationTokenSource.CallbackNode.ExecuteCallback()
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at System.Threading.CancellationTokenSource.NotifyCancellation(Boolean throwOnFirstException)
   at System.Threading.CancellationTokenSource.Cancel(Boolean throwOnFirstException)
   at Microsoft.Extensions.Hosting.Internal.ApplicationLifetime.ExecuteHandlers(CancellationTokenSource cancel)
   at Microsoft.Extensions.Hosting.Internal.ApplicationLifetime.NotifyStarted()
```

**Comment by imback82** [comment]
Do you have a `runner` class that implements `ExternalCommandRunner` on the JVM side?

**Comment by this-fifo** [comment]
Ah, so that's how you use it? I knew I was doing something wrong, I certainly did not implement an `ExternalCommandRunner` JVM class 🙈

Thank you for the explanation @imback82 , I certainly did not pay attention to that and was expecting it to be way too high level of an abstraction for anyone's taste 😅

**Comment by rajeev99342** [comment]
Hi @this-fifo, Can you please provide me the example piece of code for runner class that implements ExternalCommandRunner?

**Comment by this-fifo** [comment]
Hey @rajeev99342, unfortunately I don't have access to that anymore, it was a prototype / test project and I ended up taking a different approach without needing to rely on `ExternalCommandRunner` after

**Comment by rajeev99342** [comment]
Hi @this-fifo. No problem man. Thanks WTB
