### ISSUE TITLE
[BUG]: .NET Spark with udf not works on AWS EMR

### ISSUE THREAD

**Issue by KimKiHyuk** [dotnet/spark#786]
**Describe the bug**

my app(emrApp) contains udf function (not external file, just built in)
when i tried to execute it in local, it works well
```
export DOTNET_ASSEMBLY_SEARCH_PATHS=./emrApp/
spark-submit --packages org.apache.spark:spark-avro_2.11:2.4.6 --class org.apache.spark.deploy.dotnet.DotnetRunner --master local ./bin/Release/netcoreapp3.1/ubuntu.16.04-x64/publish/microsoft-spark-2-4_2.11-1.0.0.jar emrApp.zip emrApp <args> <args>
```

but when i tried it on AWS EMR with
```
 'HadoopJarStep': {
                'Jar': 'command-runner.jar',
                'Args': [
                    'spark-submit',
                    '--packages',
                    'org.apache.spark:spark-avro_2.11:2.4.6', 
                    '--class',
                    'org.apache.spark.deploy.dotnet.DotnetRunner',
                    '--master',
                    'yarn',
                    '--conf',
                    'spark.yarn.appMasterEnv.DOTNET_ASSEMBLY_SEARCH_PATHS=./emrApp/',   // and also i tried .
                    '<spark jar in s3>',
                    '<emrApp.zip in s3>',
                    'emrApp',
                    'args', 
                    'args'
        }
```
stderr said 
```
20/11/29 05:19:50 INFO TaskSetManager: Lost task 0.1 in stage 0.0 (TID 1) on ip-172-31-3-97.us-east-2.compute.internal, executor 2: org.apache.spark.api.python.PythonException (System.Runtime.Serialization.SerializationException: Unable to find assembly 'emrApp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Runtime.Serialization.Formatters.Binary.BinaryAssemblyInfo.GetAssembly()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetType(BinaryAssemblyInfo assemblyInfo, String name)
   at System.Runtime.Serialization.Formatters.Binary.ObjectMap..ctor(String objectName, String[] memberNames, BinaryTypeEnum[] binaryTypeEnumA, Object[] typeInformationA, Int32[] memberAssemIds, ObjectReader objectReader, Int32 objectId, BinaryAssemblyInfo assemblyInfo, SizedArray assemIdToAssemblyTable)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMapTyped(BinaryObjectWithMapTyped record)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMapTyped(BinaryHeaderEnum binaryHeaderEnum)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(BinaryParser serParser, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, Boolean check)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
   at Microsoft.Spark.Utils.CommandSerDe.GetUdfWrapperDataFromStream(Stream stream, SerializedMode& serializerMode, SerializedMode& deserializerMode, String& runMode) in /_/src/csharp/Microsoft.Spark/Utils/CommandSerDe.cs:line 297
   at Microsoft.Spark.Utils.CommandSerDe.Deserialize[T](Stream stream, SerializedMode& serializerMode, SerializedMode& deserializerMode, String& runMode) in /_/src/csharp/Microsoft.Spark/Utils/CommandSerDe.cs:line 306
   at Microsoft.Spark.Worker.Processor.CommandProcessor.ReadSqlCommands(PythonEvalType evalType, Stream stream) in D:\a\1\s\src\csharp\Microsoft.Spark.Worker\Processor\CommandProcessor.cs:line 188
   at Microsoft.Spark.Worker.Processor.CommandProcessor.ReadSqlCommands(PythonEvalType evalType, Stream stream, Version version) in D:\a\1\s\src\csharp\Microsoft.Spark.Worker\Processor\CommandProcessor.cs:line 101
   at Microsoft.Spark.Worker.Processor.CommandProcessor.Process(Stream stream) in D:\a\1\s\src\csharp\Microsoft.Spark.Worker\Processor\CommandProcessor.cs:line 43
   at Microsoft.Spark.Worker.Processor.PayloadProcessor.Process(Stream stream) in D:\a\1\s\src\csharp\Microsoft.Spark.Worker\Processor\PayloadProcessor.cs:line 82
   at Microsoft.Spark.Worker.TaskRunner.ProcessStream(Stream inputStream, Stream outputStream, Version version, Boolean& readComplete) in D:\a\1\s\src\csharp\Microsoft.Spark.Worker\TaskRunner.cs:line 144) [duplicate 1]
```

I feel it's quite similar with https://github.com/dotnet/spark/issues/615

source code is 
```.cs
using System.Collections.Generic;
using System;

namespace emrApp.Model 
{
    [Serializable]
    internal class RegionModel {
        
        private IDictionary<string, string> convTable; 
        
        public IDictionary<string, string> ConversionTable {
            get { return this.convTable; }
        }

        public RegionModel()
        {
            this.convTable = new Dictionary<string, string>()
            {
                {"0", "Orange"},
                {"1", "Liverpool"},
                {"2", "Brisbane"},
                {"3", "Gold Coast"},
                {"4", "Sunshine Coast"},  
                {"5", "Blue Mountains"},
                {"6", "Newcastle"},
                {"7", "Sydney"},
                {"8", "Griffith"},
                {"9", "Darwin"},
            };
        }
    }
}


using System;
using Microsoft.Spark.Sql;
using static Microsoft.Spark.Sql.Functions;
using emrApp.Model;

namespace emrApp
{
    class Program
    {
        static void Main(string[] args)
        {
            SparkSession spark = SparkSession
                .Builder()
                .AppName("emrApp")
                .GetOrCreate();

            DataFrame dataFrame = spark
                .Read()
                .Format("avro")
                .Load(args[0]);

            RegionModel regionModel = new RegionModel();
            
            Func<Column, Column> udfConvertRegion = Udf<string, string>(
                city => {                    
                    var regionCode = city.Split('_')[1].Substring(0, 1);
                    var convertedRegion = String.Empty; 
                    regionModel.ConversionTable.TryGetValue(regionCode, out convertedRegion);
                    return convertedRegion;
                } // city_23 --> 23 --> 2 --> {2 : Brisbane} --> ** Brisbane **
            );

            dataFrame = dataFrame
                .WithColumn("Region", udfConvertRegion(dataFrame["address.city"]))
                .Drop("orderunits", "address");
            
            dataFrame
                .Coalesce(1)
                .Write()
                .Format("csv")
                .Save($"{args[1]}/{DateTime.UtcNow.ToString("yyyy/MM/dd/hh-mm-ss")}");  
        }
    }
}
```

**To Reproduce**

1. deploy cluster
```
aws --profile key emr create-cluster \
--name "Test cluster" \
--log-uri "log uri" \
--release-label emr-5.31.0 \
--use-default-roles \
--ec2-attributes KeyName=test-key \
--applications Name=Spark \
--instance-count 3 \
--instance-type m4.large \
--bootstrap-actions Path=<s3://install-worker.sh> Name="Install Microsoft.Spark.Worker",\
Args=["aws","s3://<Microsoft.Spark.Worker.netcoreapp3.1.linux-x64-1.0.0.tar.gz>","/usr/local/bin"]

```
2. Add step
```
    step = {
            'Name': 'process-avro-1',
            'ActionOnFailure': 'CONTINUE',
            'HadoopJarStep': {
               'Jar': 'command-runner.jar',
                'Args': [
                    'spark-submit',
                    '--packages',
                    'org.apache.spark:spark-avro_2.11:2.4.6', 
                    '--class',
                    'org.apache.spark.deploy.dotnet.DotnetRunner',
                    '--master',
                    'yarn',
                    '--conf',
                    'spark.yarn.appMasterEnv.DOTNET_ASSEMBLY_SEARCH_PATHS=./emrApp/',   // and also i tried .
                    '<spark jar in s3>',
                    '<emrApp.zip in s3>',
                    'emrApp',
                    'args', 
                    'args'
         }
 }

   action = connection.add_job_flow_steps(JobFlowId=os.environ['job_flow_id'], Steps=[step])
```
3. see error
```
20/11/29 05:19:50 INFO TaskSetManager: Lost task 0.1 in stage 0.0 (TID 1) on ip-172-31-3-97.us-east-2.compute.internal, executor 2: org.apache.spark.api.python.PythonException (System.Runtime.Serialization.SerializationException: Unable to find assembly 'emrApp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Runtime.Serialization.Formatters.Binary.BinaryAssemblyInfo.GetAssembly()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetType(BinaryAssemblyInfo assemblyInfo, String name)
   at System.Runtime.Serialization.Formatters.Binary.ObjectMap..ctor(String objectName, String[] memberNames, BinaryTypeEnum[] binaryTypeEnumA, Object[] typeInformationA, Int32[] memberAssemIds, ObjectReader objectReader, Int32 objectId, BinaryAssemblyInfo assemblyInfo, SizedArray assemIdToAssemblyTable)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMapTyped(BinaryObjectWithMapTyped record)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMapTyped(BinaryHeaderEnum binaryHeaderEnum)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(BinaryParser serParser, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, Boolean check)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
   at Microsoft.Spark.Utils.CommandSerDe.GetUdfWrapperDataFromStream(Stream stream, SerializedMode& serializerMode, SerializedMode& deserializerMode, String& runMode) in /_/src/csharp/Microsoft.Spark/Utils/CommandSerDe.cs:line 297
   at Microsoft.Spark.Utils.CommandSerDe.Deserialize[T](Stream stream, SerializedMode& serializerMode, SerializedMode& deserializerMode, String& runMode) in /_/src/csharp/Microsoft.Spark/Utils/CommandSerDe.cs:line 306
   at Microsoft.Spark.Worker.Processor.CommandProcessor.ReadSqlCommands(PythonEvalType evalType, Stream stream) in D:\a\1\s\src\csharp\Microsoft.Spark.Worker\Processor\CommandProcessor.cs:line 188
   at Microsoft.Spark.Worker.Processor.CommandProcessor.ReadSqlCommands(PythonEvalType evalType, Stream stream, Version version) in D:\a\1\s\src\csharp\Microsoft.Spark.Worker\Processor\CommandProcessor.cs:line 101
   at Microsoft.Spark.Worker.Processor.CommandProcessor.Process(Stream stream) in D:\a\1\s\src\csharp\Microsoft.Spark.Worker\Processor\CommandProcessor.cs:line 43
   at Microsoft.Spark.Worker.Processor.PayloadProcessor.Process(Stream stream) in D:\a\1\s\src\csharp\Microsoft.Spark.Worker\Processor\PayloadProcessor.cs:line 82
   at Microsoft.Spark.Worker.TaskRunner.ProcessStream(Stream inputStream, Stream outputStream, Version version, Boolean& readComplete) in D:\a\1\s\src\csharp\Microsoft.Spark.Worker\TaskRunner.cs:line 144) [duplicate 1]
```

thank you

**Comment by imback82** [comment]
> 20/11/29 05:19:50 INFO TaskSetManager: Lost task 0.1 in stage 0.0 (TID 1) on ip-172-31-3-97.us-east-2.compute.internal, executor 2: org.apache.spark.api.python.PythonException (System.Runtime.Serialization.SerializationException: Unable to find assembly 'emrApp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

Did you deploy `emrApp` to the executors? `--archives` is an option if you are using YARN. Check this doc as well: https://github.com/dotnet/spark/blob/master/docs/deploy-worker-udf-binaries.md#2-parameter-options

**Comment by KimKiHyuk** [comment]
thank you for your reply :)

First, i've tried it but that's not work..
command
```
                    'Jar': 'command-runner.jar',
                    'Args': [
                        'spark-submit',
                        '--packages',
                        'org.apache.spark:spark-avro_2.11:2.4.6', 
                        '--class',
                        'org.apache.spark.deploy.dotnet.DotnetRunner',
                        '--master',
                        'yarn',
                         '--conf',
                        'spark.yarn.appMasterEnv.DOTNET_ASSEMBLY_SEARCH_PATHS=./emrApp',
                        '--archives',
                        's3://emrApp.zip#emrApp', // and also tried without #emrApp
                        's3://microsoft-spark-2-4_2.11-1.0.0.jar',
                        's3://emrApp.zip',
                        'emrApp',
                        's3 args', 
                        's3 args']
```
```
 Cannot run program "--archives": error=2, No such file or directory 
```

i'm following this description
https://docs.microsoft.com/en-us/dotnet/spark/tutorials/amazon-emr-spark-deployment

in docs,
spark-submit \
--master yarn \
--class org.apache.spark.deploy.dotnet.DotnetRunner \
--files <comma-separated list of assemblies that contain UDF definitions, if any> \
s3://mybucket/<some dir>/microsoft-spark-<spark_majorversion-spark_minorversion>_<scala_majorversion.scala_minorversion>-<spark_dotnet_version>.jar \
**s3://myapp.zip** myapp args

my app should be positioned **

**Comment by KimKiHyuk** [comment]
@imback82
Do you mean that include with udf functions name?

like

```cs
 Func<Column, Column> udfConvertRegion = Udf<string, string>(
                city => {                    
                    var regionCode = city.Split('_')[1].Substring(0, 1);
                    var convertedRegion = String.Empty; 
                    regionModel.ConversionTable.TryGetValue(regionCode, out convertedRegion);
                    return convertedRegion;
                } // city_23 --> 23 --> 2 --> {2 : Brisbane} --> ** Brisbane **
            );
```
```
--archives s3://emrApp.zip#udfConvertRegion
```

**Comment by KimKiHyuk** [comment]
> > 20/11/29 05:19:50 INFO TaskSetManager: Lost task 0.1 in stage 0.0 (TID 1) on ip-172-31-3-97.us-east-2.compute.internal, executor 2: org.apache.spark.api.python.PythonException (System.Runtime.Serialization.SerializationException: Unable to find assembly 'emrApp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
> 
> Did you deploy `emrApp` to the executors? `--archives` is an option if you are using YARN. Check this doc as well: https://github.com/dotnet/spark/blob/master/docs/deploy-worker-udf-binaries.md#2-parameter-options

hmm..  log said new error
```
spark-submit --packages org.apache.spark:spark-avro_2.11:2.4.6 \
--class org.apache.spark.deploy.dotnet.DotnetRunner \
--master yarn \
--deploy-mode cluster \
--conf spark.yarn.appMasterEnv.DOTNET_ASSEMBLY_SEARCH_PATHS=./udfs \
--conf spark.yarn.appMasterEnv.DOTNET_WORKER_DIR=./worker/Microsoft.Spark.Worker-1.0.0 \
--archives s3://emrApp.zip#udfs,s3://Microsoft.Spark.Worker.netcoreapp3.1.linux-x64-1.0.0.zip#Worker \
s3://microsoft-spark-2-4_2.11-1.0.0.jar s3://emrApp.zip emrApp s3a://file1 s3a://file2
```
```
20/11/29 07:30:48 ERROR Client: Application diagnostics message: User application exited with status 134
Exception in thread "main" org.apache.spark.SparkException: Application application_1606632402051_0009 finished with failed status
	at org.apache.spark.deploy.yarn.Client.run(Client.scala:1149)
	at org.apache.spark.deploy.yarn.YarnClusterApplication.start(Client.scala:1529)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:853)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:928)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:937)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
20/11/29 07:30:48 INFO ShutdownHookManager: Shutdown hook called
```

**Comment by KimKiHyuk** [comment]
@imback82
 
I read docs that you linked carefully, but i don't get it why should i pass these parameters and how..
I would appreciate it if you would explain under questions.

in the examples, 
`DOTNET_ASSEMBLY_SEARCH_PATHS= ./udfs` , so i've searched my published app has udfs, but there's no file udfs
what kind of string should i pass to DOTNET_ASSEMBLY_SEARCH_PATHS? is it emrApp(my app name) ? or udfs? 

---

`--archives hdfs://<path to your files>/Microsoft.Spark.Worker.net461.win-x64-<version>.zip#worker`
`--conf spark.yarn.appMasterEnv.DOTNET_WORKER_DIR=./worker/Microsoft.Spark.Worker-1.0.0 \`

in my case, i've already installed microsoft.spark.worker via emr bootstapping with installer-worker.sh, 
can i omit this command?


---

thank you
