### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/internal/Logging$class

### ISSUE THREAD

**Issue by ali-khawaja** [dotnet/spark#803]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/run
Operating System: windows

I am trying to run the sample but its giving me NoClassDefFoundError.  

C:\git\spark\mysparkapp1>spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local bin\Debug\net5.0\microsoft-spark-2.4.x-0.10.0.jar dotnet bin\Debug\net5.0\mySparkApp1.dll

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/C:/spark-3.0.1/jars/spark-unsafe_2.12-3.0.1.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/internal/Logging$class
        at org.apache.spark.deploy.dotnet.DotnetRunner$.<init>(DotnetRunner.scala:35)
        at org.apache.spark.deploy.dotnet.DotnetRunner$.<clinit>(DotnetRunner.scala)
        at org.apache.spark.deploy.dotnet.DotnetRunner.main(DotnetRunner.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.internal.Logging$class
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 15 more

C:\git\spark\mysparkapp1>

**Comment by imback82** [comment]
You are using `microsoft-spark-2.4.x-0.10.0.jar` (scala-2.11) against Spark 3.0 (scala-2.12). Can you run it against Spark 2.4 (or upgrade .NET for Apache Spark to 1.0 and use `microsoft-spark-3-0_2.12`)?

**Comment by ali-khawaja** [comment]
my bad. thanks. i realized that after posting.  i updated to the release version for .net for apache spark and it worked fine.

**Comment by andrey-puzyr** [comment]
There is another case when you can see this error. Just want to note it as artifact of my painful debugging)
Check that you spark jars folder doesn't contains other versions of `microsoft-spark-*.jar`, except the version that you use in spark-submit. It may happens if you use copy by wildcard somewhere in your build Dockerfile.

ie if
```
> ls -l #{SPARK_HOME}/jars | grep microsoft-spark-
-rwxr--r-- 1 root root   184514 Mar 30 05:37 microsoft-spark-2-3_2.11-1.1.1.jar
-rwxr--r-- 1 root root   191446 Mar 30 05:37 microsoft-spark-2-4_2.11-1.1.1.jar
-rwxr--r-- 1 root root   104751 Mar 30 05:38 microsoft-spark-3-0_2.12-1.1.1.jar
```
just kill the others!

**Comment by manikumararyas** [comment]
Thanks, @andrey-puzyr. I encountered with the same scenario and your suggestion helped me.
