### ISSUE TITLE
[FEATURE REQUEST]: Support StructArray as a return type in ArrowFunctions.VectorUdf

### ISSUE THREAD

**Issue by imback82** [dotnet/spark#826]
We need to support `StructArray` as a return type in `ArrowFunctions.VectorUdf`.

To repro:
```csharp
Func<Microsoft.Spark.Sql.Column, Microsoft.Spark.Sql.Column, Microsoft.Spark.Sql.Column> udf
  = ArrowFunctions.VectorUdf((Func<BinaryArray, Int32Array, StructArray>) someUDFWrapper);
```
You will get:
```
Unhandled Exception: System.ArgumentException: Apache.Arrow.StructArray is not supported.
   at Microsoft.Spark.Utils.UdfUtils.GetReturnType(Type type)
   at Microsoft.Spark.Sql.Functions.CreateUdf[TResult](String name, Delegate execute, PythonEvalType evalType)
   at Microsoft.Spark.Sql.ArrowFunctions.VectorUdf[T1,T2,TResult](Func`3 udf)
```

**Comment by dbeavon** [comment]
Is this a short-term goal (ie. is it included in "**1:1 API compatibility for Dataframes**")

**Comment by imback82** [comment]
Since we have a workaround using non-arrow UDF, this is not a short-term goal, but let me talk to the team.

cc @suhsteve @rapoth

**Comment by quarkonium3** [comment]
I was trying out ArrowFunctions - discovered I'd need this in my application
