### ISSUE TITLE
[BUG]: org.apache.spark.sql.AnalysisException: Cannot resolve column name

### ISSUE THREAD

**Issue by saravananponnaiah** [dotnet/spark#83]
**Describe the bug**
I am trying work count program and below is the code I am executing,

```
SparkSession spark = SparkSession.Builder().AppName("StructuredNetworkWordCount").GetOrCreate();

DataFrame lines = spark.Read().Text(@"E:\Hadoop\Data\Test.txt");
lines.Show();
DataFrame words = lines.Select(Explode(Split(lines["value"], " "))).Alias("word");
DataFrame wordCounts = words.GroupBy("word").Count();

wordCounts.Show();

```

When I execute, I am getting below error. Could you please help on this.

```
19/05/01 13:21:15 INFO FileScanRDD: Reading File path: file:///E:/Hadoop/Data/Test.txt, range: 0-564, partition values: [empty row]
19/05/01 13:21:15 INFO CodeGenerator: Code generated in 14.437193 ms
19/05/01 13:21:15 INFO Executor: Finished task 0.0 in stage 0.0 (TID 0). 1728 bytes result sent to driver
19/05/01 13:21:15 INFO TaskSetManager: Finished task 0.0 in stage 0.0 (TID 0) in 357 ms on localhost (executor driver) (1/1)
19/05/01 13:21:15 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool
19/05/01 13:21:15 INFO DAGScheduler: ResultStage 0 (showString at <unknown>:0) finished in 0.471 s
19/05/01 13:21:15 INFO DAGScheduler: Job 0 finished: showString at <unknown>:0, took 0.536283 s
+--------------------+
|               value|
+--------------------+
|Of course, you ca...|
+--------------------+

19/05/01 13:21:15 INFO BlockManagerInfo: Removed broadcast_1_piece0 on ASPLAPNAV118.xxxxx.com:64062 in memory (size: 4.0 KB, free: 366.3 MB)
19/05/01 13:21:15 ERROR DotnetBackendHandler: methods:
19/05/01 13:21:15 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.Dataset.limit(int)
19/05/01 13:21:15 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.Dataset.cache()
19/05/01 13:21:15 ERROR DotnetBackendHandler: public long org.apache.spark.sql.Dataset.count()
19/05/01 13:21:15 ERROR DotnetBackendHandler: public java.lang.String org.apache.spark.sql.Dataset.toString()
19/05/01 13:21:15 ERROR DotnetBackendHandler: public boolean org.apache.spark.sql.Dataset.isEmpty()
19/05/01 13:21:15 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.Dataset.join(org.apache.spark.sql.Dataset,scala.collection.Seq)
19/05/01 13:21:15 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.Dataset.join(org.apache.spark.sql.Dataset,scala.collection.Seq,java.lang.String)
19/05/01 13:21:15 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.Dataset.join(org.apache.spark.sql.Dataset,org.apache.spark.sql.Column)
19/05/01 13:21:15 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.Dataset.join(org.apache.spark.sql.Dataset,org.apache.spark.sql.Column,java.lang.String)
19/05/01 13:21:15 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.Dataset.join(org.apache.spark.sql.Dataset,java.lang.String)
19/05/01 13:21:15 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.Dataset.join(org.apache.spark.sql.Dataset)
19/05/01 13:21:15 ERROR DotnetBackendHandler: public org.apache.spark.sql.Column org.apache.spark.sql.Dataset.apply(java.lang.String)
19/05/01 13:21:15 ERROR DotnetBackendHandler: public java.lang.Object org.apache.spark.sql.Dataset.collect()
19/05/01 13:21:15 ERROR DotnetBackendHandler: public org.apache.spark.sql.DataFrameWriter org.apache.spark.sql.Dataset.write()
19/05/01 13:21:15 ERROR DotnetBackendHandler: public org.apache.spark.sql.catalyst.expressions.NamedExpression org.apache.spark.sql.Dataset.resolve(java.lang.String)
19/05/01 13:21:15 ERROR DotnetBackendHandler: public java.lang.Object org.apache.spark.sql.Dataset.first()
19/05/01 13:21:15 ERROR DotnetBackendHandler: public java.lang.Object org.apache.spark.sql.Dataset.head()
19/05/01 13:21:15 ERROR DotnetBackendHandler: public java.lang.Object org.apache.spark.sql.Dataset.head(int)
....
.....
....
19/05/01 13:21:15 ERROR DotnetBackendHandler: public native int java.lang.Object.hashCode()
19/05/01 13:21:15 ERROR DotnetBackendHandler: public final native java.lang.Class java.lang.Object.getClass()
19/05/01 13:21:15 ERROR DotnetBackendHandler: public final native void java.lang.Object.notify()
19/05/01 13:21:15 ERROR DotnetBackendHandler: public final native void java.lang.Object.notifyAll()
19/05/01 13:21:15 ERROR DotnetBackendHandler: args:
19/05/01 13:21:15 ERROR DotnetBackendHandler: argType: java.lang.String, argValue: word
19/05/01 13:21:15 ERROR DotnetBackendHandler: argType: scala.collection.mutable.WrappedArray.ofRef, argValue: WrappedArray()
[2019-05-01T07:51:15.6684168Z] [ASPLAPNAV118] [Error] [JvmBridge] JVM method execution failed: Nonstatic method groupBy failed for class 12 when called with 2 arguments ([Index=1, Type=String, Value=word], [Index=2, Type=String[], Value=System.String[]], )
[2019-05-01T07:51:15.6684616Z] [ASPLAPNAV118] [Error] [JvmBridge] org.apache.spark.sql.AnalysisException: Cannot resolve column name "word" among (col);
        at org.apache.spark.sql.Dataset$$anonfun$resolve$1.apply(Dataset.scala:223)
        at org.apache.spark.sql.Dataset$$anonfun$resolve$1.apply(Dataset.scala:223)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.sql.Dataset.resolve(Dataset.scala:222)
        at org.apache.spark.sql.Dataset$$anonfun$groupBy$2.apply(Dataset.scala:1622)
        at org.apache.spark.sql.Dataset$$anonfun$groupBy$2.apply(Dataset.scala:1622)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at org.apache.spark.sql.Dataset.groupBy(Dataset.scala:1622)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.handleMethodCall(DotnetBackendHandler.scala:162)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.handleBackendRequest(DotnetBackendHandler.scala:102)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.channelRead0(DotnetBackendHandler.scala:29)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.channelRead0(DotnetBackendHandler.scala:24)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)

		....
		....
		
[2019-05-01T07:51:15.6941021Z] [ASPLAPNAV118] [Exception] [JvmBridge] JVM method execution failed: Nonstatic method groupBy failed for class 12 when called with 2 arguments ([Index=1, Type=String, Value=word], [Index=2, Type=String[], Value=System.String[]], )
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args) in D:\a\1\s\src\csharp\Microsoft.Spark\Interop\Ipc\JvmBridge.cs:line 192

Unhandled Exception: System.Exception: JVM method execution failed: Nonstatic method groupBy failed for class 12 when called with 2 arguments ([Index=1, Type=String, Value=word], [Index=2, Type=String[], Value=System.String[]], )
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args) in D:\a\1\s\src\csharp\Microsoft.Spark\Interop\Ipc\JvmBridge.cs:line 192
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object arg0, Object arg1) in D:\a\1\s\src\csharp\Microsoft.Spark\Interop\Ipc\JvmBridge.cs:line 138
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallNonStaticJavaMethod(JvmObjectReference objectId, String methodName, Object arg0, Object arg1) in D:\a\1\s\src\csharp\Microsoft.Spark\Interop\Ipc\JvmBridge.cs:line 94
   at Microsoft.Spark.Sql.DataFrame.GroupBy(String column, String[] columns) in D:\a\1\s\src\csharp\Microsoft.Spark\Sql\DataFrame.cs:line 429
   at NetworkWordCount.Program.Main(String[] args) in D:\Workspace\DotNet\DotNetSpark\NetworkWordCount\NetworkWordCount\Program.cs:line 29
19/05/01 13:21:18 INFO DotnetRunner: Closing DotnetBackend
19/05/01 13:21:18 INFO DotnetBackend: Requesting to close all call back sockets
19/05/01 13:21:18 INFO SparkContext: Invoking stop() from shutdown hook
19
```

**Comment by rapoth** [comment]
@saravananponnaiah: Can you try moving the Alias into the Select? (since you are aliasing the column name and not the output of Select itself).

            DataFrame words = lines.Select(Explode(Split(lines["value"], " ")).Alias("word"));

**Comment by rapoth** [comment]
@saravananponnaiah : I'm closing this for now. Please feel free to re-open if the suggested change does not fix your problem. Thank you!
