### ISSUE TITLE
No connection could be made because the target machine actively refused it. 127.0.0.1:5567

### ISSUE THREAD

**Issue by jhdrosos** [dotnet/spark#931]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/code
Operating System: windows

[Exception] [JvmBridge] No connection could be made because the target machine actively refused it. 127.0.0.1:5567
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at Microsoft.Spark.Network.DefaultSocketWrapper.Connect(IPAddress remoteaddr, Int32 port, String secret)
   at Microsoft.Spark.Interop.Ipc.JvmBridge.GetConnection()
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)

**Comment by imback82** [comment]
@jhdrosos, please check this thread: #175. Closing this as duplicate.
