### ISSUE TITLE
[BUG]: The example spark/examples/Microsoft.Spark.CSharp.Examples/Sql/Batch/VectorUdfs.cs doesnt run with latest spark 3.0. 

### ISSUE THREAD

**Issue by viskumar-microsoft** [dotnet/spark#932]
The example spark/examples/Microsoft.Spark.CSharp.Examples/Sql/Batch/VectorUdfs.cs doesnt run with latest spark 3.0. 

HDI now supports Spark 3.0 and we are trying to migrate our spark dotnet jobs to it and we get similar exception.

https://github.com/dotnet/spark/blob/main/examples/Microsoft.Spark.CSharp.Examples/Sql/Batch/VectorUdfs.cs

spark/examples/Microsoft.Spark.CSharp.Examples/Sql/Batch/VectorUdfs.cs doesnt run using Spark 3.0 scala 2.12. Here is the exception we get

DotnetWorker PID:[58708] Args:[-m pyspark.worker] SparkVersion:[3.0.0]
[2021-05-04T17:27:01.1901724Z] [] [Info] [SimpleWorker] RunSimpleWorker() is starting with port = 49291.
[2021-05-04T17:27:01.2139101Z] [] [Info] [TaskRunner] [0] Starting with ReuseSocket[False].
[2021-05-04T17:27:01.2223162Z] [] [Info] [ConfigurationService] 'DOTNETBACKEND_PORT' environment variable is not set.
[2021-05-04T17:27:01.2223487Z] [] [Info] [ConfigurationService] Using port 5567 for connection.
[2021-05-04T17:27:01.2237232Z] [] [Info] [JvmBridge] JvMBridge port is 5567
[2021-05-04T17:27:01.2261437Z] [] [Info] [JvmBridge] The number of JVM backend thread is set to 10. The max number of concurrent sockets in JvmBridge is set to 7.
21/05/04 10:27:01 INFO CodeGenerator: Code generated in 6.5561 ms
[2021-05-04T17:27:01.3970085Z] [] [Debug] [TaskRunner] [0] Received END_OF_STREAM signal.
[2021-05-04T17:27:01.3971403Z] [] [Info] [TaskRunner] [0] Processed a task: readComplete:True, entries:2
[2021-05-04T17:27:01.3972846Z] [] [Info] [TaskRunner] [0] Waiting for JVM side to close socket.
[2021-05-04T17:27:01.4114444Z] [] [Info] [TaskRunner] [0] JVM side has closed socket.
[2021-05-04T17:27:01.4120392Z] [] [Info] [TaskRunner] [0] Finished running 1 task(s).
[2021-05-04T17:27:01.4120824Z] [] [Info] [SimpleWorker] RunSimpleWorker() finished successfully
21/05/04 10:27:01 ERROR Executor: Exception in task 0.0 in stage 2.0 (TID 2)
java.lang.NullPointerException
        at org.apache.spark.sql.vectorized.ArrowColumnVector.getChild(ArrowColumnVector.java:131)
        at org.apache.spark.sql.execution.python.PandasGroupUtils$.$anonfun$executePython$2(PandasGroupUtils.scala:50)
        at org.apache.spark.sql.execution.python.PandasGroupUtils$.$anonfun$executePython$2$adapted(PandasGroupUtils.scala:50)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
        at scala.collection.immutable.Range.foreach(Range.scala:158)
        at scala.collection.TraversableLike.map(TraversableLike.scala:238)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at org.apache.spark.sql.execution.python.PandasGroupUtils$.$anonfun$executePython$1(PandasGroupUtils.scala:50)
        at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:484)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:490)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage3.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:729)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:340)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:872)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:872)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:127)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
21/05/04 10:27:01 WARN TaskSetManager: Lost task 0.0 in stage 2.0 (TID 2, , executor driver): java.lang.NullPointerException
        at org.apache.spark.sql.vectorized.ArrowColumnVector.getChild(ArrowColumnVector.java:131)
        at org.apache.spark.sql.execution.python.PandasGroupUtils$.$anonfun$executePython$2(PandasGroupUtils.scala:50)
        at org.apache.spark.sql.execution.python.PandasGroupUtils$.$anonfun$executePython$2$adapted(PandasGroupUtils.scala:50)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
        at scala.collection.immutable.Range.foreach(Range.scala:158)
        at scala.collection.TraversableLike.map(TraversableLike.scala:238)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at org.apache.spark.sql.execution.python.PandasGroupUtils$.$anonfun$executePython$1(PandasGroupUtils.scala:50)
        at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:484)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:490)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage3.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:729)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:340)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:872)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:872)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:127)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

21/05/04 10:27:01 ERROR TaskSetManager: Task 0 in stage 2.0 failed 1 times; aborting job

1. It fails to run this example : The example spark/examples/Microsoft.Spark.CSharp.Examples/Sql/Batch/VectorUdfs.cs doesnt run with latest spark 3.0. 

If you think the bug depends on external factors (e.g., dataset), please provide us with a minimal reproducible example that consists of the following items:

- a minimal dataset, necessary to reproduce the error
- the minimal runnable code necessary to reproduce the error, which can be run on the given dataset
- the necessary information on any used packages, .NET runtime version, and system it is run on
- in the case of random processes, a seed for reproducibility

**Desktop (please complete the following information):**
 - OS: Fails on HDI Spark 3.0 as well as Spark 3.0 local setup on windows.
 - Version Spark 3.0

**Comment by suhsteve** [comment]
I just tried `Microsoft.Spark.CSharp.Examples.exe Sql.Batch.VectorUdfs %SPARK_HOME%\examples\src\main\resources\people.json` on `Windows`, using commit `3fb684c50d722f5bb06483adb9458a867fbed4fc` (tag v1.1.1), and with `Spark 3.0.0` and it runs without issue.

@viskumar-microsoft can you give more details related to your setup ?  What version of Microsoft.Spark & Worker did you use ?

**Comment by viskumar-microsoft** [comment]
For local setup: here is what I have
Spark 3.0: https://archive.apache.org/dist/spark/spark-3.0.0/spark-3.0.0-bin-hadoop2.7.tgz
Microsoft.Spark: <PackageReference Include="Microsoft.Spark" Version="1.1.1" />
Worker: https://github.com/dotnet/spark/releases/download/v1.1.1/Microsoft.Spark.Worker.netcoreapp3.1.win-x64-1.1.1.zip 
 (Microsoft.Spark.Worker.netcoreapp3.1.win-x64-1.1.1\Microsoft.Spark.Worker-1.1.1)

**Comment by suhsteve** [comment]
@viskumar-microsoft  I also tried using official released Worker that you linked, as well as the official 1.1.1 nuget and jar, and the Spark 3.0.0 distro.  Did not encounter any issues.  Maybe you can msg me on teams and we can screenshare ?

**Comment by viskumar-microsoft** [comment]
Thanks Steve, it works with Spark 3.0, we needed to upgrade the spark worker to Microsoft.Spark.Worker-1.1.1 in HDI to get this working.
