### ISSUE TITLE
[BUG]: DotnetRunner is mistakenly trying to connect to debug port 5567 when not in debug mode.

### ISSUE THREAD

**Issue by akamor** [dotnet/spark#999]
**Describe the bug**
DotnetRunner is mistakenly trying to connect to debug port 5567 when not in debug mode.

**To Reproduce**

We are launching jobs on AWS EMR via spark-submit.  spark-submit command looks like:

```
spark-submit --deploy-mode cluster --master yarn 
	--conf spark.yarn.appMasterEnv.DOTNET_WORKER_DIR=./worker
	--conf spark.executorEnv.DOTNET_ASSEMBLY_SEARCH_PATHS=.,./worker
	--conf spark.yarn.submit.waitAppCompletion=true
	--conf spark.yarn.maxAppAttempts=1
	--conf spark.executor.memory=1g
	--conf spark.executor.memoryOverhead=1g
	--conf spark.driver.memory=1g
	--conf spark.driver.memoryOverhead=1g
	--conf spark.executor.cores=1
	--conf spark.executor.instances=1
	--conf spark.dynamicAllocation.enabled=false
	--conf spark.sql.legacy.parquet.datetimeRebaseModeInWrite=CORRECTED
	--conf spark.sql.legacy.parquet.datetimeRebaseModeInRead=CORRECTED
	--conf spark.sql.legacy.avro.datetimeRebaseModeInWrite=CORRECTED
	--conf spark.sql.legacy.avro.datetimeRebaseModeInRead=CORRECTED
	--archives worker.zip#worker
	--files <some key in s3>
	--jars <list of jar files>
	--class org.apache.spark.deploy.dotnet.DotnetRunner microsoft-spark-3-0_2.12-1.0.0.jar Allos.Spark e30= EmrSpark
```

This results in a stack trace on the stdout of the driver of this:

```
---> Autofac.Core.DependencyResolutionException: An exception was thrown while activating ?:Microsoft.Spark.Sql.SparkSession.
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (111): Connection refused 127.0.0.1:5567
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at Microsoft.Spark.Network.DefaultSocketWrapper.Connect(IPAddress remoteaddr, Int32 port, String secret) in /mnt/c/Users/adam/Repos/spark/src/csharp/Microsoft.Spark/Network/DefaultSocketWrapper.cs:line 75
   at Microsoft.Spark.Interop.Ipc.JvmBridge.GetConnection() in /mnt/c/Users/adam/Repos/spark/src/csharp/Microsoft.Spark/Interop/Ipc/JvmBridge.cs:line 85
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args) in /mnt/c/Users/adam/Repos/spark/src/csharp/Microsoft.Spark/Interop/Ipc/JvmBridge.cs:line 216
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallStaticJavaMethod(String className, String methodName, Object[] args) in /mnt/c/Users/adam/Repos/spark/src/csharp/Microsoft.Spark/Interop/Ipc/JvmBridge.cs:line 111
   at Microsoft.Spark.Sql.Builder..ctor() in /mnt/c/Users/adam/Repos/spark/src/csharp/Microsoft.Spark/Sql/Builder.cs:line 23
   at Microsoft.Spark.Sql.SparkSession.Builder() in /mnt/c/Users/adam/Repos/spark/src/csharp/Microsoft.Spark/Sql/SparkSession.cs:line 62
```

In our Main() we create our spark session via:

```
            builder.Register(ctx => SparkSession
                    .Builder()
                    .AppName("Allos.SparkHelper")
                    .Config("hive.metastore.connect.retries", 5)
                    .Config("hive.metastore.client.factory.class", "com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory")
                    .EnableHiveSupport()
                    .GetOrCreate())
                .As<SparkSession>()
                .SingleInstance();
```

As you can see we aren't passing 'debug' to the DotNetRunner args.  Is it possible its deciding to go into debug mode via some other variable we are not aware of?

**Comment by imback82** [comment]
Do you see any logs similar to the followings?
https://github.com/dotnet/spark/blob/c79cf8fad49e4760e6f6b4c8fe31a59f0fa306c4/src/csharp/Microsoft.Spark/Services/ConfigurationService.cs#L110

https://github.com/dotnet/spark/blob/c79cf8fad49e4760e6f6b4c8fe31a59f0fa306c4/src/csharp/Microsoft.Spark/Services/ConfigurationService.cs#L114

**Comment by akamor** [comment]
On stdout on the driver I see:

[2021-11-10T20:22:50.1009705+00:00] [2021-11-10T20:22:50.1008602Z] [ip-172-31-83-212] [Info] [ConfigurationService] Using port 35785 for connection.

**Comment by akamor** [comment]
And on stderr on the worker we see:

[2021-11-10T20:23:10.6593535Z] [ip-172-31-95-236] [Info] [ConfigurationService] 'DOTNETBACKEND_PORT' environment variable is not set.
[2021-11-10T20:23:10.6594946Z] [ip-172-31-95-236] [Info] [ConfigurationService] Using port 5567 for connection.

**Comment by imback82** [comment]
Hmm you should see this only in the driver. Why do you see this in the worker? Are you writing some UDFs that can cause this? If so, can you share?

**Comment by akamor** [comment]
Yes, we are using a C# UDF.  The error appears to occur when calling that UDF.  The UDF itself is for demonstrative purposes and just news up a RNG and generates a random integer which is placed in the column.

**Comment by akamor** [comment]
So the UDF itself just generators random values but we wrap it in more complex logic.  Here it is:

```
public static Func<Microsoft.Spark.Sql.Column, Microsoft.Spark.Sql.Column> Generate(
            StructType returnType,
            List<string> columnsInReplacement,
            List<string> columnsOnlyInCondition,
            Broadcast<string> stringifiedReplacement,
            Broadcast<string> stringifiedStatistics,
            string serializerCacheId,
            int baseSeed)
        {
            return Udf<Row>(row =>
                {
     
                    var tRow = new Dictionary<string, object>(allColumns.Count);
                    foreach (var col in allColumns)
                    {
                        var index = row.Schema.Fields.FindIndex(f => f.Name == col);
                        tRow.Add(col, index == -1 ? null : row[index]);
                    }

                  
                    //ERROR HAPPENS IN THIS CALL
                    Program.GeneratorCaller.Execute(resolvedStats, resolvedReplacement, tRow);
                  

                    var modifiedValues = colsInReplacement.Select(c =>
                        {
                            var val = tRow[c];
                            return val is JsonElement el && el.ValueKind is JsonValueKind.Null ? null : (object) val?.ToString();
                        }
                    );

                    var unmodidifedValues = columnsOnlyInCondition.Select(c => tRow[c]);
                    return new GenericRow(modifiedValues.Concat(unmodidifedValues).ToArray());
                },
                returnType
            );
        }
    }
```

Program.GeneratorCaller is declared in Program.cs

```
internal static readonly IGeneratorCaller GeneratorCaller = _container.Resolve<IGeneratorCaller>();
```

The GeneratorCaller itself does not rely on SparkSession in any way.  _container is just an autofac container.

**Comment by akamor** [comment]
Ok, we actually believe we've fixed the issue.  I'm saying this now so you don't spend cycles investigating.  I'm gonna do a writeup a bit later tonight so others can learn from my mistakes. :)

**Comment by akamor** [comment]
The issue was related to a code change on our side.  When we referenced Program.GeneratorCaller in the UDF that caused us to unknowingly try to start a new SparkSession and it couldn't connect to the port on the worker.  What made us realize the issue was seeing logs on the worker.  We hadn't previously realized there were worker logs for this job.  Thanks a lot for your help.
